### ISSUE TITLE
The syscall.SYS_EXIT constant is not defined on Windows

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#1]
If you plan to support Windows OS in the future, I found that the server builds well, except that the SYS_EXIT constant used in [syscall.Exit()](https://github.com/iotexproject/iotex-core/search?utf8=%E2%9C%93&q=SYS_EXIT&type=) is not defined on Windows.

I quickly fixed that with `syscall.Exit(60)`, though I'm not a Go developer therefore a more suitable replacement is probably available.

**Comment by FishMeat** [comment]
wow~

**Comment by raullenchai** [comment]
We should remove "syscall.Exit". Prefer log.Fatal.

**Comment by zjshen14** [comment]
Fixed in: https://github.com/iotexproject/iotex-core/commit/7fac6df704de1e29efe1aa038f82b15d618e690e
