### ISSUE TITLE
Split chain.db into multiple files

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#1003]
**What would you like to be added**:
Chain.db should be split into multiple files maybe of ~100MB each so you can more easily synchronize the tip the chain to another node. If chain.db is 100GB it will be difficult to sync / copy with something like rsync as you will need to freeze the node while you do it.

In addition to splitting the chain.db ideally database filesystem is split into logical directories based on some timestamp , for example 

```
/data/archive/2019-04-09/chain-000.db
/data/archive/2019-04-10/chain-001.db
/data/archive/2019-04-11/chain-002.db
/data/active/chain-003.db
```
This would avoid having large files or lots of files in a single directory, it also means that older data can be archived by administrators to less expensive storage then SSD where active data would exist. When 100MB is exceeded a new file is created and previous file archived into folder of whatever day it might be.

**Why is this needed**:
Ability to backup and restore faster without needing to stop node for long period of time. Ability to have HOT data in /data/active with fast SSD and archived data on Spinning drive (1/4 cost generally per GB)

**Comment by raullenchai** [comment]
My impression is this feature has been implemented. @zjshen14 pls confirm and give the instructions for turn it on here.

**Comment by lzxm160** [comment]
refer to #1421 ,need two config options:
SplitDBSize: 640 //The unit is M，it will split db when that is not 0,default is 0
SplitDBHeight: 2000000 // This height must be higher than the current height, that means since this height will split db

**Comment by raullenchai** [comment]
cc @dustinxie 

Done
