### ISSUE TITLE
"current node is not a delegate" is not accurate

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1025]
**What would you like to be added**:
"current node is not a delegate" has ambiguity, which means "current node is not an active consensus delegate but it is a consensus delegate" for consensus delegates.

**Why is this needed**:

**Comment by raullenchai** [comment]
We should have the same terms as used by the frontend for all logs, e.g.,
- active consensus delegate
- consensus delegate
- delegate
- candidate

**Comment by yutongp** [comment]
This log is printed by all nodes
