### ISSUE TITLE
Investigate TravisCI vs CircleCI

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1026]
We are now heavy on Circle CI and need to investigate if TravisCI fits us better, e.g.,
-- better performance/scalability
-- better price
-- easier to use
-- others.

**Comment by FeirenK** [comment]
TravisCI merit:
1, support  window
2, Configuration files simply automatically select the installation version or multiple versions

**Comment by raullenchai** [comment]
can u also compare the pricing model?

**Comment by raullenchai** [comment]
Thanks.
