### ISSUE TITLE
Script for collecting Machine/System info (a.k.a. systemstat)

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1028]
Assume the system is running Ubuntu. Here are the metrics we need:
- cpu, memory, hard disk size, network interfaces
- load test for getting IOPS (fio) and bandwidth (iperf)
- os release
- kernel version

Examples:
- https://bash.cyberciti.biz/guide/Getting_information_about_your_system
- https://github.com/myfreeweb/systemstat

**Comment by zjshen14** [comment]
And iperf for bandwidth: https://www.linode.com/docs/networking/diagnostics/install-iperf-to-diagnose-network-speed-in-linux/

**Comment by FeirenK** [comment]
I thought Prometheus collected metrics,grafana showed that

http://34.228.208.0/grafana/d/xuNP2YgWk/node-exporter-full?orgId=1&var-job=node&var-node=172.31.40.15&var-port=9100&from=1555320523186&to=1555406923186

**Comment by raullenchai** [comment]
This script is expected to be run even before they have iotex-core installed. We want to collect some metrics about the machine itself.

**Comment by FeirenK** [comment]
https://github.com/iotexproject/iotex-bootstrap/pull/18
