### ISSUE TITLE
Set DefaultGas to 1Qev

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#1062]
https://github.com/iotexproject/iotex-core/blob/a89900bd7f7a77ba04aff748e5e747c86c1bd18d/config/config.go#L159

**Comment by raullenchai** [comment]
Can u elaborate what is wrong here @ququzone ?

**Comment by ququzone** [comment]
> Can u elaborate what is wrong here @ququzone ?

When user estimate GasLimit through `EstimateGasForAction` API and recent Block No any actions, the API will return DefaultGas and Action Pool only access the action's gas limit greater than 1Qev, so user use DefaultGas as his action gas limit, this action will fail. @raullenchai
