### ISSUE TITLE
Cleanup native voting system code

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1071]
We eventually chose to vote via ethereum, so that the native voting system code is no longer useful and we could delete it. There are a bunch of things need to do:

1. Remove voting action's reference in the test code or replace it with transfer action if necessary to make the test pass.
2. Remove voting action protobuf and goland definition and reference in the prod code.
3. Remove voting protocol registration in the chain service, and the tests
4. Remove voting protocol, and the voting logic handling in account protocol (one important thing here is to evaluate if it's a breaking change)
5. Use lifeLongDelegatesProtocol by default to feed delegate info to make blockchain be able to run by default.

**Comment by zjshen14** [comment]
@lzxm160 would you please help this task?

**Comment by lzxm160** [comment]
no problem
