### ISSUE TITLE
TestBlockEpochReward sporadica failure

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1073]
**Which jobs are failing**:

build_test_docker

**Which test(s) are failing**:

TestBlockEpochReward

**Since when has it been failing**:

Not sure

**Testgrid link**:

https://circleci.com/gh/iotexproject/iotex-core/5920?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Reason for failure**:

Need to trouble shoot

**Anything else we need to know**:

N/A

**Comment by zjshen14** [comment]
https://circleci.com/gh/iotexproject/iotex-core/5883?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by raullenchai** [comment]
Saw again
