### ISSUE TITLE
ioctl migrates to use golang SDK

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1099]
**What would you like to be added**:

**Why is this needed**:

**Comment by dustinxie** [comment]
@lzxm160  i had a PR doing this for actionhash.go some time back, code is pushed to 'origin/ioctl-use-sdk'
you can pull that branch and start from there to finish other parts of ioctl

**Comment by lzxm160** [comment]
> @lzxm160 i had a PR doing this for actionhash.go some time back, code is pushed to 'origin/ioctl-use-sdk'
> you can pull that branch and start from there to finish other parts of ioctl

sure,ths

**Comment by raullenchai** [comment]
Any update?
