### ISSUE TITLE
fork problem

### ISSUE THREAD

**Issue by FishMeat** [iotexproject/iotex-core#11]
when i forked the project, and run make build, a error below:
`
make build
go build -o ./bin/server -v ./server
github.com/fishmeat/iotex-core/vendor/github.com/golang/protobuf/proto
github.com/fishmeat/iotex-core/server
#github.com/fishmeat/iotex-core/server
server/main.go:79:60: cannot use bcb (type func("github.com/fishmeat/iotex-core/vendor/github.com/golang/protobuf/proto".Message) error) as type func("github.com/iotexproject/iotex-core/vendor/github.com/golang/protobuf/proto".Message) error in argument to rpcservice.NewChainServer
make: *** [build] Error 2
`

**Comment by zjshen14** [comment]
Would you please try running `glide update` and `glide install` before `make build`?

**Comment by FishMeat** [comment]
the project dir must github.com/iotexproject/iotex-core ? I forked is github.com/fishmeat/iotex-core

**Comment by zjshen14** [comment]
Try update this line: https://github.com/iotexproject/iotex-core/blob/a46bb389e072557bd4bf6c3f92417386cb1a9159/glide.yaml#L1. Replace it with `github.com/fishmeat/iotex-core`. And then run `glide update` and `glide install``

**Comment by FishMeat** [comment]
thanks
