### ISSUE TITLE
add new fields to BlockMeta

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-core#1107]
**What would you like to be added**:
add new fields to BlockMeta
**Why is this needed**:
![56892024-eb8a2b80-6ab0-11e9-8c21-29a27b540d36](https://user-images.githubusercontent.com/12439992/56948301-4760bd00-6b62-11e9-93c3-f891fdf17400.jpg)
these fields now missing on the new design of iotex-explorer block detail page. should we need add these fields in blockMeta?

related: https://github.com/iotexproject/iotex-explorer/issues/390

**Comment by raullenchai** [comment]
@dustinxie pls take a look

**Comment by JIUQIWANG** [comment]
Ok,I will start working on it.

**Comment by JIUQIWANG** [comment]
I have done the backend api preparation in iotex-core, could you help me to modify our iotex-antenna repo to obtain these data ? Thanks! @uu-z
