### ISSUE TITLE
GRPC streaming APIs

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1124]
Feature requests:

- Listen to block (or block header only) once it's created
- Listen to receipts

What else?

**Comment by puncsky** [comment]
listen to logs
listen to whether the node is syncing data

**Comment by puncsky** [comment]
listen to a certain payload content

**Comment by puncsky** [comment]
bloom filter subscribe to a certain ERC20 token contract

**Comment by lizhefeng** [comment]
block (including receipt) listener is done.

**Comment by zjshen14** [comment]
> listen to whether the node is syncing data

@puncsky  what does this mean?
