### ISSUE TITLE
[ioctl] -p does not support floating number

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-core#1126]
`ioctl action invoke io1mactnrnhzpcfw754rlwgv4luw888yrwqx0kl8k -s xxx -l 30000 -b 18160ddd -p 0.1` does not work.

**Comment by zjshen14** [comment]
I think this on purpose for ioctl

**Comment by CoderZhi** [comment]
Likai said it could be float

**Comment by guo** [comment]
so it is a wontfix?

**Comment by zjshen14** [comment]
https://testnet.iotexscan.io/action/422b7a377aa305a99cabb8065d87db64126c931d928b577f0401e86979e0821a

Verified it's working.

0.1 isn't because it's bellow the gas price limit set on the nodes
