### ISSUE TITLE
Key shouldn't be stored in the config file as a plain text

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1130]
**What would you like to be added**:

Encrypt the key in some way (e.g., keystore) and load it the server software

**Why is this needed**:

Prevent key from being hacked

**Comment by hao1022** [comment]
Ok, once this feature is implemented, please also consider adding a similar mechanism to "ioctl action", I am pretty sure this is going to be wide needed

**Comment by lzxm160** [comment]
parity way: keystore+file with password of keystore

**Comment by lzxm160** [comment]
need to split tasks and reopen
