### ISSUE TITLE
Revive test coverage

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1140]
Test coverage reported by https://codecov.io/gh/iotexproject/iotex-core is growing lower, as we didn't write enough test cases for newly added code. Two packages are most worth adding more tests are: action/protocols and blockchain.

**Comment by lzxm160** [comment]
still need improve test coverage

**Comment by raullenchai** [comment]
Thanks for pushing this one consistently.

**Comment by lzxm160** [comment]
need more tests to fix coverage
