### ISSUE TITLE
[ioctl] after account being deleted, it still shows in alias list

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1153]
### What version of iotex-core are you using (`ioctl version`)?
latest

### What operating system and processor architecture are you using?
iOS

### What did you do? If possible, provide a recipe for reproducing the error.
ioctl account delete xxx

### What did you expect to see?
xxx deleted from both account and alias

### What did you see instead?
xxx still shows in alias list

**Comment by lzxm160** [comment]
I tested this in ubuntu system,there's no such problem,I dont have ios system,pls assign to another?
