### ISSUE TITLE
Export Public Key and Sign Message

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1155]
**What would you like to be added**:
1. Export Public Key of an account
2. Sign a message with private key

**Why is this needed**:
1. Share public key to other ppl
2. Sign a private message, e.g., identity for login

**Comment by zjshen14** [comment]
@lzxm160 would you please help?

**Comment by lzxm160** [comment]
> @lzxm160 would you please help?

sure
