### ISSUE TITLE
"ioctl config set endpoint" should have basic sanitization of the given url

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1156]
```
ioctl config set endpoint api.mainnet.iotex.one:$43
endpoint is set to api.mainnet.iotex.one:
```

This looks bizarre. Basic sanitization is needed.

**Comment by lzxm160** [comment]
> api.mainnet.iotex.one:$43

as I tested，even check function added, this cannot be fixed,because $  belongs to linux system,linux system execute this $ command before passed to our program,unless our user add '\'

![image](https://user-images.githubusercontent.com/5837417/57564472-d2517b00-73de-11e9-8fb7-348c46dff4ce.png)
