### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1163]
### What version of iotex-core are you using (`ioctl version`)?

v0.5.1

### What did you do? If possible, provide a recipe for reproducing the error.

{"level":"error","ts":1557774475.7048879,"caller":"committee/committee.go:515","msg":"failed to fetch result by height","ioAddr":"io1kt8e5stjutvh8q7s88jeskr4dvp7jzh3prhrhd","networkAddr":"0.0.0.0:4689","error":"Post https://mainnet.infura.io/v3/b0773072278b4700b70dce8dcd74dd67: read tcp 172.17.0.2:55302->34.202.251.153:443: read: connection reset by peer","height":7674500,"tried":1}

**Comment by zjshen14** [comment]
It's the issue on iotex-election. Move it to https://github.com/iotexproject/iotex-election/issues/66
