### ISSUE TITLE
Sporadic TestBlockEpochReward failure

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1173]
**Which jobs are failing**:

https://circleci.com/gh/iotexproject/iotex-core/6369

**Which test(s) are failing**:

TestBlockEpochReward

**Since when has it been failing**:

Not sure

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by raullenchai** [comment]
@Frankonly pls help with this one.
