### ISSUE TITLE
Release windows version of ioctl executable

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1201]
**What would you like to be added**:

See the title

May need to validate all functions (in particularly file, io related) still work on windows

**Why is this needed**:

Some delegates are using windows

**Comment by FeirenK** [comment]
On Windows The master branch builds exe every day, 
Download: https://s3-ap-southeast-1.amazonaws.com/ioctl/ioctl-windows-amd64.exe

**Comment by zjshen14** [comment]
does `curl https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli.sh | sh -s "unstable"` work for windows case?

**Comment by FeirenK** [comment]
It is best to download directly (S3 url),  otherwise you need to install curl tools
