### ISSUE TITLE
Miss  listen to/query events for Contract

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#1211]
**What would you like to be added**:

Support api for query block logs. similar eth `eth_getLogs` and `eth_getFilterLogs`

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterlogs

**Why is this needed**:

facilitate dapp development

**Comment by dustinxie** [comment]
implemented in PR1301, will check-in soon
