### ISSUE TITLE
Nightly build keeps failing

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1247]
### What version of iotex-core are you using (`ioctl version`)?

master

### What operating system and processor architecture are you using?

darwin

### What did you do? If possible, provide a recipe for reproducing the error.

It's nightly ci job

### What did you expect to see?

Darwin CI job should succeed.

### What did you see instead?

Darwin CI job failed. For example: https://circleci.com/gh/iotexproject/iotex-core/6641

**Comment by FeirenK** [comment]
https://github.com/iotexproject/iotex-core/pull/1262
