### ISSUE TITLE
Handle nonce update uniformly

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1251]
We shouldn't require every protocol to update the nonce separately upon an action. Account protocol handler should process and increment the nonce uniformly

**Comment by zjshen14** [comment]
This change may result in incompatible change

**Comment by lzxm160** [comment]
For account transfer protocol,according to handleTransfer in transfer.go,the sequence is:
1、create account if account not exist, state changed
2、if raCtx.BlockHeight < p.pacificHeight，call rewarding.DepositGas that will change state
3、if recipientAcct.IsContract() and raCtx.BlockHeight >= p.pacificHeight，call rewarding.DepositGas that will change state
4、SetNonce
5、StoreAccount

If increase nonce before call handleTransfer,the sequence will be:
1、create account if account not exist, state changed
2、SetNonce, state changed
3、if raCtx.BlockHeight < p.pacificHeight，call rewarding.DepositGas that will change state
4、if recipientAcct.IsContract() and raCtx.BlockHeight >= p.pacificHeight，call rewarding.DepositGas that will change state
5、StoreAccount, state changed

Only if rewarding.DepositGas is not called,final digest is the same.

**Comment by lzxm160** [comment]
This change may result in incompatible data,we may fix this in beta launch(iotex 2.0),that will regenerate genesis,rerun all actions and generate new digest.
