### ISSUE TITLE
Show more user friendly messages

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1285]
For ioctl, some of the outputs are not readable. E.g., for ioctl alias set command, the output is "set"; for ioctl xrc20 balanceOf, if no balance, we still output "Raw output:\nOutput in decimal: <nil>".

**What would you like to be added**:
Review all commands, and adjust output.

**Why is this needed**:

**Comment by raullenchai** [comment]
@JIUQIWANG is this done?

**Comment by JIUQIWANG** [comment]
No, yesterday I have a PR to modify something I found and something which Zhi have mentioned. But it is have not been reviewed yet. #1398
