### ISSUE TITLE
Setup up the process of testing compatibility against mainnet

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1290]
The goal is to test if we have breaking change that isn't gated by fork block height.

To do this, every period (e.g., 1 day) we pick the latest master, and deploy it as a full node in the mainnet, and check if the node could sync and process blocks successfully. This will not be able to capture the breaking change in consensus, but should help anything around state transition.

**Comment by FeirenK** [comment]
Some don't understand

1, How deploy a full node in the mainnet ? 
    
2, check if the node could sync and process blocks successfully?
   By what command?

**Comment by zjshen14** [comment]
> 1, How deploy a full node in the mainnet ?

Check the instructions here: https://github.com/iotexproject/iotex-bootstrap

> 2, check if the node could sync and process blocks successfully?

The most straightforward check is the block heigh is keep growing. You can check ip/hostname:8080/metrics, and look up this record: iotex_heartbeat_status{source="1",status_type="blockchainHeight"} 513030

**Comment by FeirenK** [comment]
Per day(1AM ) Redeploy full node  and detect change (status_type="blockchainHeight") every 30 minutes 
if not change , save s.log to AWS S3 : https://s3-ap-southeast-1.amazonaws.com/ioctl/
blockchainHeight sync status monitor: 
http://monitor.iotex.world/d/l5XspfkZz/geth-full-node?orgId=1&panelId=310&fullscreen
