### ISSUE TITLE
Node stopped syncing blocks after connection fails, can only recover by restarting the node

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1307]
report from stakingteam.com

i found an issue that I am investigating and managed to reproduce it on 2 different nodes.
The iotex node, after a connection problem, fails to recover by itself. The synchronization of the blocks stops but everything else seems to work properly. Readiness and liveness probe status are "ok" even if it is not true.
The only way to restart the synchronization is to stop and restart the node

Ubuntu 18.04
8 vCPU / 32gb RAM, 500 ssd nvme
1gb connection

![stop-syncing](https://user-images.githubusercontent.com/12551272/60037316-12567f80-9666-11e9-82c9-ca074ea7d418.jpg)

**Comment by raullenchai** [comment]
connection resumption is missed?

**Comment by raullenchai** [comment]
Let's close this one which is too stale
