### ISSUE TITLE
execution amount can not be set to empty

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1309]
unmarshal proto set "" to bigInt(0)
marshal proto then set bigInt(0) to "0"
then sig verification will be fail

**Comment by zjshen14** [comment]
@yutongp can you check if other action, such as Transfer has the similar problem?

**Comment by raullenchai** [comment]
any update?

**Comment by raullenchai** [comment]
any update?

**Comment by yutongp** [comment]
I think @zjshen14 and me already agreed offline that this issue will not be fix in core to avoid nil ptr issue for now. current fix will on all on sdk/client side to avoid send out empty arg but 0 value instead
