### ISSUE TITLE
Add blocksync protocol to proactively ask for the peers' block height

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#131]
Currently, a node will only passively listen to the flying blocks in the P2P network, request the missing blocks between the flying block height and its own top block height. It could happen that there's no flying blocks, but a node is not up-to-date in terms of blockchain. In this case, it should be able to proactively ask neighbors for the top block height they see

**Comment by raullenchai** [comment]
@xiaxiangzhou @zjshen14 we still want this?

**Comment by zjshen14** [comment]
we used a different approach
