### ISSUE TITLE
Claim Reward always return invalid hash on Testnet

### ISSUE THREAD

**Issue by yxguo2536** [iotexproject/iotex-core#1315]
I have build and join the Testnet following  the step recorded in this document:
https://github.com/iotexproject/iotex-bootstrap#join-testnet
and i can use `ioctl node delegate` to find the delegate node in Testnet.

now i want to try the token/data transcation, so i think i will need to get some token, then transfer it out.

but when i try `ioctl action claim 100 '' -l 10000 -p 0 -s yxguo` to get some token , it always return invalid hash.
```
Enter password #yxguo:


version: 1  nonce: 1  gasLimit: 10000  gasPrice: 0 Rau
senderAddress: io14xah9le5ul9sk9hfgpwndzx4py9g9cumpc94tf (yxguo)
version: 1
nonce: 1
gasLimit: 10000
gasPrice: "0"
claimFromRewardingFund: <
  amount: "100000000000000000000"
>
senderPubKey: 04956a66470e240bdd6e418d65743860c13f256686adb860a1d50192b869ba34eb785e008cd7698a2e92cfac0c427562b92aefc34a068bd2c865056edf695340aa
signature: 2933adae5a62d6afcc0ba0b0fc6d16aa24d43322017ce6fde652a039fde2b6fd4f777114041959482fee941ed32a762f8ba6cdd3bc0efb44158e07027ec9943c01

Please confirm your action.
Type 'YES' to continue, quit for anything else.
YES

Action has been sent to blockchain.
Wait for several seconds and query this action by hash:
f3c8c08cb01e03a1605224353a1f23145ebb085627b8e679c975c3e36b748cfb
```

query the action:
```
# ioctl action hash f3c8c08cb01e03a1605224353a1f23145ebb085627b8e679c975c3e36b748cfb
Error: rpc error: code = Unavailable desc = action hash f3c8c08cb01e03a1605224353a1f23145ebb085627b8e679c975c3e36b748cfb does not exist in pool: invalid hash
```

and of course my balance still remain 0 :
```
# ioctl account balance yxguo
io14xah9le5ul9sk9hfgpwndzx4py9g9cumpc94tf: 0 IOTX
```

it seem my request was not accepted, but i don't know what's wrong.

**Comment by lizhefeng** [comment]
@yxguo2536 Your guess is right. The claim action is rejected by action pool because you set the gas price to zero which is lower than the minimum gas price limit 1 Qev. To get some testnet token, please use our faucet tool [here](https://member.iotex.io/tools/faucet).
