### ISSUE TITLE
Implement CLI based on blockchain APIs

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#132]
Background: We have a basic implementation of CLI but we have recently added a bunch of new APIs (see `explorer.idl` for more details). However, CLI only wraps over a very limited amount of them. We need to support all or most our APIs from the command line. And a step back, we need to rethink the framework/layout of CLI.

Requirement: We need a command line tool that interfaces with the blockchain APIs that can:
-- be configured to talk to a proper endpoint
-- get blockchain states
-- issue txs
-- create/update/manage accounts

**Comment by raullenchai** [comment]
[IOCTL RFC.pdf](https://github.com/iotexproject/iotex-core/files/2870606/IOCTL.RFC.pdf)

**Comment by raullenchai** [comment]
@lizhefeng @zjshen14 pls help @ashishsnigam to understand the context

**Comment by ashishsnigam** [comment]
@raullenchai @zjshen14 Just a suggestion for framework/layout of cli for iotexproject. We can follow similar approach as followed in docker cli project. Please see attached screenshot of docker code base.  We are already on similar line.

ioctl [resource] [verb] [param] [flags]
we can add folder per resource and then with in this folder, add go files as per verbs available.
For eg: ioctl blockchain [list|get|show] ==> will add one folder named blockchain and 3 go files for 3 verbs. 

![docker_cli_example](https://user-images.githubusercontent.com/8629099/52942800-b6b37700-3391-11e9-9cc5-561cac2e1bb3.png)

**Comment by ashishsnigam** [comment]
Also while developing cli, put comment to specify complete cli path like  
// NewCopyCommand creates a new `docker cp` command

similarly in iotex context 
// heightCmd creates a new `ioctl blockchain height` command

**Comment by raullenchai** [comment]
@ashishsnigam both LGTM.

**Comment by raullenchai** [comment]
I've  setup the skeleton: https://github.com/iotexproject/iotex-core/tree/master/cli/ioctl

**Comment by raullenchai** [comment]
I have breakdown tasks for this. No need to keep the umbrella task.
