### ISSUE TITLE
Make crypto computation tolerate client heterogeneity

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1320]
**What would you like to be added**:

1. Public key may start or not start with 04.
2. V of signature (the last byte) may be 0, 1 or 27, 28.

**Why is this needed**:

We're now increasing the support from the clients in different programming languages and libraries.

**Comment by zjshen14** [comment]
1. createSecp256k1KeyPair in web3j will create a keypair, which could export the public key (64 bytes) without 04 prefix, but geth will.

2. web3j signs the message, and v of the signature is 27 or 28, but geth is 0 or 1 (subtracted by 27)

We use geth at our server side, but we have more clients written with different programming language and libraries.

It's better to provide tolerance to different version of pk, sig (or even something else), it is worthwhile to study how geth handle this first

**Comment by lzxm160** [comment]
ok,no problem
