### ISSUE TITLE
Action by address seems still not to be sorted by timestamp

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1324]

**Comment by zjshen14** [comment]
@yutongp would you please provide the link the address you encountered the issue yesterday?

**Comment by yutongp** [comment]
https://testnet.iotexscan.io/address/io1gakgrsnsxmg9ed0tlcc2ukxzxdg6v8z2glw82e

**Comment by Frankonly** [comment]
Already fixed
