### ISSUE TITLE
For produced blocks, show foundation bonus and block reward

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1331]
e.g., https://www.iotexscan.io/block/591568

Do we need any backend support?

@zjshen14 @JIUQIWANG

**Comment by zjshen14** [comment]
As they're the fixed number, we don't need to do anything on backend. To tell who get rewarded, we just need to parse the pubkey of the block

**Comment by JIUQIWANG** [comment]
Ok, should we just modify javascript for this issue?

**Comment by raullenchai** [comment]
@JIUQIWANG pls close this one after opening an issue in iotex-explorer and assign to @puncsky for dispatching

**Comment by JIUQIWANG** [comment]
@raullenchai Ok, I have created one in iotex-explorer and Zhi help me assign it to gyanpgupta. Should I reassign to Tian or reopen a issue?

**Comment by raullenchai** [comment]
No need. let's close this one.
