### ISSUE TITLE
Keep track of account state changes

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-core#1346]
**What would you like to be added**:
A journal-like structure to keep the record of state changes.
**Why is this needed**:
We want to have an overview of all the accounts (including account balance) currently existing on the chain. But we don't have the record of state changes (mostly the state changes resulted from executions). Need to figure out a way to keep track of the account state changes in all kinds of actions. Please take a look at https://github.com/ethereum/go-ethereum/blob/36f81118f6d00713dbf8d1caf168ad937e0f1a90/core/state/statedb.go#L90 for your reference.

**Comment by raullenchai** [comment]
@Frankonly what is the progress on this one?

**Comment by zjshen14** [comment]
@lizhefeng if you want to iterate through all the accounts you can use the cursor from boltdb: https://github.com/etcd-io/bbolt. Check the readme
