### ISSUE TITLE
Get action by address is inefficient if the account has a lot of actions

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1359]
**What would you like to be added**:

Add the index or something similar to make it fast to get action by address, start, count.

**Why is this needed**:

Nowadays, we need to fetch all the actions by an address, and sort in memory, and then get [start, count) interval.

**Comment by lzxm160** [comment]
After #1404 merged,this will be restart

**Comment by lzxm160** [comment]
Now we are using CountingIndex to store actions,one account store in one bucket.
 CountingIndex is a bucket of <k, v> where
 k consists of 8-byte whose value increments (0, 1, 2 ... n) upon each insertion
position 0 (k = 0x0000000000000000) stores the total number of items in bucket so far
