### ISSUE TITLE
Shorten block interval to 5sec

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1377]
**What would you like to be added**:

A few config changes will be required, e.g, reward amount, block interval, consensus configs, ...

**Why is this needed**:

Make consensus faster to support some dapps, such as gaiming

**Comment by zjshen14** [comment]
Please help to benchmark the perf of 48 consensus delegates and 5sec interval. Thanks @yutongp

**Comment by zjshen14** [comment]
Based on the experiment, it's 48 consensus nodes with 5sec block interval works fine (usually < 1 sec). @dustinxie would please help pushing the test to testnet

**Comment by raullenchai** [comment]
@dustinxie is evaluating all impact on the product side (member.iotex.io, explorer, wallet, dapp and so on)...
