### ISSUE TITLE
Reduplicative ations with same hash shows in action list

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-core#1386]
https://iotexscan.io/address/io15ed8a4lyqgglm7z9wdq40kjksc0j5z0erw5v3x

![image](https://user-images.githubusercontent.com/16026265/61455915-6881be80-a997-11e9-977f-e663568ee57d.png)

![image](https://user-images.githubusercontent.com/16026265/61455929-72a3bd00-a997-11e9-9ac0-89bc56b24d1b.png)

**Comment by zjshen14** [comment]
@lzxm160 Is this the bug you're talking about in https://github.com/iotexproject/iotex-core/pull/1384

**Comment by lzxm160** [comment]
> @lzxm160 Is this the bug you're talking about in #1384

yes

**Comment by wowa1234567** [comment]
Würde das gehen auf N26 app zu übertragen? 😅
