### ISSUE TITLE
Chain has moved to tip height but consensus is stuck S_ACCEPT_PRECOMMIT_ENDORSEMENT

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1388]
It should be S_ACCEPT_PRECOMMIT_ENDORSEMENT of a previous block height. Suspect that the clibration doesn't happen on block sync.

**Comment by raullenchai** [comment]
Any update?

**Comment by dustinxie** [comment]
Zhi fixed in https://github.com/iotexproject/iotex-core/commit/c06239d6a6b866670769ee8e31c33f3296d63fd2
