### ISSUE TITLE
Support partitioning db by block height

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1395]
**What would you like to be added**:

Nowadays all block data are written into the same db file. It is not friendly to daily backup, which theoretically only needs to backup incremental block data.

**Why is this needed**:

Let's make the block data storage to partitioned by block height physically. For example, 1-8640 blocks are stored in chain-1.db, and 8641-19280 blocks are stored in chain-2.db

**Comment by lzxm160** [comment]
1421,split by db size
