### ISSUE TITLE
"ioctl account balance" panic

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1409]
ioctl account balance
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iotexproject/iotex-core/ioctl/cmd/account.glob..func1(0x54fc920, 0x5545350, 0x0, 0x0, 0x0, 0x0)
	/Users/distiller/iotex-core/ioctl/cmd/account/accountbalance.go:26 +0x70
github.com/spf13/cobra.(*Command).execute(0x54fc920, 0x5545350, 0x0, 0x0, 0x54fc920, 0x5545350)
	/Users/distiller/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x54faca0, 0x0, 0x0, 0x485c6bc)
	/Users/distiller/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/distiller/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/iotexproject/iotex-core/ioctl/cmd.Execute()
	/Users/distiller/iotex-core/ioctl/cmd/root.go:34 +0x2e
main.main()
	/Users/distiller/iotex-core/ioctl/ioctl.go:14 +0x20

**Comment by Frankonly** [comment]
Which version @raullenchai

**Comment by raullenchai** [comment]
```
ioctl account balance
Error: 12, use "ioctl config set defaultacc ADDRESS|ALIAS" to config default account first
```

"Error 12" is not user-friendly.

**Comment by raullenchai** [comment]
pls fix and close this issue asap @Frankonly
