### ISSUE TITLE
Upgrade to use golang 1.12

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1418]
cc @yutongp

**Comment by zjshen14** [comment]
We're already on 1.12

**Comment by raullenchai** [comment]
should update readme.md

**Comment by zjshen14** [comment]
I guess our code is still compilable with 1.11.x. If nothing is broken with 1.11.x, maybe it's not necessary to enforce 1.12

@koseoyoung can you help test golang 1.11.x compatibility?

**Comment by koseoyoung** [comment]
I've tested with the version go1.11.5, there was no error to build it. Should I test the version higher than 1.11.5?

**Comment by zjshen14** [comment]
Thanks for the experiments! I think we're good from now. Feel free to close the isse
