### ISSUE TITLE
Contract Address in receipt is empty

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1426]
### What version of iotex-core are you using (`ioctl version`)?

v0.7.2 or latest master

### What did you expect to see?

https://www.iotexscan.io/action/792cbd45abdef93f3f7f46e5e5cf3aa829e1a873f7e236646e78abf502aa5222

expect to see Contract Address = io1p99pprm79rftj4r6kenfjcp8jkp6zc6mytuah5

### What did you see instead?

empty

**Comment by zjshen14** [comment]
This is probably not a bug. Check this: https://github.com/ethereum/go-ethereum/blob/947f5f2b152e18dfab2bec72c99ef76e1d851764/core/state_processor.go#L117-L120

The contract address in the receipt is only used for the case when the contract is created. This aligns with what we did

**Comment by koseoyoung** [comment]
Oh yes, that's why when we are not creating contract but executing the contract, we don't put contract address in receipt. https://github.com/iotexproject/iotex-core/blob/5cda06ed2f957a8ba3f6b3dbeb4a77c492d9e57f/action/protocol/execution/evm/evm.go#L236

**Comment by zjshen14** [comment]
Yes, prefer a "not fix"

**Comment by zjshen14** [comment]
BTW, the fix could be the a ui improvement. Whenever it's a contract execution, it should just hide this row. cc @puncsky
