### ISSUE TITLE
Blocksync didn't make progress for quite long

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1432]
We added a new node, which start to sync from block 1, and was stuck on getting new blocks around reaching 600K+ blocks. It seems that eth data syncing was still moving forward regularly, but block data syncing showed no logs. After restarting, block data syncing resumed. It seemed that there's some corner case that blocksync module would just hang.

**Comment by lzxm160** [comment]
let me reproduce it first

**Comment by zjshen14** [comment]
@lzxm160 we suspected it's related to our cluster problem. Please hold, we will update you soon

**Comment by lzxm160** [comment]
> @lzxm160 we suspected it's related to our cluster problem. Please hold, we will update you soon

ok

**Comment by zjshen14** [comment]
Validated. It wasn't a problem
