### ISSUE TITLE
Make GetBlockMetas API only read block header

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1441]
Currently it uses the getBlock method form blockchain interface, which is more expensive than reading a header, especially when there are a lot of transactions. Blockchain interface has the getBlockHeader method, which only reads the the header data. We should migrate to use this method instead. One challenge is that the number of transactions is not in the header. We need to add a field. Also, this will change the data structure of header, which is a breaking change. It needs to be gated by the Bering height

**Comment by raullenchai** [comment]
@5sWind
