### ISSUE TITLE
Failed to build ioctl on Windows after commit 2ea4d58

### ISSUE THREAD

**Issue by Frankonly** [iotexproject/iotex-core#1442]
Failed to build ioctl on Windows after commit [2ea4d58](https://github.com/iotexproject/iotex-core/commit/2ea4d58052d79f9bd064106fa7a13fb21c98e215)

The probable cause is that new evm imports github.com/karalabe/usb indirectly, which causes error with MinGW on windows.

**Comment by raullenchai** [comment]
@dustinxie pls take a look at this.
