### ISSUE TITLE
Show XRC20 token transfer in receiver's tx logs bug 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-core#1454]
### What version of iotex-core are you using (`ioctl version`)?

https://iotexscan.io/action/77eed89c8307a96a8f1bc7d54eb6749f20940ca46cf47a8bf92834835b7a867e

### What did you expect to see?

receiver shows XRC20 tx

### What did you see instead?

but in receiver's tx logs, I didn't see this XRC20's tx log
https://iotexscan.io/address/io1cnq64jkkrg2ga2fx2q0209mgkw93js8c0a8rgc

**Comment by puncsky** [comment]
https://github.com/iotexproject/iotex-explorer/issues/951

**Comment by lzxm160** [comment]
I think we should add a special page for xrc20,like this https://etherscan.io/token/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0?a=0x5af33b044fc0b24758552a2b3efb8b27bb06b038

**Comment by lizhefeng** [comment]
In this case, receiver is the contract itself, so the action will only be listed under the contract address rather than the real recipient.

**Comment by raullenchai** [comment]
@puncsky pls drive this one.
