### ISSUE TITLE
After 1466 merged,need to check if there's a conflict in writing the same table with analytics

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-core#1469]
After #1466 merged,we need to check if there's a conflict in writing the same table with analytics,
iotex-core and iotex-analytics will write the same table,account_histroy

**Comment by Frankonly** [comment]
[This RP](https://github.com/iotexproject/iotex-analytics/pull/78) is related.

**Comment by lzxm160** [comment]
INSERT sets an exclusive lock on the inserted row. This lock is an index-record lock, not a next-key lock (that is, there is no gap lock) and does not prevent other sessions from inserting into the gap before the inserted row.
Prior to inserting the row, a type of gap lock called an insert intention gap lock is set. This lock signals the intent to insert in such a way that multiple transactions inserting into the same index gap need not wait for each other if they are not inserting at the same position within the gap. Suppose that there are index records with values of 4 and 7. Separate transactions that attempt to insert values of 5 and 6 each lock the gap between 4 and 7 with insert intention locks prior to obtaining the exclusive lock on the inserted row, but do not block each other because the rows are nonconflicting.

When transfer happens in smart contract, for example multisend contract,there will be two kinds of insert,one from iotex-core,one from iotex-analytics.

I tested one case using multisend,
multisend contract address:io13mduvrakl046d35qx6a268n5u5vdcqsdy98hk4
send from:io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg,
send to two address:io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms,io1tdfyk5gqrfas22am6sw732twxyjcnl6xqe850s
There is 8 inserts like this:
1、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io13mduvrakl046d35qx6a268n5u5vdcqsdy98hk4', 3000000000000000000, 0);
2、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg', 0, 3000000000000000000);
3、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms', 1000000000000000000, 0);
4、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io13mduvrakl046d35qx6a268n5u5vdcqsdy98hk4', 0, 1000000000000000000);
5、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io1tdfyk5gqrfas22am6sw732twxyjcnl6xqe850s', 1000000000000000000, 0);
6、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io13mduvrakl046d35qx6a268n5u5vdcqsdy98hk4', 0, 1000000000000000000);
7、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg', 1000000000000000000, 0);
8、INSERT INTO `account_history`(`epoch_number`, `block_height`, `action_hash`, `address`, `in`, `out`) VALUES (18312, 878974, 'b4d81af254f2028e7a8bb7768ee9be0e95045c1d4239e61c8a44fc5ab51f1241', 'io13mduvrakl046d35qx6a268n5u5vdcqsdy98hk4', 0, 1000000000000000000);

iotex-analytics only insert 1 and 2,so I think https://github.com/iotexproject/iotex-analytics/pull/78 is  ok
