### ISSUE TITLE
There's build and run error after 1471

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-core#1472]
After #1471 merged,there build and run error:

{"level":"fatal","ts":1567657156.73755,"caller":"itx/server.go:218","msg":"Failed to start server.","ioAddr":"io1vsw06fn53yjj2e3nqz786majd28cqmcl6392vj","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting blockchain: failed to init state tracker store: failed to init balance change tracker: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(epoch_number DECIMAL(65, 0) NOT NULL, block_height DECIMAL(65, 0) NOT NULL, act' at line 1","errorVerbose":"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(epoch_number DECIMAL(65, 0) NOT NULL, block_height DECIMAL(65, 0) NOT NULL, act' at line 1\nfailed to init balance change tracker\ngithub.com/iotexproject/iotex-core/state/tracker.InitStore\n\t/root/iotex-core/state/tracker/tracker.go:51\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Start\n\t/root/iotex-core/state/factory/statedb.go:111\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/root/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to init state tracker store\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Start\n\t/root/iotex-core/state/factory/statedb.go:112\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/root/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:228\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:128\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:217\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:129\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:217\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337"}

**Comment by lizhefeng** [comment]
@Frankonly Please take a look.

**Comment by lzxm160** [comment]
> @Frankonly Please take a look.

I am working on it
