### ISSUE TITLE
Query votes of a given candidate by height

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1514]
**What would you like to be added**:
Query votes of a given candidate by height

**Why is this needed**:
As mentioned in https://github.com/iotexproject/iotex-core/pull/1510, the current implementation of query votes by ethereum height in iotex-core is confusing to users. If we do want to have this functionality in iotex-core, we should support user to query it by iotex height in poll.

**Comment by lzxm160** [comment]
I think this api maybe is not necessary,I add it when it's needed
