### ISSUE TITLE
ioctl bc info default output is json

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1522]
### What version of iotex-core are you using (`ioctl version`)?

v0.8.3

### What operating system and processor architecture are you using?

Mac OS

### What did you do? If possible, provide a recipe for reproducing the error.

```
 zjshen@Zhijies-MacBook-Pro  ~/Projects/iotex-core   master ●  ioctl bc info
Blockchain Node: api.iotex.one:443
{
  "height": 1386599,
  "numActions": 1457347,
  "tps": 1,
  "epoch": {
    "num": 3852,
    "height": 1386361,
    "gravityChainStartHeight": 8651100
  },
  "tpsFloat": 0.1
}
```

### What did you expect to see?

Formatted console output

### What did you see instead?

Json output

**Comment by Frankonly** [comment]
This is not the standard json output, I use json as part of the output here.
