### ISSUE TITLE
Prevent exposing internal error message to users

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1525]
For example, when using cli to query an unconfirmed action, I got the bellow:

```
root@iotex-delegate-0:/go/apps/iotex-core# ioctl action hash e7fc240f3eb14b8745e5703594ecf2fbe88b3dbe0e2f49cd6f82cac2375067cf
Error: failed to get action e7fc240f3eb14b8745e5703594ecf2fbe88b3dbe0e2f49cd6f82cac2375067cf: key = 94ecf2fbe88b3dbe0e2f49cd6f82cac2375067cf doesn't exist: not exist in DB
```

Rather than return the internal error such as key not exist in DB, we should only raise user friendly error, e.g., action xxxx isn't found.

BTW, more than this particular APIs have the same problem.

**Comment by lzxm160** [comment]
This will be fixed when version is stable

**Comment by lzxm160** [comment]
not necessary
