### ISSUE TITLE
it sometimes get chain meta failed on test network

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-core#1530]
~~The following error may occur when using iotex-antenna send a write action to contract~~
```
5 NOT_FOUND: sql: Scan error on column index 0, name "MAX(height)": converting driver.Value type <nil> ("<nil>") to a int64: invalid syntax
```

**Comment by zjshen14** [comment]
@uu-z can you specify what contract and what action you send? And is it reproducible?

**Comment by uu-z** [comment]
@zjshen14  This problem may occur in any contract. I think it has something to do with the rate limit.

**Comment by uu-z** [comment]
@zjshen14   I just founded this error in `getChainMeta` action, do you have any ideas?

**Comment by raullenchai** [comment]
@lizhefeng pls take a look

**Comment by lizhefeng** [comment]
@uu-z Do you still have this problem?

**Comment by uu-z** [comment]
@lizhefeng  look like it has been fixed, thanks
