### ISSUE TITLE
There're a few errors when syncing testnet

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-core#1537]
Test commit b79fb5c
There're two errors,need to find out the reason

1、{"level":"error","ts":1570498796.4513602,"caller":"committee/committee.go:211","msg":"failed to catch up via network","ioAddr":"io14qrkr2svzunvles05r9n60n6gy7e6nfkkteyxl","networkAddr":"0.0.0.0:4689","height":7831200,"error":"failed to get record hashes: no such column: ids","errorVerbose":"no such column: ids\nfailed to get record hashes\ngithub.com/iotexproject/iotex-election/committee.(*recordTableOperator).Put\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/recordtableoperator.go:140\ngithub.com/iotexproject/iotex-election/committee.(*archive).PutPoll\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/pollarchive.go:178\ngithub.com/iotexproject/iotex-election/committee.(*committee).storeInBatch\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/committee.go:349\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start.func1\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/committee.go:210\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337"}
2、{"level":"error","ts":1570498800.4408448,"caller":"blocksync/buffer.go:86","msg":"Failed to commit the block.","ioAddr":"io14qrkr2svzunvles05r9n60n6gy7e6nfkkteyxl","networkAddr":"0.0.0.0:4689","recvHeight":1145701,"confirmedHeight":1145700,"source":"blockBuffer","error":"error when validating block 1145701: failed to validate action: height 0 is lower than start height 7825200","errorVerbose":"height 0 is lower than start height 7825200\ngithub.com/iotexproject/iotex-election/committee.(*committee).resultByHeight\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/committee.go:410\ngithub.com/iotexproject/iotex-election/committee.(*committee).ResultByHeight\n\t/root/gopath/pkg/mod/github.com/iotexproject/iotex-election@v0.2.5/committee/committee.go:404\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*governanceChainCommitteeProtocol).delegatesByGravityChainHeight\n\t/root/iotex-core/action/protocol/poll/protocol.go:243\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*governanceChainCommitteeProtocol).DelegatesByHeight\n\t/root/iotex-core/action/protocol/poll/protocol.go:288\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*stakingCommittee).DelegatesByHeight\n\t/root/iotex-core/action/protocol/poll/staking_committee.go:99\ngithub.com/iotexproject/iotex-core/action/protocol/poll.validate\n\t/root/iotex-core/action/protocol/poll/protocol.go:454\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*stakingCommittee).Validate\n\t/root/iotex-core/action/protocol/poll/staking_committee.go:95\ngithub.com/iotexproject/iotex-core/blockchain.(*validator).validateActions.func2\n\t/root/iotex-core/blockchain/blockvalidator.go:186\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to validate action\ngithub.com/iotexproject/iotex-core/blockchain.(*validator).validateActionsOnly\n\t/root/iotex-core/blockchain/blockvalidator.go:109\ngithub.com/iotexproject/iotex-core/blockchain.(*validator).Validate\n\t/root/iotex-core/blockchain/blockvalidator.go:67\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).validateBlock\n\t/root/iotex-core/blockchain/blockchain.go:960\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/iotex-core/blockchain/blockchain.go:584\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/iotex-core/blocksync/util.go:20\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/iotex-core/blocksync/buffer.go:82\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/iotex-core/blocksync/blocksync.go:133\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/iotex-core/chainservice/chainservice.go:290\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/iotex-core/dispatcher/dispatcher.go:218\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nerror when validating block 1145701\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).validateBlock\n\t/root/iotex-core/blockchain/blockchain.go:963\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/iotex-core/blockchain/blockchain.go:584\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/iotex-core/blocksync/util.go:20\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/iotex-core/blocksync/buffer.go:82\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/iotex-core/blocksync/blocksync.go:133\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/iotex-core/chainservice/chainservice.go:290\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/iotex-core/dispatcher/dispatcher.go:218\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337","syncHeight":1145701}

**Comment by raullenchai** [comment]
pls investigate

**Comment by lzxm160** [comment]
> pls investigate

sure

**Comment by lzxm160** [comment]
test again,it's already fixed after rebuild testnet
