### ISSUE TITLE
Provide users useful feedback if the action hasn’t been accepted

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1545]
@koseoyoung @puncsky pls help on this one

**Comment by zjshen14** [comment]
https://github.com/iotexproject/iotex-core/pull/1544

**Comment by koseoyoung** [comment]
I think this work is for back-end. On the other hand, for iotexscan.io when we send transaction, the error should be shown to users since currently we are showing just the transaction hash and don't let them know the error of sendAction api. (for the ioctl, it is returning from the api, so no need to change)

**Comment by koseoyoung** [comment]
@puncsky

**Comment by puncsky** [comment]
@koseoyoung as long as there is some way to differentiate errors, we can throw error accordingly.

**Comment by puncsky** [comment]
please elaborate on the API that we can integrate with

**Comment by koseoyoung** [comment]
In SendAction api, it's returning rpc error where code is 'internal' and message contains the error msg. Just like this 
```
&status.statusError{Code:13, Message:"reject invalid action: 89db806e64f5cee3057e55fc2ab17f773e6d60a2d958e87a13e337c1b3e9c795: error when validating transfer action: error when validating recipient's address EURYLJTDUUXSUKCJBZBXSYPJHPTGGCUPDUNTSEZTD: hrp  and address prefix io don't match: invalid index of 1", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
```
Do we need to classify and redefine the error code like this https://github.com/ethereum/EIPs/issues/136 ? 
And the API is
 rpc SendAction(SendActionRequest) returns (SendActionResponse) {}

**Comment by puncsky** [comment]
I think we still need error code instead of error message

**Comment by yutongp** [comment]
because
https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
`details` is an any type in protobuf, basically it is an empty interface,
so we can put anything we want in details as well as define format as we like to.

**Comment by yutongp** [comment]
for example: https://github.com/googleapis/googleapis/blob/c372c656aef153931708c80ac1a8186060841cdf/google/api/expr/v1alpha1/conformance_service.proto#L145
this `IssueDetails` is an error detail defined for this specific api

**Comment by koseoyoung** [comment]
> for example: https://github.com/googleapis/googleapis/blob/c372c656aef153931708c80ac1a8186060841cdf/google/api/expr/v1alpha1/conformance_service.proto#L145
> this `IssueDetails` is an error detail defined for this specific api

Thanks for your reference! 
I tried to use google.rpc.Status as the above example, but I think I need to clone the status.proto (unlike timestamp.proto), so I'm thinking about defining error code as enum, is it fine? 
```message SendActionResponse {
  enum ResultCode { 
    SUCCESS = 0;
    INVALID_ARGUMENT = 1;
    INVALID_BALANCE = 2;
    INSUFFICIENT_BALANCE_FOR_GAS = 3;
    INVALID_NONCE = 4;
    BLACKLISTED_ADDRESS = 5;
    INVALID_ACTPOOL = 6;
    INVALID_GAS_PRICE = 7; 
    INTERNAL_UNKNOWN = 8;
  }
  string actionHash = 1;
  ResultCode resultStatus = 2;
}
