### ISSUE TITLE
`ioctl node delegate` returns key not found

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1551]
In Simone's word, `I'm still seeing it constantly on blocks 1 -9 of each epoch. `

The vide clip showing the issue is attached.

[ioctl-node-delegate-error.mp4.zip](https://github.com/iotexproject/iotex-core/files/3731739/ioctl-node-delegate-error.mp4.zip)

**Comment by lzxm160** [comment]
Caused by electionCommittee.HeightByTime,later we need to check new version v0.9.0 if it still have this problem

**Comment by lzxm160** [comment]
v0.9.0 already fix this
