### ISSUE TITLE
block height stuck on is 1,292,941 

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1561]
```If we start a node from the genesis block using 0.8.3 or even 0.9.0 it gets stuck on the same block height every time. The block height it gets stuck on is 1,292,941  then it seems to get stuck in a loop```

**Comment by TezBaker** [comment]
Thanks for raising for me (Public Payments)

**Comment by yutongp** [comment]
if you are not using snapshot we provide but sync from 0 block, plz use docker image v0.9.2

**Comment by TezBaker** [comment]
That solved the issue on one node but not the other. I can blow it away and start again but will leave it for a few days incase you need any for more information. This is what I'm currently seeing in the logs:

Not enough lock endorsements
didn't receive the proposed block before timeout
Not enough proposal endorsements
Not enough lock endorsements
Start a new round
