### ISSUE TITLE
node bootstrap from state db Checkpoint instead of block 0

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1562]
Currently we only support start from our snapshots or start from very beginning.

one ability we may need to not sync from block 0 but start syncing from some checkpoint. which means we start with a state.db at height X, and the node directly asking it's peers for block X+1 and above to keep up to the latest change and doesn't request for block less and equal to X.

This is also the fundamental feature if we will Re-genesis in the future.

**Comment by lzxm160** [comment]
I think this will take two steps:
1. sync state to state.db,include account and trie node
2. modify code logic,implement sync data when only have state.db

**Comment by lzxm160** [comment]
Start to research today

**Comment by lzxm160** [comment]
After 1655 and 1652 ,I will restart this

**Comment by lzxm160** [comment]
research and test code

**Comment by lzxm160** [comment]
Branch 15621 is for this issue,now have the following error to fix:

{"level":"error","ts":1575593719.0967667,"caller":"blocksync/buffer.go:87","msg":"Failed to commit the block.","ioAddr":"io1wgalgkvdxqpmls8zhj6l8mwnjafj58n3xw5swf","networkAddr":"0.0.0.0:4689","recvHeight":720,"confirmedHeight":719,"source":"blockBuffer","error":"delta state digest doesn't match, expected = 0bdf20394f6b88c3e37b7a7babcb11824587d108d47de0a054b4f560e2ea4da9, actual = c4dbddc9e3053fe10a273eed24e59c796580cef820343bb55c3eb73acafd243b","errorVerbose":"delta state digest doesn't match, expected = 0bdf20394f6b88c3e37b7a7babcb11824587d108d47de0a054b4f560e2ea4da9, actual = c4dbddc9e3053fe10a273eed24e59c796580cef820343bb55c3eb73acafd243b\ngithub.com/iotexproject/iotex-core/blockchain/block.(*Block).VerifyDeltaStateDigest\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/block/block.go:95\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).validateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:783\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:491\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/util.go:20\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/buffer.go:83\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/blocksync.go:133\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/chainservice/chainservice.go:383\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:218\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1357","syncHeight":720}

**Comment by lzxm160** [comment]
https://github.com/iotexproject/iotex-core/tree/checkpoint,one way to implement this

**Comment by lzxm160** [comment]
After #1851,this will be restart to test and commit pr

**Comment by lzxm160** [comment]
we should fix #1864，and then based on #1864 fix #1863 and rebuild snapshot

**Comment by lzxm160** [comment]
Based on latest code，dont use splitdb，sync from height 1 is good for test

**Comment by lzxm160** [comment]
It's been assigned to someone else
