### ISSUE TITLE
Sampling the logs

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#1573]
When syncing up, many logs are printed. We should rate-limit them by sampling.

**Comment by raullenchai** [comment]
zerolog supports sampling - https://github.com/rs/zerolog/blob/master/sampler.go

**Comment by yutongp** [comment]
we don't use zerolog

**Comment by yutongp** [comment]
https://github.com/uber-go/zap/blob/a01e410a7526259f89e9c701465a2553bc201741/config.go#L35

zap also has sampling and our config support user to enable it. not convinced it should be enabled by default, but if one want to sampling log, they can enable it
