### ISSUE TITLE
linux versions in release are uploaded mistakenly

### ISSUE THREAD

**Issue by Rambin** [iotexproject/iotex-core#1586]
![图片](https://user-images.githubusercontent.com/9563884/67883418-0718e080-fb7f-11e9-9da6-c7fd185e6181.png)
![图片](https://user-images.githubusercontent.com/9563884/67883431-0b44fe00-fb7f-11e9-9eec-e7f50fa63318.png)
![图片](https://user-images.githubusercontent.com/9563884/67883435-0ed88500-fb7f-11e9-8e02-71333b4931e7.png)
File size and analysis from 7-zip shows that linux version of v0.9.1 and v0.9.2 are darwin version, leading to a "cannot execute binary file: Exec format error" running these files.

**Comment by yutongp** [comment]
Thank you for your report! We have fixed this issue. Sorry about the inconvenience.
