### ISSUE TITLE
one command script to upgrade node to current golden version

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1587]
currently to upgrade our node require 5 steps: https://github.com/iotexproject/iotex-bootstrap

user not only need to upgrade image, but also yaml config. sometime they forgot to upgrade yaml of upgrade to wrong version.

so we want to have a way to pin current desired build.
and just let user to run one command to
1. stop old docker
2. pull image
3. pull new config
4. there are two field in old config need to feed in new config (externalHost, producerPrivKey)
5. run new node docker

something like `io-upgrade old-config.yaml`

**Comment by FeirenK** [comment]
https://github.com/iotexproject/iotex-bootstrap/pull/76
sh/bash setup_iotex.sh  
input version,datadir
