### ISSUE TITLE
go1.13.4 cannot build?

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1597]
### What version of iotex-core are you using (`ioctl version`)?
latest

### What operating system and processor architecture are you using?
Linux

### What did you do? If possible, provide a recipe for reproducing the error.
customer build with go1.13.4, failed with message:
build github.com/iotexproject/iotex-core/ioctl: cannot load bufio: malformed module path "bufio": missing dot in first path element

### What did you expect to see?
build pass

### What did you see instead?
build fail

**Comment by dustinxie** [comment]
here's customer's go env:
i pointed out GOBIN="", he fixed later but still cannot build.
searched the error message, it seems related to go1.13.4  

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bnbprd/.cache/go-build"
GOENV="/home/bnbprd/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bnbprd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/server/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/server/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/server/wallet/iotex/iotex-core/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build478085927=/tmp/go-build -gno-record-gcc-switches"

**Comment by yutongp** [comment]
I believe this issue is the same as https://github.com/golang/go/issues/34184 which caused by incorrect goroot setup. nothing to do with our project.
I have updated my local go version to 1.13.4 and built our project without any issue.
