### ISSUE TITLE
version/height should not bound to features

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1600]
currently height/version is tied to some set of features.
for example cook is native staking, Dardanelles is 5s block interval. this highly bound feature with version which make it hard to decouple them to enable some feature in a version but not others or start a new chain with a subset of current supported features.

a preferred model should be:
``` yaml
cook:
  height: xxx
  enableFeatures: [A, B, C]
```
and in the code instead of
```go
if passedCook {
 do XYZ
}
```
have
```go
if xyzEnabled {
  do XYZ
}
```

**Comment by maswalker** [comment]
https://github.com/iotexproject/iotex-core/pull/2768
