### ISSUE TITLE
add CreateBlockchain() method

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1603]
at least 5 places in our test have similar code to create a blockchain according to config and protocols the chain needs to handle. better to have a CreateBlockchain() method to simplify these:

CreateBlockchain(inMem bool, cfg config.Config, protocol const []string) (blockchain.Blockchain, blockdao.BlockDAO, blockindex.Indexer, *protocol.Registry, error)

5 places in our test:
api_test.go 1661
blockchain_test.go 617, 775
execution/protocol_test.go 291, 475

there could be more places that can use this to improve

**Comment by lzxm160** [comment]
waiting for the refactor of blockchain and chainservice

**Comment by lzxm160** [comment]
not necessary，cannot find a better way
