### ISSUE TITLE
circle.ci fail with error "current state height 2 doesn't match working set version 0"

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1605]
### What version of iotex-core are you using (`ioctl version`)?
latest master

### What operating system and processor architecture are you using?
Linux

### What did you do? If possible, provide a recipe for reproducing the error.
This has sth to do with local_transfer_test.go, line 525: cfg.Genesis.BlockInterval = 500 * time.Millisecond

Reducing the interval even further like 100ms will help to repro the error
Increasing the interval to like 2s will pass the test (but test runs longer) 

### What did you expect to see?
circle ci pass

### What did you see instead?
circle ci failed with error "current state height 2 doesn't match working set version 0"

**Comment by raullenchai** [comment]
Is this still true? If so, pls work o it.

**Comment by raullenchai** [comment]
Too stale, close it
