### ISSUE TITLE
add UndelegatedBalance(address string) (string, error) into blockatlas

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1611]
To enable native staking for trustwallet, we need to implement the UndelegatedBalance(address string) (string, error) interface

Because the staked balance is actually transferred to the staking contract, so this balance is just the balance of the address returned by query from pharos API, for example, https://pharos.iotex.io/v1/accounts/io1e2nqsyt7fkpzs5x7zf2uk0jj72teu5n6aku3tr

**Comment by ququzone** [comment]
https://github.com/iotexproject/pharos/pull/7
https://github.com/trustwallet/blockatlas/pull/458

@dustinxie already add `UndelegatedBalance` api

**Comment by dustinxie** [comment]
thx Leo!
