### ISSUE TITLE
TipHeight and TipHash should not be stored in a separate db

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1617]
If we want to split chain db into multiple files ($start_height.db), the tip height and hash are now stored in a separate db. As a result, there is a potential data conflict in the db files because of multiple db writes. Ideally, the tip height and hash could be stored in the same db file as the block data.

Solution:
Each $start_height.db file will contain a pair of tip height and tip hash. In blockDao, we read the latest tip height and hash from the largest $start_height.db and store them in memory. In this way, we don't need to have multiple commits in one putBlock call.

**Comment by lzxm160** [comment]
According to #1421 ,only header,body ,footer and receipt maped to split db,tip height and tip hash both in the default db

**Comment by lzxm160** [comment]
As discussed offline,I'll add checking func to make sure chain.db and chain_xxxx.db have the same block height

**Comment by lzxm160** [comment]
As discussed offline,today I'll add height->hash,start and end height for every chainxx.db

**Comment by lzxm160** [comment]
As discussed offline,this needs to move block datas to chainxx.db totally,it's a big change and need a lot of tests

**Comment by lzxm160** [comment]
try to resume this

**Comment by lzxm160** [comment]
already done with latest code
