### ISSUE TITLE
Add a StatePruner to prune obsolete states

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1619]
#1604 explains the method we'll use to prune obsolete states in trie

Add a StatePruner as a standalone component (similar to IndexBuilder), it runs a regular job (by default 1000 blocks) that:

1. for account, call RangeIndex's Purge(current tip - retention)
2. for contract, scan the "prune" bucket and delete entries < current tip - retention

**Comment by lzxm160** [comment]
almost good,rangeindex need to merge with my version

**Comment by lzxm160** [comment]
switch to branch hs commit ee4f908 and test

**Comment by lzxm160** [comment]
no need this since archive data using trie
