### ISSUE TITLE
Unify API service client

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1658]
The following piece of code could be found in multiple places in ioctl:
https://github.com/iotexproject/iotex-core/blob/master/ioctl/cmd/account/account.go#L115-L120

Remove the duplicate code, and also make it possible to mock an APIServiceClient for unit test purpose.

**Comment by YoshiyukiSakura** [comment]
before coding:
i got 2 way for this,   
1. create APIServiceClient in advance with `Init()`   
2. add a `func GetAPIServiceClient()` in /ioctl/util(maybe somewhere else)   
please comment & let me know which way is better

**Comment by millken** [comment]
@CoderZhi no to find duplicate code，has been fixed?

**Comment by CoderZhi** [comment]
it has been fixed
