### ISSUE TITLE
Improve test coverage of config package

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1682]
Details of coverage can be found here: https://codecov.io/gh/iotexproject/iotex-core/tree/master/config

We need to add more unit test, especially for HeightUpgrade.

**Comment by CoderZhi** [comment]
https://github.com/iotexproject/iotex-core/pull/1707

**Comment by CoderZhi** [comment]
More tests needed for config.go

**Comment by RuneAkko** [comment]
I will take #1682

**Comment by RuneAkko** [comment]
#1736

**Comment by raullenchai** [comment]
make sure close it when it is done
