### ISSUE TITLE
Improve test coverage for state package

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1684]
Unit test is missing for state.go and account.go in 
https://github.com/iotexproject/iotex-core/tree/master/state

Unit test for candidate.go is not complete

**Comment by CoderZhi** [comment]
#1687

**Comment by CoderZhi** [comment]
More corner cases to cover

**Comment by RuneAkko** [comment]
Is this needed to improve more? I find the test cover of state package is already 83%  in the latest commit.

**Comment by raullenchai** [comment]
The remaining will be covered in https://github.com/iotexproject/iotex-core/issues/2231
