### ISSUE TITLE
Unit test for Envelope and SealedEnvelope

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1685]
Move envelope and sealed envelope into two separate files and add unit tests for them.

**Comment by RuneAkko** [comment]
I will take this issue:)

**Comment by RuneAkko** [comment]
I find this issue has been solved in #1713 yesterday......

**Comment by raullenchai** [comment]
@RuneAkko feel free to assign tasks to yourself if no one takes care of it; if you found it is solved, pls comment and close this task. thx
