### ISSUE TITLE
Unit test for action/protocol/rolldpos/epoch.go

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1686]
Add unit test for rolldpos protocol

**Comment by RuneAkko** [comment]
I think I have fininshed this one. Is there anything to be updated?

**Comment by raullenchai** [comment]
https://codecov.io/gh/iotexproject/iotex-core/src/master/action/protocol/rolldpos/epoch.go

@RuneAkko ProductivityByEpoch is not covered.

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/85102683-02f70d00-b1ba-11ea-94ae-f16d3e4e4c72.png)
