### ISSUE TITLE
panic when start syncing data from height 1

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-core#1703]
### What version of iotex-core are you using (`ioctl version`)?
master commit 906f304

### What operating system and processor architecture are you using?
ubuntu 16.04

### What did you do? If possible, provide a recipe for reproducing the error.

sync data from height 1

### What did you expect to see?
sync data normally

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xce6fa6]

goroutine 1 [running]:
go.etcd.io/bbolt.(*DB).beginTx(0x0, 0x4542e2, 0xc0006b4b80, 0x0)
	/root/gopath/pkg/mod/go.etcd.io/bbolt@v1.3.2/db.go:545 +0x26
go.etcd.io/bbolt.(*DB).Begin(0x0, 0x0, 0x0, 0x41b9f9, 0xc0006b4ba0)
	/root/gopath/pkg/mod/go.etcd.io/bbolt@v1.3.2/db.go:538 +0x6e
go.etcd.io/bbolt.(*DB).View(0x0, 0xc0005336c0, 0x0, 0x0)
	/root/gopath/pkg/mod/go.etcd.io/bbolt@v1.3.2/db.go:703 +0x3c
github.com/iotexproject/iotex-core/db.(*boltDB).Get(0xc0004e4840, 0x12e177d, 0x7, 0xc0006b4ba0, 0x14, 0x14, 0xd7d838, 0xc00053378c, 0xc0006b4b8c, 0x14, ...)
	/root/gopath/src/github.com/iotexproject/iotex-core/db/db_bolt.go:84 +0xd6
github.com/iotexproject/iotex-core/state/factory.(*stateDB).state(0xc0000af800, 0x471997ed66f7625c, 0xdc8b3e975536db77, 0xd8a1ed8c, 0x11f2980, 0xc000708860, 0x20, 0x20)
	/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/statedb.go:243 +0xaf
github.com/iotexproject/iotex-core/state/factory.(*stateDB).CandidatesByHeight(0xc0000af800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/statedb.go:210 +0x113
github.com/iotexproject/iotex-core/action/protocol/poll.(*stakingCommittee).CandidatesByHeight(0xc0003a0fc0, 0x0, 0xc0003a0fc0, 0x162fa00, 0xc0003a0fc0, 0x1, 0x0)
	/root/gopath/src/github.com/iotexproject/iotex-core/action/protocol/poll/staking_committee.go:215 +0x65
github.com/iotexproject/iotex-core/blockchain.(*blockchain).candidatesByHeight(0xc0000af100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:613 +0xa8
github.com/iotexproject/iotex-core/blockchain.(*blockchain).context(0xc0000af100, 0x1624d40, 0xc000546840, 0x1611e80, 0xc0006b4ac0, 0x0, 0x0, 0xed53613f0, 0x22a2cc0, 0x2, ...)
	/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:460 +0x50
github.com/iotexproject/iotex-core/blockchain.(*blockchain).Start(0xc0000af100, 0x1624d40, 0xc000546840, 0x0, 0x0)
	/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:366 +0x138
github.com/iotexproject/iotex-core/chainservice.(*ChainService).Start(0xc0003a10a0, 0x1624d40, 0xc000546840, 0x0, 0x0)
	/root/gopath/src/github.com/iotexproject/iotex-core/chainservice/chainservice.go:310 +0x60
github.com/iotexproject/iotex-core/server/itx.(*Server).Start(0xc0002d3c00, 0x1624d40, 0xc00003dcc0, 0xc0004fc140, 0x12)
	/root/gopath/src/github.com/iotexproject/iotex-core/server/itx/server.go:97 +0x13e
github.com/iotexproject/iotex-core/server/itx.StartServer(0x1624d40, 0xc00003dcc0, 0xc0002d3c00, 0xc0002f81c0, 0xc0004dd980, 0xc000442ed8, 0x7, 0x1251, 0x0, 0x0, ...)
	/root/gopath/src/github.com/iotexproject/iotex-core/server/itx/server.go:173 +0x5d
main.main()
	/root/gopath/src/github.com/iotexproject/iotex-core/server/main.go:101 +0x886

**Comment by lzxm160** [comment]
blockchain's context method should not contain candidatesByHeight,because candidatesByHeight need to read state from boltdb, but boltdb is not started at that time

**Comment by CoderZhi** [comment]
https://github.com/iotexproject/iotex-core/pull/1716
