### ISSUE TITLE
README.md points to a whitepaper that doesn't exist

### ISSUE THREAD

**Issue by awojnarek** [iotexproject/iotex-core#1719]
### What version of iotex-core are you using (`ioctl version`)?
n/a

### What operating system and processor architecture are you using?
n/a

### What did you do? If possible, provide a recipe for reproducing the error.
Clicked on the link in the readme.MD

### What did you expect to see?
The web page

### What did you see instead?
404:  http://iotex.io/academics

**Comment by yutongp** [comment]
thank you for reporting the issue. should be fixed now
