### ISSUE TITLE
update gitter to iotex community forum

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-core#1734]
**What would you like to be added**:
change gitter channel to 
https://community.iotex.io/c/research-development/protocol

**Why is this needed**:
forum have better threading. It is helpful for discussions.

**Comment by raullenchai** [comment]
Gitter is mentioned here https://github.com/iotexproject/iotex-core/blob/master/README.md

**Comment by raullenchai** [comment]
https://github.com/iotexproject/iotex-core/pull/1747 merged
