### ISSUE TITLE
Add auto generated code into codecov.yml

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1742]
HOW: https://docs.codecov.io/docs/ignoring-paths
WHAT: test/mock/*, consensus/scheme/rolldpos/endorsementpb, action/protocol/rewarding/rewardingpb, action/protocol/account/accountpb, and etc.

**Comment by RuneAkko** [comment]
I will take it at #1744

**Comment by RuneAkko** [comment]
> I will take it at #1744

It seems @applemin has done it.

**Comment by CoderZhi** [comment]
One left: https://codecov.io/gh/iotexproject/iotex-core/tree/4642ed7a54a920ee2c703c2ac95fd8a76313cdbf/tools/executiontester/blockchain
