### ISSUE TITLE
Data Racing

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1750]
==================
WARNING: DATA RACE
Write at 0x00c0001065e8 by goroutine 239:
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/internal/race/race.go:41 +0xee
  github.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).Stop()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:152 +0xfe
  github.com/iotexproject/iotex-core/server/itx.(*Server).Stop()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:114 +0x145
  github.com/iotexproject/iotex-core/e2etest.TestLocalTransfer.func2()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/e2etest/local_transfer_test.go:313 +0xab
  runtime.call64()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3a
  testing.(*T).FailNow()
      <autogenerated>:1 +0x43
  github.com/stretchr/testify/require.NoError()
      /Users/zhi/go/pkg/mod/github.com/stretchr/testify@v1.3.0/require/require.go:800 +0xef
  github.com/stretchr/testify/require.(*Assertions).NoError()
      /Users/zhi/go/pkg/mod/github.com/stretchr/testify@v1.3.0/require/require_forward.go:623 +0xcf
  github.com/iotexproject/iotex-core/e2etest.TestLocalTransfer()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/e2etest/local_transfer_test.go:321 +0xbad
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous read at 0x00c0001065e8 by goroutine 212:
  sync.(*WaitGroup).Add()
      /usr/local/go/src/internal/race/race.go:37 +0x18d
  github.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).Start()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:139 +0x15a
  github.com/iotexproject/iotex-core/server/itx.(*Server).Start()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:101 +0x2ae
  github.com/iotexproject/iotex-core/server/itx.StartServer()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:173 +0x6d

Goroutine 239 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:62 +0x223

Goroutine 212 (running) created at:
  github.com/iotexproject/iotex-core/e2etest.TestLocalTransfer()
      /Users/zhi/go/src/github.com/iotexproject/iotex-core/e2etest/local_transfer_test.go:310 +0x918
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

**Comment by raullenchai** [comment]
pls check if this is still the case @JonSnow47, if not, feel free to close it

**Comment by JonSnow47** [comment]
cmd: `go test -v -race e2etest/local_transfer_test.go`
now, no DATA RACE WARNING
