### ISSUE TITLE
Standalone mode cannot grant reward

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1759]
### What version of iotex-core are you using (`ioctl version`)?

0.10.0

### What did you do? If possible, provide a recipe for reproducing the error.

reward protocol which queries ProductivityByEpoch cannot return appropriate values in standalone mode

**Comment by raullenchai** [comment]
Basically, Standalone is one mode to run iotex blockchain with a single node, mostly for testing/demo purposes.

**Comment by huof6829** [comment]
Now it's ok. Run blockchain in standalone mode and query the node reward.  First check the rolldpos protocol is registered or not, and `ProductivityByEpoch` is not called yet.   The output:
<img width="882" alt="截屏2022-09-20 16 31 14" src="https://user-images.githubusercontent.com/9823472/191411760-997da822-5722-4fd1-8a45-ea4e494243e4.png">
