### ISSUE TITLE
Refactor Blockchain.Start

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1787]
1. protocols should be started first.
1.1 we can use bc.registry directly, instead of fetching it from protocol.GetBlockchainCtx
1.2 Move the whole section to line 295, before bc.lifecycle.OnStart
2. Assume that https://github.com/iotexproject/iotex-core/issues/1779 has been done
2.1 Add sf as an indexer of dao
2.2 Move function startExistingBlockchain into dao
2.2.1 Change PutBlock(block.Block) to PutBlock(context.Context, block.Block)
2.2.2 Add a PutBlock implementation in factory, which will call runActions and commit

**Comment by lzxm160** [comment]
After #1799 finished,this will start to do

**Comment by lzxm160** [comment]
resume this today

**Comment by lzxm160** [comment]
long time ago,the architecture is different now
