### ISSUE TITLE
add API of total supply for the native IOTX token 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-core#1790]
**What would you like to be added**:

a field in the chain meta on the total supply of the IOTX token

**Why is this needed**:

we already have it in the XRC 20 API so we need it as well in the native.

**Comment by nmhung1210** [comment]
Can we have update on this matter?

**Comment by lizhefeng** [comment]
@nmhung1210 We will have an analytics API for total balance of all accounts. In order to get total supply (total circulating IOTX), we need to add TotalBalance coming from the ReadState API inside the rewarding protocol.

**Comment by lizhefeng** [comment]
For analytics, please refer https://github.com/iotexproject/iotex-analytics/issues/173

**Comment by lizhefeng** [comment]
Total circulating balance = total balance of all the accounts + Total Balance in rewarding fund (total unclaimed balance + total available balance)

**Comment by raullenchai** [comment]
We have this in analytics now - https://github.com/iotexproject/iotex-analytics/issues/249
