### ISSUE TITLE
Membership service for consortium blockchain

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#1792]
Leverage iotex-election module to implement membership service for consortium blockchain. 

Instead of reading from Ether/infura, read from a SQL table (behind certain API endpoint) to pull the delegates list

1. define the SQL table schema for delegate list
2. define the API for read/write/update the table
3. start a web service to expose the API

**Comment by lzxm160** [comment]
research vote model first

**Comment by lzxm160** [comment]
CREATE TABLE IF NOT EXISTS `delegate_list`  (
  `delegate_id` decimal(65, 0) NOT NULL,
`delegate_name` varchar(255),
`delegate_nodeid` varchar(255),
 `group_id` decimal(65, 0) NOT NULL,
`group_name` varchar(255),
  `consensus_type` varchar(255) NOT NULL,
 `max_trans_num` decimal(65, 0),
 `gas_limit` decimal(65, 0) NOT NULL,
  UNIQUE INDEX `delegate_group_index`(`delegate_id`, `group_id`)
) 

define this table elementarily,need to research further
