### ISSUE TITLE
Run actions in parallel

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1813]
**What would you like to be added**:
In validation step, run actions in parallel.

**Why is this needed**:
Minimize validation time

**How to implement it**
Block producer prepares a DAG during block proposal, and sends it to endorsers together with the block. Endorsers run actions in parallel according to the DAG.

**Comment by raullenchai** [comment]
This one needs some discussion and design. A few ref:
- https://eprint.iacr.org/2019/835.pdf
- https://allquantor.at/blockchainbib/pdf/shrey2019dipetrans.pdf
- even sharding for specific sub-protocols
