### ISSUE TITLE
Unit test for save history feature

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1818]
Save history feature was introduced in https://github.com/iotexproject/iotex-core/commit/dab29156364ada6dad2bd90aff9fc91892396806, but it hasn't been fully tested.

Unit test or end-to-end test for this feature, and verify that we are able to access historical data via factory.State function.

Test plan:
0. Init a blockchain: account A has X IOTX, B has Y IOTX, get the current root hash RH of account trie in factory
1. Put a block with a transfer with 10 IOTX from A->B, get the current root hash NRH
2. Verify that the balance of A is X - 10 IOTX, and the balance of B is Y + 10 IOTX
3. Reset account trie's root hash to RH
4. Verify that the balance of A is X, the balance of B is Y
5. Reset account trie's root hash to NRH
6. Verify that the balance of A is X - 10, and the balance of B is Y + 10

Eventually, we will have the test be applied to https://github.com/iotexproject/iotex-core/pull/1726, which is a replacement implementation of https://github.com/iotexproject/iotex-core/commit/dab29156364ada6dad2bd90aff9fc91892396806. The PR1726 hasn't been merged because it is not fully tested (this is definitely not a valid reason, because https://github.com/iotexproject/iotex-core/commit/dab29156364ada6dad2bd90aff9fc91892396806 hasn't be fully tested either, and moreover it modified the statetx. @dustinxie )

**Comment by lzxm160** [comment]
need add unit test for account and contract seperately

**Comment by lzxm160** [comment]
https://github.com/iotexproject/iotex-core/commits/addtestforsavehistory,base on https://github.com/iotexproject/iotex-core/commit/dab29156364ada6dad2bd90aff9fc91892396806, add TestHistoryForAccount and TestHistoryForContract in blockchain_test.go

**Comment by lzxm160** [comment]
Before dab2915,account state use statetx without trie,now account state already change to use workingset with trie,need to rewrite test code for account
