### ISSUE TITLE
Vote for delegate could not less than 100 iotex

### ISSUE THREAD

**Issue by tohnee** [iotexproject/iotex-core#1822]
### What version of iotex-core are you using (`ioctl version`)?
https://member.iotex.io/

### What operating system and processor architecture are you using?

mac/chrome

### What did you do? If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/18139119/71763518-c2f7e280-2f17-11ea-9379-d68937ca3517.png)

![image](https://user-images.githubusercontent.com/18139119/71763529-e3c03800-2f17-11ea-8923-9f19dd7b01a8.png)

### What did you expect to see?

i have 38.92 iotx, i vote 20 iotx, according to hint "must be smaller or equal to 38.924845".vote should be success

### What did you see instead?
but vote failed

**Comment by yutongp** [comment]
the minimum token amount to vote is 100. @puncsky let's make some ui change to reflect the error more clear

**Comment by puncsky** [comment]
copied to web-bp

**Comment by raullenchai** [comment]
Verified it is fixed
