### ISSUE TITLE
ioctl send auth token

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1829]
If there is a `auth.jwt` file under user's ioctl config folder (example: `~/.config/ioctl/default/auth.jwt`),
ioctl put the contain of the file (should be a valid  encoded jwt string, you can also do a sanity check) in every grpc request sending to a iotex node's metadata with key `Authorization`. So `Authorization: jwt_content`
This is how to send request metadata as a grpc client: https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-metadata 

There is an example `auth.jwt` file, github can only upload `txt` format, please remove the `txt` when use it.
[auth.jwt.txt](https://github.com/iotexproject/iotex-core/files/4067292/auth.jwt.txt)

**Comment by RuneAkko** [comment]
#1856
