### ISSUE TITLE
error while loading shared libraries: libtblsmnt_ubuntu.so

### ISSUE THREAD

**Issue by pabloxorx** [iotexproject/iotex-core#183]
I m trying to install iotex-core on Ubuntu 16.04, I got an error on make test command:
`/tmp/go-build454528752/b001/keystore.test: error while loading shared libraries: libtblsmnt_ubuntu.so: cannot open shared object file: No such file or directory
FAIL	github.com/iotexproject/iotex-core/accounts/keystore	0.003s
/tmp/go-build454528752/b166/subchain.test: error while loading shared libraries: libtblsmnt_ubuntu.so: cannot open shared object file: No such file or directory
FAIL	github.com/iotexproject/iotex-core/action/subchain	0.005s
/tmp/go-build454528752/b171/actpool.test: error while loading shared libraries: libtblsmnt_ubuntu.so: cannot open shared object file: No such file or directory
FAIL	github.com/iotexproject/iotex-core/actpool	0.002s
/tmp/go-build454528752/b177/address.test: error while loading shared libraries: libtblsmnt_ubuntu.so: cannot open shared object file: No such file or directory
FAIL	github.com/iotexproject/iotex-core/address	0.001s
`
How can I solve it? Thanks

**Comment by zjshen14** [comment]
@lizhefeng can you take a look?

**Comment by lizhefeng** [comment]
@pabloxorx You need to set up this Env Path: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GOPATH/src/github.com/iotexproject/iotex-core/crypto/lib:$GOPATH/src/github.com/iotexproject/iotex-core/crypto/lib/blslib

Or simply run export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GOPATH/src/github.com/iotexproject/iotex-core/crypto/lib:$GOPATH/src/github.com/iotexproject/iotex-core/crypto/lib/blslib
before you run make test.

**Comment by pabloxorx** [comment]
@lizhefeng Thanks it fixed but got new error nearly of finish 

`# github.com/iotexproject/iotex-core/network
network/rpcserver.go:30:5: cannot use (*RPCServer)(nil) (type *RPCServer) as type lifecycle.StartStopper in assignment:
	*RPCServer does not implement lifecycle.StartStopper (wrong type for Start method)
		have Start("github.com/iotexproject/iotex-core/vendor/golang.org/x/net/context".Context) error
		want Start("context".Context) error
`

**Comment by lizhefeng** [comment]
@pabloxorx Did you make any code change? Could you please provide your GO version and the steps of how you encountered this problem?

**Comment by pabloxorx** [comment]
@lizhefeng  I passed RPC error but got an old error.

`/tmp/go-build401974060/b358/trie.test: error while loading shared libraries: libtblsmnt_ubuntu.so: cannot open shared object file: No such file or directory
FAIL	github.com/iotexproject/iotex-core/trie	0.000s
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 1
v****i@v****i-**-7**:~/go/src/github.com/iotexproject/iotex-core$ echo $LD_LIBRARY_PATH
:/home/****/go/src/github.com/iotexproject/iotex-core/crypto/lib:/home/****/go/src/github.com/iotexproject/iotex-core/crypto/lib/blslib:/home/****/go/src/github.com/iotexproject/iotex-core/crypto/lib:/home/****/go/src/github.com/iotexproject/iotex-core/crypto/lib/blslib:/home/*****/go/src/github.com/iotexproject/iotex-core/crypto/lib
v****i@v****i-**-7**:~/go/src/github.com/iotexproject/iotex-core$ 
`

**Comment by pabloxorx** [comment]
@pabloxorx  I passed RPC server it was going version problem after I run iotex core I got this error on: 14004 port. 

{"jsonrpc":"2.0","id":"","error":{"code":-32700,"message":"Unable to parse JSON: unexpected end of JSON input"}}

**Comment by pabloxorx** [comment]
> @pabloxorx I passed RPC server it was going version problem after I run iotex core I got this error on: 14004 port.
> 
> {"jsonrpc":"2.0","id":"","error":{"code":-32700,"message":"Unable to parse JSON: unexpected end of JSON input"}}

I m trying to solve it wholly a day, someone can help me to solve it? Thanks

**Comment by lizhefeng** [comment]
@pabloxorx Sorry for the late reply. Did you encounter this problem when you run make test? If yes, which test did you fail on?

**Comment by pabloxorx** [comment]
Its result of make test:

make test
go fmt ./...
go test -short ./...
ok  	github.com/iotexproject/iotex-core/accounts/keystore	0.050s
ok  	github.com/iotexproject/iotex-core/action	0.018s
ok  	github.com/iotexproject/iotex-core/action/subchain	0.017s
ok  	github.com/iotexproject/iotex-core/actpool	0.644s
ok  	github.com/iotexproject/iotex-core/address	(cached)
ok  	github.com/iotexproject/iotex-core/address/bech32	(cached)
ok  	github.com/iotexproject/iotex-core/beacon	(cached)
ok  	github.com/iotexproject/iotex-core/blockchain	6.600s
ok  	github.com/iotexproject/iotex-core/blocksync	0.608s
?   	github.com/iotexproject/iotex-core/chainservice	[no test files]
?   	github.com/iotexproject/iotex-core/cli/iotc	[no test files]
ok  	github.com/iotexproject/iotex-core/cli/iotc/cmd	0.049s
ok  	github.com/iotexproject/iotex-core/config	0.026s
?   	github.com/iotexproject/iotex-core/consensus	[no test files]
?   	github.com/iotexproject/iotex-core/consensus/scheme	[no test files]
ok  	github.com/iotexproject/iotex-core/consensus/scheme/rolldpos	27.639s
?   	github.com/iotexproject/iotex-core/consensus/sim	[no test files]
?   	github.com/iotexproject/iotex-core/consensus/sim/proto	[no test files]
ok  	github.com/iotexproject/iotex-core/crypto	(cached)
ok  	github.com/iotexproject/iotex-core/db	0.106s
ok  	github.com/iotexproject/iotex-core/db/rds	0.010s
ok  	github.com/iotexproject/iotex-core/dispatcher	0.046s
ok  	github.com/iotexproject/iotex-core/e2etest	12.535s
ok  	github.com/iotexproject/iotex-core/explorer	0.135s
?   	github.com/iotexproject/iotex-core/explorer/idl/explorer	[no test files]
ok  	github.com/iotexproject/iotex-core/indexservice	0.023s
ok  	github.com/iotexproject/iotex-core/iotxaddress	(cached)
?   	github.com/iotexproject/iotex-core/logger	[no test files]
ok  	github.com/iotexproject/iotex-core/network	2.560s
?   	github.com/iotexproject/iotex-core/network/node	[no test files]
?   	github.com/iotexproject/iotex-core/network/proto	[no test files]
ok  	github.com/iotexproject/iotex-core/pkg/counter	(cached)
?   	github.com/iotexproject/iotex-core/pkg/enc	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/errcode	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/hash	[no test files]
ok  	github.com/iotexproject/iotex-core/pkg/keypair	(cached)
ok  	github.com/iotexproject/iotex-core/pkg/lifecycle	(cached)
ok  	github.com/iotexproject/iotex-core/pkg/routine	(cached)
?   	github.com/iotexproject/iotex-core/pkg/util/byteutil	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/util/fileutil	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/version	[no test files]
?   	github.com/iotexproject/iotex-core/proto	[no test files]
?   	github.com/iotexproject/iotex-core/server	[no test files]
?   	github.com/iotexproject/iotex-core/server/itx	[no test files]
ok  	github.com/iotexproject/iotex-core/state	0.882s
?   	github.com/iotexproject/iotex-core/test/mock/mock_actpool	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_blockchain	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_blocksync	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_consensus	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_dispatcher	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_lifecycle	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_network	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_state	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_trie	[no test files]
ok  	github.com/iotexproject/iotex-core/test/testaddress	0.004s
ok  	github.com/iotexproject/iotex-core/testutil	0.015s
ok  	github.com/iotexproject/iotex-core/tools/actioninjector	5.372s
?   	github.com/iotexproject/iotex-core/tools/addrgen	[no test files]
?   	github.com/iotexproject/iotex-core/tools/addrgen/internal/cmd	[no test files]
?   	github.com/iotexproject/iotex-core/tools/minicluster	[no test files]
?   	github.com/iotexproject/iotex-core/tools/util	[no test files]
ok  	github.com/iotexproject/iotex-core/trie	3.194s

**Comment by lizhefeng** [comment]
@pabloxorx  From the output you showed, It seems that all tests passed. Do you still have the error?

**Comment by pabloxorx** [comment]
> @pabloxorx From the output you showed, It seems that all tests passed. Do you still have the error?

Yes its still error, I tried second day already to solve it. Its coming from this vendor: https://github.com/coopernurse/barrister-go Line 1289

**Comment by pabloxorx** [comment]
@lizhefeng  Any update about it?

**Comment by lizhefeng** [comment]
@pabloxorx Please join this gitter chat room
https://gitter.im/iotex-dev-community/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Let's talk through this chanel. Thanks.

**Comment by nkbai** [comment]
```makefile
.PHONY: run
run:
	$(ECHO_V)rm -rf ./e2etest/*chain*.db
	$(GOBUILD) -o ./bin/$(BUILD_TARGET_SERVER) -v ./$(BUILD_TARGET_SERVER)
	LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):$(PWD)/crypto/lib:$(PWD)/crypto/lib/blslib ./bin/$(BUILD_TARGET_SERVER) -config-path=e2etest/config_local_delegate.yaml
```

this works.
