### ISSUE TITLE
Unit test failure in ioctl/cmd/account

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#1935]
### What version of iotex-core are you using (`ioctl version`)?
master branch

### What operating system and processor architecture are you using?
Circle CI

### What did you do? If possible, provide a recipe for reproducing the error.
Submit PR

### What did you expect to see?
No Error

### What did you see instead?
--- FAIL: TestAccount (1.83s)
    account_test.go:68: 
        	Error Trace:	account_test.go:68
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestAccount
FAIL

**Comment by CoderZhi** [comment]
potential root cause: https://github.com/iotexproject/iotex-core/blob/master/ioctl/cmd/account/account_test.go#L37

Wallet is default path is not a temporary directory/file. If two ci tests run at the same time, one may overwrite the other.

**Comment by Frankonly** [comment]
> potential root cause: https://github.com/iotexproject/iotex-core/blob/master/ioctl/cmd/account/account_test.go#L37
> 
> Wallet is default path is not a temporary directory/file. If two ci tests run at the same time, one may overwrite the other.

We use temperary test path in this case. Two ci would use different path.

**Comment by CoderZhi** [comment]
#1944
