### ISSUE TITLE
Rename "Available Reward" and "Total Reward" to something meaningful

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2012]
➜  ~ ioctl node reward
Available Reward: 4931421.782464681337667499 IOTX   Total Reward: 33762976.939048088470363785 IOTX

Available Reward == Rewards in the pool that has not been **issued to** anyone
Total Reward == Rewards in the pool that has been **issued to** a delegate but are not claimed yet
Claimed Reward (which is not shown here) == Rewards **claimed and collected** by a delegate (thus not in the pool any more)

We should rename to make things clear.

**Comment by lizhefeng** [comment]
@RuneAkko Can you also help change the relevant namings in the "ReadState": https://github.com/iotexproject/iotex-core/blob/master/action/protocol/rewarding/protocol.go#L196

**Comment by RuneAkko** [comment]
#2067
