### ISSUE TITLE
restore removed tests

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2089]
10 test cases are removed in latest PR
https://github.com/iotexproject/iotex-core/commit/fd020e003c3f871bcc4963b787e235418a7fdf74#diff-9024ef3522c8b63c6f5ae9734ffb5a14L500

that is because the check of candidate conflict has been moved from validateCandidateRegister() to handleCandidateRegister()

1. add them back into TestProtocol_HandleCandidateRegister() to restore these tests
2. do the same for 3 removed tests in TestProtocol_ValidateCandidateUpdate(), add them back to TestProtocol_HandleCandidateUpdate()

You don't need to worry about other removals, I think those are also checked in handler before this PR

**Comment by lzxm160** [comment]
restart this today
