### ISSUE TITLE
Revise the error handlings in handlers.go

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2141]
In protocols, in some case where we should return a failure receipt, we throw error instead. For example, https://github.com/iotexproject/iotex-core/blob/master/action/protocol/staking/handlers.go#L91-L93 and etc.

**What would you like to be added**:
Review all the error handling, and return receipt unless system failure

**Comment by dustinxie** [comment]
fixed in https://github.com/iotexproject/iotex-core/commit/062c50f09935cfcdd2c73cc82546ca72bd6470ae
