### ISSUE TITLE
Clean up some static functions in staking protocol

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2142]
**What would you like to be added**:
We have some static functions like getTotalBucketCount (not used anywhere), getBucket, updateBucket, putBucket, delBucket, getAllBuckets, getBucketsWithIndices, putBucketAndIndex, which could all be moved in to CandidateStateManager. Also, function settleAction could be moved into CandidateStateManager as well.

**Why is this needed**:
Because of these functions, we have a mixture usage of CandidateStateManager and StateManager throughout this package. By moving them into CandidateStateManager, we don't need to expose StateManager APIs, and CandidateStateManager could be the only interface interacting with this protocol internally.

**Comment by LuckyPigeon** [comment]
I can take this, but needs to create separate PRs.
