### ISSUE TITLE
[ioctl] add delegate's Name in 'ioctl node delegate' output

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2169]
**What would you like to be added**:
add a column "Name" between Address and Rank

**Why is this needed**:
user can easily see the name, and use ioctl stake2 to vote to the delegate he wants

**Comment by dustinxie** [comment]
<img width="735" alt="Screen Shot 2020-05-12 at 8 42 59 PM" src="https://user-images.githubusercontent.com/12551272/81769167-c553e580-9491-11ea-8443-1eca0f329558.png">

**Comment by dustinxie** [comment]
also, now only first 24 are listed

for nsV2, let's list all registered candidates, but put a separate marker between 36 and 37

io1m8rge0h4xvmfzkc4yup766slcvn5cwymqeenpe     36      active   3     2289494
--------------------
io1qendhfjmpmug6ywde0590lakvxp3ph869ehlyp     37      active   0     1219594

**Comment by lzxm160** [comment]
done
