### ISSUE TITLE
[ioctl] config set nsv2height

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2177]
**What would you like to be added**:
1. ioctl config set nsv2height 3123456
2. remove ioctl.config.FairbankHeight, use the value from this
3. use config.Default.Genesis.FairbankBlockHeight as its default value

**Why is this needed**:
ioctl.config.FairbankHeight can only read from default value (which is for mainnet), as a result, the new feature to display delegate's name doesn't work correctly on testnet

**Comment by lzxm160** [comment]
done
