### ISSUE TITLE
Failed to input password/secret key to ioctl on Windows

### ISSUE THREAD

**Issue by Frankonly** [iotexproject/iotex-core#2191]
After updating my golang to `go version go1.14.3 windows/amd64`, new build ioctl fails to get secret input by `ReadSecretFromStdin`.

**Comment by millken** [comment]
i tested it and found no problems (win10+golang 1.14.12+cmd/powershell)，can you explain your env?

**Comment by raullenchai** [comment]
Feel free to close it if it already works @millken thanks
