### ISSUE TITLE
delta state digest doesn't match

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-core#2204]
### What version of iotex-core are you using (`ioctl version`)?
testnet version e7a5c7f

### What operating system and processor architecture are you using?
ubuntu go version go1.13.5
with latest testnet config:
https://raw.githubusercontent.com/iotexproject/iotex-bootstrap/v1.0.0/config_testnet.yaml
https://raw.githubusercontent.com/iotexproject/iotex-bootstrap/v1.0.0/genesis_testnet.yaml

### What did you do? If possible, provide a recipe for reproducing the error.
sync data with disable ArchiveMode,and then restart with the following config:
**enableTrielessStateDB: false
enableArchiveMode: true**

### What did you expect to see?
sync data without error

### What did you see instead?

{"level":"error","ts":1590753014.8032622,"caller":"blocksync/buffer.go:84","msg":"Failed to commit the block.","ioAddr":"io1c0cczzsaxew6ynuzfjhqlet8eun46tm4gm3ujl","networkAddr":"0.0.0.0:4689","recvHeight":41,"confirmedHeight":40,"source":"blockBuffer","error":"failed to validate block with workingset in factory: failed to verify delta state digest: delta state digest doesn't match, expected = 910b91dfcb170f11feee6bfd3982a6040586c9329fbc302517444cea627ee867, actual = e56f5953f6742e53831f85090b1e9c7478522f0d577fe35acd35c9f11a3b602d","errorVerbose":"delta state digest doesn't match, expected = 910b91dfcb170f11feee6bfd3982a6040586c9329fbc302517444cea627ee867, actual = e56f5953f6742e53831f85090b1e9c7478522f0d577fe35acd35c9f11a3b602d\ngithub.com/iotexproject/iotex-core/blockchain/block.(*Block).VerifyDeltaStateDigest\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/block/block.go:92\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/workingset.go:459\ngithub.com/iotexproject/iotex-core/state/factory.(*factory).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/factory.go:427\ngithub.com/iotexproject/iotex-core/blockchain/block.(*validator).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/block/validator.go:45\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:344\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/util.go:19\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/buffer.go:80\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/blocksync.go:138\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/chainservice/chainservice.go:492\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:220\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1357\nfailed to verify delta state digest\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/workingset.go:460\ngithub.com/iotexproject/iotex-core/state/factory.(*factory).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/factory.go:427\ngithub.com/iotexproject/iotex-core/blockchain/block.(*validator).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/block/validator.go:45\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:344\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/util.go:19\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/buffer.go:80\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/blocksync.go:138\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/chainservice/chainservice.go:492\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:220\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1357\nfailed to validate block with workingset in factory\ngithub.com/iotexproject/iotex-core/state/factory.(*factory).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/state/factory/factory.go:428\ngithub.com/iotexproject/iotex-core/blockchain/block.(*validator).Validate\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/block/validator.go:45\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:344\ngithub.com/iotexproject/iotex-core/blocksync.commitBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/util.go:19\ngithub.com/iotexproject/iotex-core/blocksync.(*blockBuffer).Flush\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/buffer.go:80\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/blocksync/blocksync.go:138\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/root/gopath/src/github.com/iotexproject/iotex-core/chainservice/chainservice.go:492\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:220\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).newsHandler\n\t/root/gopath/src/github.com/iotexproject/iotex-core/dispatcher/dispatcher.go:182\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1357","syncHeight":41}

**Comment by koseoyoung** [comment]
@lzxm160 What is the purpose of this testing? Not sure whether we support changing to the archive mode in the middle. In mainnet or with other images, was it able to change the archive mode ?

**Comment by lzxm160** [comment]
> @lzxm160 What is the purpose of this testing? Not sure whether we support changing to the archive mode in the middle. In mainnet or with other images, was it able to change the archive mode ?

I think mainnet or testnet both does not support this changing,if you think it's not a issue,I just close it

**Comment by koseoyoung** [comment]
In order to change to the archive mode in the middle, we should delete the trie.db and restart. You can give it a try this way.

**Comment by koseoyoung** [comment]
@lzxm160 have you tested changing the mode after delete the trie.db ? If it works well, pls close this issue!

**Comment by lzxm160** [comment]
> @lzxm160 have you tested changing the mode after delete the trie.db ? If it works well, pls close this issue!

I'll try with v1.0.0,thanks for the reminder

**Comment by lzxm160** [comment]
I tested again with v1.0.0,delete the trie.db and restart archive mode,it works
