### ISSUE TITLE
Small/big blocks issue

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2207]
![Screen Shot 2020-06-01 at 12 37 26 PM](https://user-images.githubusercontent.com/989846/83447059-a8616100-a404-11ea-82bf-4d2ec97de7b3.png)

While migrating, we saw this strange pattern that txs are aggregated into "big" blocks but not "small" blocks, we need to understand why (perhaps something with action pool/picker). 

A good first step is to repro this one in nightly with injector.

**Comment by yutongp** [comment]
i think this is due to the inject pattern we have. inject action then verify action on chain.
![9401591040872_ pic_hd](https://user-images.githubusercontent.com/915849/83448069-443f9c80-a406-11ea-9a2b-6492715e1815.jpg)
if you check this page, there is no such an issue
