### ISSUE TITLE
[ioctl] use -a to display all delegates

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2208]
**What would you like to be added**:
currently, `ioctl node delegate` displays all delegates, but delegates after first 36 are not sorted
change it to:
1. `ioctl node delegate` still displays top 36 delegates, same as before
2. `ioctl node delegate -a` displays all delegates, and make delegates after first 36 sorted by votes

**Why is this needed**:
better usability

**Comment by lzxm160** [comment]
done
