### ISSUE TITLE
[ioctl] ioctl bc bucketlist should display proper info for empty result

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-core#2210]
### What version of iotex-core are you using (`ioctl version`)?
ioctl v1.0.0

### What did you do? If possible, provide a recipe for reproducing the error.
ioctl bc bucketlist io1632k0ktw7w0zya6a2x7mw23dp82dkua03w9nsk

### What did you expect to see?
Expected to see the bucket list voted from "io1632k0ktw7w0zya6a2x7mw23dp82dkua03w9nsk", but saw "Blockchain Node: api.iotex.one:443" instead.

**Comment by raullenchai** [comment]
```
ioctl bc bucketlist io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
Blockchain Node: api.mainnet.iotex.one:443
{
index: 4455
owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
candidate: io1qvjw8g9rwy6evkksf2mevtr3c2un93e9xw87zc
stakedAmount: 400011 IOTX
stakedDuration: 14 days
autoStake: true
createTime: 2020-06-01T19:03:35Z
stakeStartTime: 2020-06-01T19:03:35Z
unstakeStartTime: none
}
{
index: 4979
owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
candidate: io1gvymyt07p5rz74rk8cdf4mr55cm05vnk4kxx2q
stakedAmount: 505 IOTX
stakedDuration: 68 days
autoStake: false
createTime: 2020-06-03T12:26:45Z
stakeStartTime: 2020-06-03T12:28:15Z
unstakeStartTime: none
}
{
index: 4981
owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
candidate: io14hkfx5uxksx0n5elv5eydvfrnj5xntl86r3s7s
stakedAmount: 400 IOTX
stakedDuration: 3 days
autoStake: false
createTime: 2020-06-03T17:32:30Z
stakeStartTime: 2020-06-03T17:35:35Z
unstakeStartTime: none
}
```

**Comment by raullenchai** [comment]
Just remove ```Blockchain Node: api.mainnet.iotex.one:443``` should be fine, e.g.,

```
➜  ~ ioctl bc bucketlist io1632k0ktw7w0zya6a2x7mw23dp82dkua03w9nsk
```

**Comment by raullenchai** [comment]
In addition, can print out the json blobs prettier.

**Comment by koseoyoung** [comment]
I added ```Blockchain Node: api.mainnet.iotex.one:443 ``` to be shown on bc bucketlist and bcbucket because it's one of the bc cmds just as bcblock and bcinfo. Is removing totally this line better? I removed this line and show error message when it's empty in #2211.

**Comment by raullenchai** [comment]
> I added `Blockchain Node: api.mainnet.iotex.one:443 ` to be shown on bc bucketlist and bcbucket because it's one of the bc cmds just as bcblock and bcinfo. Is removing totally this line better? I removed this line and show error message when it's empty in #2211.

Should be fine

**Comment by raullenchai** [comment]
> ```
> ioctl bc bucketlist io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
> Blockchain Node: api.mainnet.iotex.one:443
> {
> index: 4455
> owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
> candidate: io1qvjw8g9rwy6evkksf2mevtr3c2un93e9xw87zc
> stakedAmount: 400011 IOTX
> stakedDuration: 14 days
> autoStake: true
> createTime: 2020-06-01T19:03:35Z
> stakeStartTime: 2020-06-01T19:03:35Z
> unstakeStartTime: none
> }
> {
> index: 4979
> owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
> candidate: io1gvymyt07p5rz74rk8cdf4mr55cm05vnk4kxx2q
> stakedAmount: 505 IOTX
> stakedDuration: 68 days
> autoStake: false
> createTime: 2020-06-03T12:26:45Z
> stakeStartTime: 2020-06-03T12:28:15Z
> unstakeStartTime: none
> }
> {
> index: 4981
> owner: io1juhkwk0vf8dw9kqyh4pknzs23rt4hywm6zrmne
> candidate: io14hkfx5uxksx0n5elv5eydvfrnj5xntl86r3s7s
> stakedAmount: 400 IOTX
> stakedDuration: 3 days
> autoStake: false
> createTime: 2020-06-03T17:32:30Z
> stakeStartTime: 2020-06-03T17:35:35Z
> unstakeStartTime: none
> }
> ```

@koseoyoung can u make this one looks prettier?

**Comment by koseoyoung** [comment]
@raullenchai Can you explain more about how to change the output? Are you saying such as indentation?

**Comment by koseoyoung** [comment]
> > I added `Blockchain Node: api.mainnet.iotex.one:443 ` to be shown on bc bucketlist and bcbucket because it's one of the bc cmds just as bcblock and bcinfo. Is removing totally this line better? I removed this line and show error message when it's empty in #2211.
> 
> Should remove "Blockchain Node: api.mainnet.iotex.one:443" even if the bucket list is non-empty.

Ok!
