### ISSUE TITLE
Implementation of 'Click to Deploy' node

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2215]
Design and implementation of workflows for provisioning of pre-synced iotex-core image on GCP marketplace, updated daily

An example, using Bitcoin:
https://console.cloud.google.
com/marketplace/details/koinfitpublish/bitcoin-node?
q=bitcoin&id=6b9ad2d6-a4d9-4174-a630-50fd82b130fb

**Comment by raullenchai** [comment]
Can have a separate image for Pantheon

**Comment by yutongp** [comment]
not sure if we need update it daily. should just publish the current released version.

Pantheon contains multiple components cannot be put in one single image. I think it is ok to run all components on a single machine for trial. But there is no reason to run all production pantheon components on one node, and should be highly discouraged.
