### ISSUE TITLE
Wrong "active" status reported by ioctl

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2260]
### What version of iotex-core are you using (`ioctl version`)?
packageVersion:"v1.0.0" packageCommitID:"e7a5c7f779687fbb6d9f69871ff827133e1a0b52" gitStatus:"clean" goVersion:"go version go1.13.5 linux/amd64" buildTime:"2020-05-14-UTC/23:13:16" 

### What operating system and processor architecture are you using?
Linux Ubuntu 20.04 LTS x86_64

## What did you do? If possible, provide a recipe for reproducing the error.
The "_active_" state returned by: 
`ioctl node delegate`
seems to be wrong.

Taking **iotexlab** delegate as an example, here are some epochs for which the _active_ status as returned by `ioctl` is wrong (`ioctl` says "_active_", but the node was not selected in that epoch):
```
ioctl node delegate -e 10518 
ioctl node delegate -e 10513
ioctl node delegate -e 10509
ioctl node delegate -e 10506
etc...
```
This also happens for all other nodes (you will notice many nodes in "active" state, with 0 blocks produced, yet not probated — because they were not actually selected I suppose)

**Comment by lzxm160** [comment]
Thanks for your tests,it's my fault,I'll fix this with a new pr

**Comment by lzxm160** [comment]
done
