### ISSUE TITLE
ioctl "contract invoke function" cmd needs to use antenna-go for arg encoding 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2268]
When using ```ioctl contract invoke function``` cmd which uses abi and arguments, we have to use antenna-go module as injector(https://github.com/iotexproject/iotex-core/blob/master/tools/actioninjector.v2/internal/cmd/inject.go#L280). Antenna-go has internal argument encoding function inside. Therefore otherwise, just passing raw arguments (uint64, ioAddr) into abi.Pack() has incompatible issue.

e.g., currently having this error when executing cmd. 
```
 ./bin/ioctl contract invoke function io10jus78sk0fpgyy36f07fvfg45c654mrzg480es ./test.json "transfer" --with-arguments "io120Du9ra0nffdle04jx2g5gccn6gq8qd4fy03l4" 10
Error: failed to pack given arguments: failed to unmarshal arguments: invalid character 'i' looking for beginning of value

```

**Comment by koseoyoung** [comment]
https://github.com/iotexproject/iotex-antenna-go/blob/master/iotex/caller_contract.go#L218

**Comment by Frankonly** [comment]
> When using `ioctl contract invoke function` cmd which uses abi and arguments, we have to use antenna-go module as injector(https://github.com/iotexproject/iotex-core/blob/master/tools/actioninjector.v2/internal/cmd/inject.go#L280). Antenna-go has internal argument encoding function inside. Therefore otherwise, just passing raw arguments (uint64, ioAddr) into abi.Pack() has incompatible issue.
> 
> e.g., currently having this error when executing cmd.
> 
> ```
>  ./bin/ioctl contract invoke function io10jus78sk0fpgyy36f07fvfg45c654mrzg480es ./test.json "transfer" --with-arguments "io120Du9ra0nffdle04jx2g5gccn6gq8qd4fy03l4" 10
> Error: failed to pack given arguments: failed to unmarshal arguments: invalid character 'i' looking for beginning of value
> ```

The format of arguments should be JSON. e.g. '{"addr":"io120Du9ra0nffdle04jx2g5gccn6gq8qd4fy03l4"}

**Comment by koseoyoung** [comment]
@Frankonly I see, cool thx!
