### ISSUE TITLE
`ioctl bc block` returns all actions with `--verbose` flag

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2273]
```
➜  ioctl bc block 2683926

Blockchain Node: api.mainnet.iotex.one:443
{
  "hash": "95d72ee8e96fb5615723b5655d0edb16e6cb5eff621b9cf8c7ddbb1b0ddd7410",
  "height": 2683926,
  "timestamp": {
    "seconds": 1578584030
  },
  "numActions": 1,
  "producerAddress": "io1tfke5nfwryte6nultpmqefadgm0dsahm2gm63k",
  "transferAmount": "0",
  "txRoot": "130f2b6d134f0e33bb00e38f2185ea6f95eafd77b1f5bb4f89afe1cd3f80447f",
  "receiptRoot": "dc017175570ffa21682814160a979f944141861641d11f24905dd6b296d93c28",
  "deltaStateDigest": "6faaeceed19f53378f3230767d49620696c599522f950750df5f7ac5921ed72c",
  "logsBloom": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
```

```
➜  ioctl bc block 2683926 --verbose
```
returns block info + all actions within this block.

**Comment by raullenchai** [comment]
```
➜  ~ ioctl bc block 5928695 --verbose
Blockchain Node: api.mainnet.iotex.one:443
{
  "hash": "2867406f8c363192427dc69b7befeb9667da0cab5712f1ba331a4c5d6e3e4ac1",
  "height": 5928695,
  "timestamp": {
    "seconds": 1594874485
  },
  "numActions": 2,
  "producerAddress": "io1tfke5nfwryte6nultpmqefadgm0dsahm2gm63k",
  "transferAmount": "0",
  "txRoot": "f1773162df6937cd06ae0f149516abdf58dad55a272cbdb4dd911cc4876735b4",
  "receiptRoot": "562a37687ff939a5c41d86f72d6a63221920db4e62dead2e828707c747f665a8",
  "deltaStateDigest": "f197019cffca50db8aec70fa7f23f524ca9893214a7f689db836e6f105d97635",
  "logsBloom": "00000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
[
  {
    "version": 1,
    "nonce": 3,
    "gasLimit": 10000000,
    "gasPrice": "1000000000000",
    "senderPubKey": "BM5q/SM1Wm2hZdCTezR8/oVK4LfJZBgSyq8CXXLD13sJYEn81P5wuEzoBGCnCsGO2NKSlyhMtYL+RXaXgAdDo8s=",
    "signature": "NBnCcIyV8Qq+wlMWKu1KmFt6T8EqfSuPC9hZq0dFAUB4NlTNw1anM3OdzUmLJ5ipuvAsDfxsFYX5iyQqORwn7AA="
  },
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BPVi6oAOEMThGnf28eVutePn0DzjdDIG2wtIWJ63aPMJuFxsbi1MmJJ1bJViIV8D2bfQJyHFKwK7IHdKC6m4Z1Q=",
    "signature": "MNGux0SdrmPRicWYCUElLnMCd3ngv2BHlTJz7ud8JM57jwpbIFxNppjldy40XXTs3f4dJ7VIEBMdphC06rCYUQA="
  },
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BGr/GopwuDaLLfnl2Njjr4yB8pCQzVwlpsUcEKQU5keka3aFK3V5AYcMPTjz4N1MJ8LQPbmqNnYFUMvrYRU+UO0=",
    "signature": "U9YtLrtaF/90+ODMdQCkOmxQkfGR5FN04BN4Kn6+SH0WPdydJg9Eb57JUnR/95xd7txdfy1E4DzeTfIjFcgYLgA="
  }
]
```

**Comment by raullenchai** [comment]
Pls also get txhash, type and so on (like https://iotexscan.io/action/d8c4da37cb55afc5f64400737c190053fa854f7bcd46c5f14c28d21b3c92033d) to make it useful @RuneAkko

**Comment by RuneAkko** [comment]
> Pls also get txhash, type and so on (like https://iotexscan.io/action/d8c4da37cb55afc5f64400737c190053fa854f7bcd46c5f14c28d21b3c92033d) to make it useful @RuneAkko

ok

**Comment by RuneAkko** [comment]
`Blockchain Node: api.testnet.iotex.one:443
{
  "hash": "8b186b30e08e0375178fcae7441e58e30508bbe78621eebd0acf3a6d5dc6c876",
  "height": 2683926,
  "timestamp": {
    "seconds": 1585692025
  },
  "numActions": 2,
  "producerAddress": "io1s3z2pr47u47p69zn7phshgenckw6tr70tex80k",
  "transferAmount": "0",
  "txRoot": "a0c057c14e09568e4ac1af2dd5cf0aea439f66d752827b9a1808d17981d92c9e",
  "receiptRoot": "ebfaac27bd5ff01b62e7d58ca20ab63f399b7cbb03d1d8435ce12d5d5e6e562d",
  "deltaStateDigest": "7afc764bf18d9ce79daf0e92ca2819eeadd93be14184886d155bbea431881a1c",
  "logsBloom": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
[
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BMIsSNDdSCPaiJRPt6PYf+ZmD57oBJ8/Rz1BEvF66uU98LLhEEpFCh8YJH8f4IiszSKDyeGJTeipbYoRh0bdL0M=",
    "signature": "Res+soQs+u5gBwSaYCeIMcspnoe+Odm5Db2lrQE4aKsgSm311HGwJV2m6mhGT3LJzPJPYoiCdb6zw5a3vcPXFQE=",
    "status": 1,
    "blkHeight": 2683926,
    "actHash": "ktV22/BOZG5dgd6VY9tEffmWNOnBqRbpRnr/FPv+RXM=",
    "contractAddress": "io1ze4hg0pvrftuj0pw90p7z6wj3wae7mdrwws6d5"
  },
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BMIsSNDdSCPaiJRPt6PYf+ZmD57oBJ8/Rz1BEvF66uU98LLhEEpFCh8YJH8f4IiszSKDyeGJTeipbYoRh0bdL0M=",
    "signature": "WDvRzy/IkN58NzmLIGBzP+aB+uxJhQdE8aLubVgmvlk7/QRLYhjDt+VAL3qiMvQ1dpqKX29E7KOXZJF/KOjL2AE=",
    "status": 1,
    "blkHeight": 2683926,
    "actHash": "ktV22/BOZG5dgd6VY9tEffmWNOnBqRbpRnr/FPv+RXM=",
    "contractAddress": "io1ze4hg0pvrftuj0pw90p7z6wj3wae7mdrwws6d5"
  },
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BA+N3dWx+McwjK1lkU9aAf/C0RLwm4MW6D/kXqWHjDkeQsXkOICBll7COLVlebOxACo3fJmgmYs9tTXzsuZ8fLg=",
    "signature": "ITXJAfNLuRqw8BQrfaIw5FZOkNLi4iGm7FXVkVVfg4gONi0+vGhHzkFRTRGxBblXmRPBnbeOlpgcRaJUJdUbqgA=",
    "status": 1,
    "blkHeight": 2683927,
    "actHash": "1PqjhD03BFfBGcu1BtvfUAykmxzk/+5Iy98xxNHT/tI=",
    "contractAddress": "io154mvzs09vkgn0hw6gg3ayzw5w39jzp47f8py9v",
    "logs": [
      {
        "contractAddress": "io154mvzs09vkgn0hw6gg3ayzw5w39jzp47f8py9v",
        "data": "EilpbzFzZTcyZnJzNWtuMGo2Z2gwZzNmazJ1c25ndTQ4c2gyd2p0NHFncRoTODAwMDAwMDAwMDAwMDAwMDAwMA==",
        "blkHeight": 2683927,
        "actHash": "1PqjhD03BFfBGcu1BtvfUAykmxzk/+5Iy98xxNHT/tI="
      }
    ]
  },
  {
    "version": 1,
    "gasPrice": "0",
    "senderPubKey": "BA+N3dWx+McwjK1lkU9aAf/C0RLwm4MW6D/kXqWHjDkeQsXkOICBll7COLVlebOxACo3fJmgmYs9tTXzsuZ8fLg=",
    "signature": "o/pL63JmnKgs5hQv3p8+VJJPcaiyQNZpx3Z2VQl2ej1XNO4SRM8FAz7Ksd7x+G7DvB2lNLujrFRjwpvLyV0M/wE=",
    "status": 1,
    "blkHeight": 2683927,
    "actHash": "1PqjhD03BFfBGcu1BtvfUAykmxzk/+5Iy98xxNHT/tI=",
    "contractAddress": "io154mvzs09vkgn0hw6gg3ayzw5w39jzp47f8py9v",
    "logs": [
      {
        "contractAddress": "io154mvzs09vkgn0hw6gg3ayzw5w39jzp47f8py9v",
        "data": "EilpbzFzZTcyZnJzNWtuMGo2Z2gwZzNmazJ1c25ndTQ4c2gyd2p0NHFncRoTODAwMDAwMDAwMDAwMDAwMDAwMA==",
        "blkHeight": 2683927,
        "actHash": "1PqjhD03BFfBGcu1BtvfUAykmxzk/+5Iy98xxNHT/tI="
      }
    ]
  }
]`
