### ISSUE TITLE
Remove `gravityChainAPIs` from config

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2284]
No longer needed since the chain is completely detached from Infura/Ethereum after mainnet GA.

@yutongp pls route.

**Comment by dustinxie** [comment]
prob still need to keep it
if remove from config, existing config.yaml would fail to marshal since the field 'gravityChainAPIs' is missing
unless we notify all delegates to modify their local config.yaml

**Comment by dustinxie** [comment]
could mark as deprecated, like https://github.com/iotexproject/iotex-core/blob/master/config/config.go#L246-L247

**Comment by yutongp** [comment]
we cannot deprecated it for backward compatibility

**Comment by raullenchai** [comment]
ok
