### ISSUE TITLE
Release a newer stable version of ioctl

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2299]
<img width="1140" alt="Screen Shot 2020-07-15 at 9 58 20 PM" src="https://user-images.githubusercontent.com/989846/87628672-56d81180-c6e6-11ea-9cda-67d012bf4ef9.png">

The most recent stable one was built in May, we shall release a recent one.

**Comment by raullenchai** [comment]
@Madongming

**Comment by dustinxie** [comment]
@yutongp  released v1.1.0 https://github.com/iotexproject/iotex-core/releases/tag/v1.1.0
as a result, run the ioctl installation script will pull the latest
