### ISSUE TITLE
Deprecate Poll Sub-protocol 

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2302]
We can kill this subprotocol, remove all deadcode, since staking/voting is now in nsv2 subprotocol

**Comment by koseoyoung** [comment]
Removing those deprecated poll sub-protocol(governance, nsv1) won't cause compatibility issues? I thought we are still using those dead code while syncing from 0 height (even though we have poll.db)

**Comment by raullenchai** [comment]
Got it
