### ISSUE TITLE
Submit ioctl to  homebrew

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2325]
```
1. identify a stable version with all latest features
2. follow https://docs.brew.sh/Adding-Software-to-Homebrew
3. keep your figure crossed
```

**Comment by raullenchai** [comment]
Can explore Debian/Ubuntu as well but should be harder.

**Comment by RuneAkko** [comment]
submit ioctl to homebrew with my own [tap.](https://github.com/RuneAkko/homebrew-ioctl)
if this solution is ok, we can create a new req as our tap.
Working on Debian/Ubuntu now...

**Comment by raullenchai** [comment]
> submit ioctl to homebrew with my own [tap.](https://github.com/RuneAkko/homebrew-ioctl)
> if this solution is ok, we can create a new rep as our tap.
> Working on Debian/Ubuntu now...

Sounds good

**Comment by raullenchai** [comment]
For now, there is no version control which we do want, including the latest nightly build of ioctl  @RuneAkko @Madongming 

```➜  webthings brew info ioctl
iotexproject/ioctl/ioctl: stable 1.1.1
ioctl is a command line interface for interacting with the IoTeX blockchain.
https://docs.iotex.io/developer/get-started/ioctl-install.html
/usr/local/Cellar/ioctl/1.1.1 (5 files, 24.7MB)
  Built from source on 2020-08-26 at 09:24:28
From: https://github.com/iotexproject/homebrew-ioctl/blob/HEAD/ioctl.rb
License: Apache-2.0
==> Dependencies
Required: golang ✔, make ✔
➜  webthings brew search ioctl
==> Formulae
iotexproject/ioctl/ioctl ✔                                                istioctl
```
