### ISSUE TITLE
[ioctl] add 'ioctl bc bucket count/max' to show total number of buckets and max bucket index

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2353]
**What would you like to be added**:
1. ioctl bc bucket max --> the max bucket index
2. ioctl bc bucket count  --> total number of active buckets (this will be smaller than max, due to withdrawn buckets)

**Why is this needed**:
better usability/visibility for staking

**Comment by dustinxie** [comment]
for max: call func getTotalBucketCount(sr protocol.StateReader) (uint64, error)

for count: refer to func getTotalStakedAmount(ctx context.Context, csr CandidateStateReader) (*big.Int, error)
1. total.count is what you need
2. add a new method ActiveBucketsCount() to csr

**Comment by JonSnow47** [comment]
How to calculate the number of active buckets?
```go
func (c *candSR) ActiveBucketsCount() uint64 {
	// TODO: return c.view.bucketPool.Count() - withdrawnBucketsCount
}
```

**Comment by JonSnow47** [comment]
> How to calculate the number of active buckets?
> 
> ```go
> func (c *candSR) ActiveBucketsCount() uint64 {
> 	// TODO: return c.view.bucketPool.Count() - withdrawnBucketsCount
> }
> ```

@dustinxie

**Comment by dustinxie** [comment]
return c.view.bucketPool.Count()

that is the active count
