### ISSUE TITLE
Provide default accounts when running in STANDALONE mode

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2380]
**What would you like to be added**:
When running the node in STANDALONE mode, provide a set of pre-generated accounts with some amount of IOTX 

**Why is this needed**:
STANDALONE mode is convenient for developers to easily simulate a full testnet locally on their, pc to be used as a development endpoint. Having at least one (or better a few) default accounts with a IOTX balance is required to test transactions.

**Comment by raullenchai** [comment]
IMO this is possible via configuration -- @dustinxie pls confirm

**Comment by dustinxie** [comment]
i happen to be working on an issue using standalone mode, will have a PR for this soon

@simonerom  can you pls update docs about standalone mode after PR merged
