### ISSUE TITLE
report sync status through blockchain meta

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#2386]
something like: https://www.rosetta-api.org/docs/models/SyncStatus.html
we can say if blocksync target hight is larger than currently chain tip height, chain is in a syncing up or catching up mode, and we can return this information through blockchain meta endpoint

**Comment by raullenchai** [comment]
chain meta API - https://github.com/iotexproject/iotex-core/blob/master/api/api.go#L253
