### ISSUE TITLE
Archive mode API testing for data validity

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2393]
In order to test archive mode, I disable API indexer(disable gateway) and already tested candidate/probation list by using ReadState API. 

- [ ] With archive mode back-up trie.db, we need to test various data validity by querying API. (e.g., balance of an account on some specific height, or nonce on some specific height, or staking result and etc)

- [ ] Since disabling gateway, when I tried last time, some of the APIs don't work, if necessary, we might need to fix this to test other data in archive mode. @yutongp @CoderZhi We might need to enable archive mode to support all APIs?

```
./bin/ioctl node probationlist --insecure
Warn: Language en is not supported, English instead.

Error: failed to get chain meta: action index not supported
```

**Comment by lzxm160** [comment]
tested GetAccount api with archive mode syncing from height 1,need to test GetAccount api with back-up trie.db for those enable archive mode in the middle

**Comment by lzxm160** [comment]
The height of archive mode is 1269585 now,need to finish sync and also test with rosetta-cli

**Comment by lzxm160** [comment]
The height of archive mode synced height is 1701108 now,need to change api to support io0000000000000000000000rewardingprotocol and io000000000000000000000000stakingprotocol address and test with rosetta-cli again

**Comment by lzxm160** [comment]
now rosetta checked height is 2955463

**Comment by lzxm160** [comment]
The synced height of archive mode is 5542541 now

**Comment by lzxm160** [comment]
need to know how to get archive mode's tip height,most of the time that's different from bc's tip height

**Comment by lzxm160** [comment]
stuck in the Greenland height,need to fix "delta state digest doesn't match" error and https://github.com/iotexproject/iotex-core/issues/2440

**Comment by raullenchai** [comment]
No intention to further pursuit of archive mode
