### ISSUE TITLE
Upgrade to 1.1.0 ioctl on Linux 18.4 desktop no longer works

### ISSUE THREAD

**Issue by TezBaker** [iotexproject/iotex-core#2397]
### What version of iotex-core are you using (`ioctl version`)?
1.1.0

### What operating system and processor architecture are you using?
Ubuntu 18.04 Desktop edition

### What did you do? If possible, provide a recipe for reproducing the error.
Update ioctl using "ioctl update" and I now get the error
 /usr/local/bin/ioctl: No such file or directory
Changing permissions and reinstalling from curl does not help.

### What did you expect to see?
To be able to run the command

### What did you see instead?
 /usr/local/bin/ioctl: No such file or directory

**Comment by raullenchai** [comment]
```

$ curl https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli.sh | sh
ARCH = amd64
OS = linux
Fetching https://github.com/iotexproject/iotex-core/releases/latest..
Fetching https://github.com/iotexproject/iotex-core/releases/tag/v1.1.0..
Fetching https://github.com/iotexproject/iotex-core/releases/download/v1.1.0/ioctl-linux-amd64..
Setting executable permissions.
Moving executable to /usr/local/bin/ioctl

$ ioctl
-bash: /usr/local/bin/ioctl: No such file or directory

$ /usr/local/bin/ioctl
-bash: /usr/local/bin/ioctl: No such file or directory
```

**Comment by raullenchai** [comment]
```
sudo apt update
sudo apt install musl-dev
```
should fix it. but need to understand why musl is needed here - @RuneAkko @Madongming

**Comment by TezBaker** [comment]
Great that worked for us
