### ISSUE TITLE
Getting Language Error when running ioctl

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2399]
### What version of iotex-core are you using (`ioctl version`)?
```
Client:
packageVersion:"v1.1.0" packageCommitID:"f7cbd4fa362b68d84f48f446707914d4b5566c20" gitStatus:"dirty" goVersion:"go version go1.14.5 darwin/amd64" buildTime:"2020-08-10-PDT/11:06:11" 

api.iotex.one:443:
packageVersion:"v0.8.0-597-ga1d6568b" packageCommitID:"a1d6568bca79f38b9a3f6f4c22627326080ff168" gitStatus:"dirty" goVersion:"go version go1.14.6 linux/amd64" buildTime:"2020-08-12-UTC/22:40:19" 
```

### What operating system and processor architecture are you using?
macOS Catalina 10.15.6 x64

### What did you do? If possible, provide a recipe for reproducing the error.
run `ioctl command` (any command)

### What did you expect to see?
The normal command output

### What did you see instead?
The command works, but II see this warning on top of each output:
```
Warn: Language en is not supported, English instead.
```
![image](https://user-images.githubusercontent.com/11096047/90516663-9cb04b80-e164-11ea-9369-6cbd22cc6d17.png)

**Comment by Frankonly** [comment]
@simonerom The fix will be submitted a little bit later. A manual way to solve it is to run `ioctl config set language english`

**Comment by raullenchai** [comment]
![Screen Shot 2020-08-19 at 5 40 59 PM](https://user-images.githubusercontent.com/989846/90703644-26364b00-e243-11ea-992f-bf1161aed049.png)

Verified using the latest build
