### ISSUE TITLE
ioctl binary v1.1.0 not running (wrong arch?)

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2403]
### What version of iotex-core are you using (`ioctl version`)?
```
Client:
packageVersion:"v1.0.0" packageCommitID:"e7a5c7f779687fbb6d9f69871ff827133e1a0b52" gitStatus:"clean" goVersion:"go version go1.13.5 linux/amd64" buildTime:"2020-05-14-UTC/23:13:16" 

api.iotex.one:80:
packageVersion:"v0.8.0-597-ga1d6568b" packageCommitID:"a1d6568bca79f38b9a3f6f4c22627326080ff168" gitStatus:"dirty" goVersion:"go version go1.14.6 linux/amd64" buildTime:"2020-08-12-UTC/22:40:19"
```

### What operating system and processor architecture are you using?
Ubuntu 18.04.2 LTS x86_64

### What did you do? If possible, provide a recipe for reproducing the error.
```
» curl https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli.sh | sh

» ioctl
```
### What did you expect to see?
The usual ioctl output

### What did you see instead?
```
» ioctl
zsh: command not found: ioctl
````
Notice that the installation was successful:
```
» ll /usr/local/bin
-rwx--x--x 1 sromano sromano 24M Aug 20 01:09 ioctl
```

Same happens if I grab the binary from github with wget.

Instead if I try installing the "unstable" release, it complains requiring GLIBC 2.28, while latest supported for Ubuntu 18.04 is 2.27

Grabbing the executable v1.0.0 from GitHub with wget works well

**Comment by raullenchai** [comment]
@Madongming
