### ISSUE TITLE
ioctl -s flag no longer working when using multi send tool https://member.iotex.io/tools/multisend-iotex

### ISSUE THREAD

**Issue by TezBaker** [iotexproject/iotex-core#2405]
### What version of iotex-core are you using (`ioctl version`)?
First time running this on the new version

packageVersion:"v1.1.0" packageCommitID:"f7cbd4fa362b68d84f48f446707914d4b5566c20" gitStatus:"dirty" goVersion:"go version go1.14.6 linux/amd64" buildTime:"2020-08-10-UTC/18:01:23" 

### What operating system and processor architecture are you using?
Ubuntu 18.04

### What did you do? If possible, provide a recipe for reproducing the error.
Paying my delegates using the output automatically generated from the multi send tool. 

 ioctl action invoke io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu 143767.369101148179552 -s io1yftf6xuar26lsaher0qa73d0zc3csm884hjwvh -l 10000000 -p 1   <data here>

### What did you expect to see?
All accounts to be paid 

### What did you see instead?
Error: unknown shorthand flag: 's' in -s
Usage:
  ioctl action invoke (ALIAS|CONTRACT_ADDRESS) [AMOUNT_IOTX] -b BYTE_CODE [-s SIGNER] [-n NONCE] [-l GAS_LIMIT] [-p GAS_PRICE] [-P PASSWORD] [-y] [flags]

**Comment by Frankonly** [comment]
Sorry for the outdated command. `ioctl action invoke` cmd has been deprecated and we will update that page soon. You can try new command
```
ioctl contract invoke bytecode (CONTRACT_ADDRESS|ALIAS) PACKED_ARGUMENTS [AMOUNT_IOTX]
```

For your case, the command might be:
```
ioctl contract invoke bytecode io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu PACKED_ARGUMENTS 143767.369101148179552  -l 1000000 -p 1 
```
The `PACKED_ARGUMENTS` can be replaced as the `-b` part from the Distribute page.

**Comment by raullenchai** [comment]
Filed https://github.com/iotexproject/web-native-staking-v2/issues/279 to follow for the frontend

**Comment by TezBaker** [comment]
This didn't work for us, signed the transaction, received the hash but it never made it to the block chain and no errors. We ran the following:


ioctl contract invoke bytecode io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu 02c4bc4700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000b400000000000000000000000000000000000000000000000000000000000001620000000000000000000000000000000000000000000000000000000000000005600000000000000000000000001b0f8054b3ff625e65d194018b036bbc7748517000000000000000000000000081f24782f5f4a3153a374f9eeac6de472f270ca0000000000000000000000000d4612ed5abb67cf6b3b3c4b65fcee77632bda3e00000000000000000000000011064abeb6109da33c9cc928b746c7860979a2fb000000000000000000000000113e656501a4071140fe030a2d9ae6e85aab43e800000000000000000000000013a1ee4866b51cff8a6bdf733a8aac107adaa35800000000000000000000000014d5d1e8840a58df560e46e7168d4f58a851e54c00000000000000000000000016ef2d8d4e780fea1da1bd88073041e4dca2cdb000000000000000000000000019aa6581c1b3b10c2a7884ca53a85a85f93f5aea00000000000000000000000019b8018a3a8898e5c40b6adde528a061f616ea6e000000000000000000000000124d35a0d1ef59317f3502681fc0580df1e2aa350000000000000000000000002249b0afb6af0c2da29d46a647144ee6e894f70000000000000000000000000022569d1b9d1ab5f876f91bc1df45af1623886ce7000000000000000000000000246ede5d569546bc8987c41449418e9e0af14516000000000000000000000000247f7e7b7b123f1e7fe490c544e8a3b5b2eab81c000000000000000000000000251d8082bb1c223f315d0a15b393711361c3986a0000000000000000000000002a87e5f2e22c0c31edd269be48d73ee6b2b240be0000000000000000000000002ab33f6b6d4230caad56930fb1c3a01f910c05aa0000000000000000000000002afd55faeb99411212abc12ede7611f2e28ed2f7000000000000000000000000303d0e1ec982df5d681f7c5c0d323619fdfb8cf70000000000000000000000003343944ba5367291c0241a09bf66dd96f76af404000000000000000000000000340c16903e60eed46c9beca9a6ba21846aa0f56400000000000000000000000034dc72f8b7a6189a3ea022c24eae595b5fcc9c3d00000000000000000000000040377b2d76473c495a0ac508f0f139c85a4473550000000000000000000000004663c1c1bd8eb215e980f82288dad3695434f1ca000000000000000000000000474d89d49ccc5e10355665e01866ae3e79b5b6370000000000000000000000004abf512316412e84b6cfc29a987a5055ffca4bc20000000000000000000000004b02d1ee2b6b61e90bd6372db228cbbdfe996d7d0000000000000000000000004fd10cc0cd952b53fbaacd11c7da9733289b3f1d000000000000000000000000527914eea52faa1d46949888672c7962f36d40fc000000000000000000000000542a28941f8e38fa268595681f7810c57ad9d62d000000000000000000000000574a458cec15c1103fbac5f0d306e2ea98bd2e2f00000000000000000000000059e8e22083c6e5e66d22fc139cf6edec4d511c5b0000000000000000000000005ea7e703c27911e9e4e758f143b14c215a65573b0000000000000000000000006149a51a0ab0ca12786fe3af59e80c8d6e4d12470000000000000000000000006599ea3731351200e73ebb9c35a949584efcacb60000000000000000000000006600d5d2dfa8fe8a3dccb9354e8bd70689135c190000000000000000000000006d8106b66e0f17fe2621bb2bce9d3bc471db9796000000000000000000000000730944bdd880688e3c0f18e5897f31eaa8bdcfa8000000000000000000000000787512b575324b84aa9ac2c5ccef510a3323abc20000000000000000000000007a17a6a77ae72d0ff84630e5fd27c9e9894031990000000000000000000000007c2894cc6a17f0bb30fccf02a4ac19952483f2fe0000000000000000000000008385a591f4543d801cfe592ed55d64ce1c10204200000000000000000000000083ff49624c699b6202313f8a5858b8b661131ae9000000000000000000000000859a15b35d4acde52ab09b459fcfef3f2dfd4ff600000000000000000000000085d0139f984c06047b5be818bf42c47ae3243c9f00000000000000000000000086b699add439d44cf20ad9cff05b64b117794f3800000000000000000000000088945b2f9d26f846292651827b24a80568a06d8b0000000000000000000000008ab22ee0f82475047db1378a18a6464d2ee951800000000000000000000000008ed25dc85c582da07e5e078598d08f59fb5fa9e50000000000000000000000008ed6010ba577f715690a4398856abb4f50e682fb0000000000000000000000008ef7079590d1c4ca12859a665f5af3612fb36f6700000000000000000000000091f6b3c3e5479683d66c7383490599d0b039705b0000000000000000000000009677eafa6b30d1a47369c4869a30018fd2bc22f700000000000000000000000098f90d9908481d3d471a43e96fe9312aae85106d00000000000000000000000099644d1a79b8ff659b183090fcd6bd69b73f445c00000000000000000000000099faca24acec9e484d2a2d5882120f6f42d332780000000000000000000000009afbcd8840cdad077fbabe03f937de873076a3c3000000000000000000000000a0585ef9a7a50a8e8e71d5a708178e305cb0b554000000000000000000000000a0fc691973dcf5c9b242a6aeb2a159384bc7bfb6000000000000000000000000a16c5ada1c7fce82752dce06be9ebcc6c0dab5a6000000000000000000000000a3c43d3aaf39c4f30daaf7341ede4a53480d164c000000000000000000000000a5eddcd1925dbe6e36baddcdbedc2cf328f7a672000000000000000000000000a64ddf693ebbc79725c961343d9d36c5734b8d04000000000000000000000000a85bd84a642dbbd46c1c7d2c71c915c4d1f7fac4000000000000000000000000aa40e52900550f5c189de73360c76633b2d6ede2000000000000000000000000ab92fe34d9e4c12fbdc1a6276e277cdca6c380b9000000000000000000000000b26fce9c7edab6c29466d518ff47acf1753cd247000000000000000000000000b39c00f0ad385812d9053337541dd6eab58e29af000000000000000000000000b3d75f98250c09675b9e7115e27ac111a7abc330000000000000000000000000be5183fc1f7f514e5c8aa3aabdf4b759fc78cacd000000000000000000000000bcf4cee5c36a1130210cc66f79dc9988eeed2831000000000000000000000000c26fb8637c4a6690aec561f6da48ba734cfa9a1c000000000000000000000000c6b50ac543e5337a0047576b860810a05874dcd5000000000000000000000000cbff8ccd108e59a74e7dada0b031924cd71f87ad000000000000000000000000cd796250e882e95c39b6cacfc3ba703c8bd96785000000000000000000000000d7279bdebbe469e69d3973f2323092a9f81372be000000000000000000000000d7d9033bc326dd5fc4a4cba8f2bb5770608b1787000000000000000000000000d8bd70daf91ddb37ebea0514852ffd0190a409a7000000000000000000000000d9bf62e03a272a8c07f4b23dcff308e9e34fcb09000000000000000000000000dc30c374387cfc746c7b8ce03fb1feb7e54cfa3a000000000000000000000000dcb042b2f9e6c0b2de4619c65eb7a1046192134a000000000000000000000000eee5f4d232d0df4454f2f1807a39b815da2545e2000000000000000000000000f354e4dde312e3ed2cd4c99fbd93ac07a756ca7c000000000000000000000000f5cf5fab51a2a1e3df725ac8c0cd1a77765522e3000000000000000000000000f7a679f0a08b2e0d86b307423b434915d2cc8e040000000000000000000000000000000000000000000000000000000000000056000000000000000000000000000000000000000000000000024d0bc019ae4898000000000000000000000000000000000000000000000000087bbc97f67cd5700000000000000000000000000000000000000000000000025c9d469b28e4ba000000000000000000000000000000000000000000000000007ba9cab53bfdff300000000000000000000000000000000000000000000000000293e145b28ac8380000000000000000000000000000000000000000000000031e8536657aa8f4a000000000000000000000000000000000000000000000000020a49c3ece69d7f000000000000000000000000000000000000000000000000e9c9d74d6f06492c00000000000000000000000000000000000000000000000ae26a738304ddf7c8000000000000000000000000000000000000000000000000183ae4234bb8bcf800000000000000000000000000000000000000000000001148a807f105023e88000000000000000000000000000000000000000000000014a7f29fe462707b380000000000000000000000000000000000000000000000072b30498cb2fa5b78000000000000000000000000000000000000000000000000c82f556e882f72c400000000000000000000000000000000000000000000000001d40bf49cd8b04f0000000000000000000000000000000000000000000000000ca2ef15b10d8e0e00000000000000000000000000000000000000000000003dee307211b801e0300000000000000000000000000000000000000000000000000027927e4e7998d0000000000000000000000000000000000000000000000000003404219a316872000000000000000000000000000000000000000000000000251d75c8758f5c8200000000000000000000000000000000000000000000000034470cee7c4e4204000000000000000000000000000000000000000000000000ee53887c0931341800000000000000000000000000000000000000000000000001734dc1694c5f8500000000000000000000000000000000000000000000000e7d24652a1d18e1e00000000000000000000000000000000000000000000000000c07865f3e72bad2000000000000000000000000000000000000000000000000131cfdf5a25ffd460000000000000000000000000000000000000000000000003a312088a3ea4d8800000000000000000000000000000000000000000000000018d0f750f5fd675a0000000000000000000000000000000000000000000000084afbc991b082ae1000000000000000000000000000000000000000000000000000e3ea0832b44c96000000000000000000000000000000000000000000000000039a22a9fd582949000000000000000000000000000000000000000000000000093540d98802fad6000000000000000000000000000000000000000000000000765226c65d08ad0000000000000000000000000000000000000000000000000001f3a218a46ecc6b0000000000000000000000000000000000000000000000001f75774e144d12640000000000000000000000000000000000000000000000000287172b1b7a9adb00000000000000000000000000000000000000000000000b3283d97fd18838800000000000000000000000000000000000000000000000001488da59c3a4ef5e000000000000000000000000000000000000000000000002231516a9ba7c57e000000000000000000000000000000000000000000000000000fbf7d9973068610000000000000000000000000000000000000000000000001d1e896b6b537a6e00000000000000000000000000000000000000000000000000e28047c628d4aa0000000000000000000000000000000000000000000000024dd8d766a57a24dc00000000000000000000000000000000000000000000000067ca04443f90daf80000000000000000000000000000000000000000000000002a1c11a999dd8b100000000000000000000000000000000000000000000000029de6550c73a497180000000000000000000000000000000000000000000000007286697ab4c5053000000000000000000000000000000000000000000000000b102a996ca77ea5980000000000000000000000000000000000000000000000027db98f338cbffae4000000000000000000000000000000000000000000000009a3941b64ba40aaf80000000000000000000000000000000000000000000000002a344be0201e3cdc00000000000000000000000000000000000000000000000000ea05fa4e6c5960000000000000000000000000000000000000000000000000119c846f9c5bd4dc000000000000000000000000000000000000000000000011fcc39a87d67fafb000000000000000000000000000000000000000000000000015168c4535366d340000000000000000000000000000000000000000000000000897ad24c54327e5000000000000000000000000000000000000000000000000598884c0e531b3a4000000000000000000000000000000000000000000000000f1a88bd4fcba983c000000000000000000000000000000000000000000000009fb805cb28334090000000000000000000000000000000000000000000000000014c75255baf0df2800000000000000000000000000000000000000000000000028a4650aad045c4c0000000000000000000000000000000000000000000000005443fb2c54c3b86a00000000000000000000000000000000000000000000001326c3f0a35dda67100000000000000000000000000000000000000000000000000274fb48b17e9bf600000000000000000000000000000000000000000000000009243bc7103b7dc0000000000000000000000000000000000000000000000000092df3e5f1260bd600000000000000000000000000000000000000000000000044aa9cb60320a2840000000000000000000000000000000000000000000000000933288c194336040000000000000000000000000000000000000000000000b9a614d32235bd59d00000000000000000000000000000000000000000000000006955fe998185af7400000000000000000000000000000000000000000000000000e28047c628d4aa0000000000000000000000000000000000000000000000001248778e2076e31600000000000000000000000000000000000000000000001f9fb19299d19c21b00000000000000000000000000000000000000000000000001519e47cd03da3d20000000000000000000000000000000000000000000000009daa2c315a85122c0000000000000000000000000000000000000000000000001518417bd67059d400000000000000000000000000000000000000000000000019f8d676146d4412000000000000000000000000000000000000000000000000414d72f2c666f688000000000000000000000000000000000000000000000002adeeaf2112fb1a40000000000000000000000000000000000000000000000000276dfb6e864ee9060000000000000000000000000000000000000000000000063d5124fa46dc65f0000000000000000000000000000000000000000000000000002f7c97915eb78580000000000000000000000000000000000000000000000334e894aefe72d0dc000000000000000000000000000000000000000000000000fcf98f53b2969024000000000000000000000000000000000000000000000011348531ca5f5973800000000000000000000000000000000000000000000000000071579763e3189780000000000000000000000000000000000000000000000000000000000000000 143767.369101148179552 -s io1yftf6xuar26lsaher0qa73d0zc3csm884hjwvh -l 10000000 -p 1

**Comment by TezBaker** [comment]
Actually I didn't wait long enough, it is actually working. Thanks.
