### ISSUE TITLE
Front end multisend-iotex web-site tool still creating the incorrect command to run

### ISSUE THREAD

**Issue by TezBaker** [iotexproject/iotex-core#2422]
### What version of iotex-core are you using (`ioctl version`)?
1.1.0

### What operating system and processor architecture are you using?
Ubuntu 18.04

### What did you do? If possible, provide a recipe for reproducing the error.
Running the multi send here https://member.iotex.io/tools/multisend-iotex. It is generating an in correct command.

Starts with:
ioctl action invoke io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu 

but should be

ioctl contract invoke bytecode io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu 

Then after this should be the contract code then amount and finally the flags

### What did you expect to see?
All payments to be paid 

### What did you see instead?
Error 
Error: unknown shorthand flag: 's' in -s

The correct format is as follows:

 ioctl contract invoke bytecode io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu <code> <amount> -s io1yftf6xuar26lsaher0qa73d0zc3csm884hjwvh -l 10000000 -p 1

**Comment by raullenchai** [comment]
Tracked in https://github.com/iotexproject/web-native-staking-v2/issues/279
