### ISSUE TITLE
Add check contract address RPC

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#2424]
**What would you like to be added**:

**Why is this needed**:

**Comment by yutongp** [comment]
https://github.com/iotexproject/iotex-core/blob/master/state/account.go#L33
internally we already know if an account is contract. we can add a field `IsContract` in `AccountMeta`: https://github.com/iotexproject/iotex-core/blob/master/state/account.go#L33 to expose this property.

**Comment by yutongp** [comment]
Please notice user that they cannot use contract address in hermes. we will add this field in 1.2.

**Comment by dustinxie** [comment]
IsContract: https://github.com/iotexproject/iotex-core/blob/master/state/account.go#L108
