### ISSUE TITLE
batching API call for better performance of dapps

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-core#2437]
**What would you like to be added**:

When dapp needs to read data from a lot sources (mostly smart contracts), the number of API calls is significant. We may support batch calls to reduce the cost. 

Besides, API server's caching may be also needed for each block. 

Some references:

1. how to use smartcontract to batch calls: 
https://kovan.etherscan.io/address/0x2cc8688C5f75E365aaEEb4ea8D6a480405A48D2A#code

2. infura has a multi call API to batch requests for ETH.

**Why is this needed**:

**Comment by guo** [comment]
It is a not urgent need. but something we can start planning.

**Comment by raullenchai** [comment]
Close this one as we are moving to web3.js+multicall.
