### ISSUE TITLE
Start dev env as easy as possible

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2439]
We should have a script, e.g., `./start_dev.sh` which does the following for a developer:
- start a standalone IoTeX blockchain, together with a local explorer
- issue all IOTX testing coins to a given account
- deploy an XRC20 contract for ABC tokens and issue all ABC tokens to a given account
- return useful info:
-- URL for the developer to point his ioctl to
-- URL for the local explorer
-- an example to map local files to studio.iotex.io 
- (what else?)

With this, to dev a contract would become easy.

cc @simonerom @yutongp

**Comment by raullenchai** [comment]
For example,

```
➜  ~ ganache-cli
Ganache CLI v6.10.1 (ganache-core: 2.11.2)

Available Accounts
==================
(0) 0xF7c9dc25b6917421F8b7e7529A769Ef2a9fb8538 (100 ETH)
(1) 0xBe7b2202B48D4A11201e7Fbe7593E6Ed8BDF14a2 (100 ETH)
(2) 0x79A735BB3d73D80084F38F57d397014F93AB8D92 (100 ETH)
(3) 0x8bfEeb3cb2823Da47593B0c5D7D3eb7D168CFdA3 (100 ETH)
(4) 0xa9487E75F5325E3Bc0E184EdE7BC55B23F6bd44c (100 ETH)
(5) 0x205C9d3874136b42699c5610168C1057B6126964 (100 ETH)
(6) 0x74e43558AA3169eeb11788ca96Becd5E7ee6f90f (100 ETH)
(7) 0xd179203bb45AcFcBC16DBa2783D33CD077Daa055 (100 ETH)
(8) 0x675C456F87520f82843441a57063c57258263A83 (100 ETH)
(9) 0x084ec2e57DCB45af998a01BAA34f9aCA04381761 (100 ETH)

Private Keys
==================
(0) 0xaf8b8c68546e1f1ce41e21273b8972a6d1e5ce86193ab58a701a3ca9c2f59ea7
(1) 0x3350619e2519f7ff9856cb682aa3045dfedea5e91718dec77ebd14587fd44fb1
(2) 0x03ea950aadbb5294301e64a4b6c382e688f77f813a37433e7a266e90b800a84c
(3) 0xc3c08f13c0458521a5a7c29677d8686c0b1ade8bb413aa72ede722abb8aca0ad
(4) 0x18c2eaebde15dff6d9ea904b86504c21835c4147db2ce639526c1c483b9945ef
(5) 0x418fc82e4a84b3daf03ea59ce603642aa52fd09f33614f27c52c0f144e59a356
(6) 0xc65168ad2d5df6bfab7fef2b13b30b54b6707129039773d8eef4ad143298ce4d
(7) 0x7c7d6e3fe3858a1f9bc8384ccaa095e5f1ff517c2b706513150ed3779a0b34ef
(8) 0xcace8fc0e93d894804bf675f4513579dbd3893b5738bcd0eb18fd28fd535a2fd
(9) 0x48b00065f9ab4f4a924ca911f8ab6da43b7b1295fa1133f09b86425a200cb611

HD Wallet
==================
Mnemonic:      useless vicious shove vital debate since ship topic give immune obey rally
Base HD Path:  m/44'/60'/0'/0/{account_index}

Gas Price
==================
20000000000

Gas Limit
==================
6721975

Call Gas Limit
==================
9007199254740991

Listening on 127.0.0.1:8545
```

**Comment by simonerom** [comment]
Agree that a one-step deployment of a development environment would be very helpful.
Also #2380 as a previous reference on this.

For the pre-generated accounts, while they could be randomly generated, I believe that having them to be known addresses would be very useful in simplifying documentation/tutorials (no need to ask for additional steps to the user, that is just getting started)

**Comment by raullenchai** [comment]
The remaining bits:
- point users to an example folder of hello-world contract
- use `ioctl contract share` to share this folder
- guide user to ide.iotex.io to dev the contract
- use `ioctl contract deploy` to deploy it to the local blockchain

**Comment by simonerom** [comment]
I suggest modifying the docker configuration script such that the node port 14014 gets bound to local port 80, for the following reason:

the developer will want to try ide.iotex.io, which requires ioPay to deploy the contract and in turn, ioPay only allows to connect to a custom endpoint either on port 80 or 443, hence the developer won't be able to use ide.iotex.io with his local dev env. 

Alternatively, provide info on how to redirect 14014 to 80, but that would not fit into the "as easy as possible" process.

**Comment by raullenchai** [comment]
> I suggest modifying the docker configuration script such that the node port 14014 gets bound to local port 80, for the following reason:
> 
> the developer will want to try ide.iotex.io, which requires ioPay to deploy the contract and in turn, ioPay only allows to connect to a custom endpoint either on port 80 or 443, hence the developer won't be able to use ide.iotex.io with his local dev env.
> 
> Alternatively, provide info on how to redirect 14014 to 80, but that would not fit into the "as easy as possible" process.

Good call, checked with iopay folks and for now, it doesn't support config of localhost:14014... iopay 2.0 will support it. So we can only guide developers using `ioctl` for now.
