### ISSUE TITLE
Add a "latest" TAG to iotex-core docker hub repository

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2442]
**What would you like to be added**:
For the Docker image of the full node, can we make a "@latest" tag on the Docker HUB 

**Why is this needed**:
When we update the node to a newer version we can do just a Docker pull + cContainer restart? (no need to update any version number in our scripts, just use "latest").

**Comment by yutongp** [comment]
First, for now, "latest" tag is usually mean build from master branch. and this is more like a common practice in open source world, we probably will continue to follow.

Even for a "stable-latest" tag, I am hesitated to ask our users or delegates to use "stable-latest". I understand it is easier to start a new node with "stable-latest" and easier for documentation, but it also makes users hard to track what version they are actually using. It may introduce us more troubles if users don't aware what actually version they are running with and why they should upgrade or why not.

Here is a good article I found: https://vsupalov.com/docker-latest-tag/
using "latest" tag is easy to introduce issues even for developers, considering most of users and delegates are not very technical, i think it will be even harder to track issues with them.

and you can see eth doesn't introduce "stable-latest" or anything similar tag either: https://github.com/ethereum/go-ethereum

**Comment by simonerom** [comment]
This is very interesting insight, about the "latest" thing! Thank you for sharing!
Basically, having just to pull the explicit version, update the start script, is pretty quick for me. I got this request from a delegate who is managing a big amount of nodes in different networks (like 40-50) and having the ability to automate as much as possible makes actually sense.

Yet I agree that conveniency should never go at the expense of security.
