### ISSUE TITLE
Add a release for the node server

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2443]
**What would you like to be added**:
Add an executable release of the node server. A "latest" link to easily download the latest version at any moment would be nice too.

**Why is this needed**:
a user who wants to use the node outside docker (e.g. for development purposes or because he just can't/doesn't want to use docker) has to "git clone" and build the code. Providing the release and a "latest" link for downloading the compiled package would make the process a lot easier and (also help avoiding stale version numbers in documentation and scripts)

**Comment by yutongp** [comment]
My comment on "latest" tag can be found here: #2442.

For dev, they probably need to run on a different mode(standalone), and currently they can start standalone mode `make run`. and there is task to make the toolchain better on dev mode: #2439 .

For people don't want use docker, there is a guide to build in linux here: https://github.com/iotexproject/iotex-bootstrap#mainnet_native

Something like this: https://geth.ethereum.org/downloads/ is really nice to have. But for a small team like us, it is not easy to maintain different formats of release. It requires quite bit of effort to build, test and maintain release channels for different platform and make sure they all work. I think currently supporting docker image is still our main focus, unless we see increasing demand to install node locally.

**Comment by simonerom** [comment]
The idea, for dApp developers, is to not require them to clone and build the node (which probably has nothing to do with their application, and could be a barrier for some, bothering for others to have to do additional steps).

If this adds too much work on the maintenance side then it’s fine to clone&make or use Docker at this moment 👍
