### ISSUE TITLE
latest version of ioctl no longer runs on Ubuntu 18.04

### ISSUE THREAD

**Issue by TezBaker** [iotexproject/iotex-core#2444]
### What version of iotex-core are you using (`ioctl version`)?

1.1.1
Not sure of the exact version as it doesn't work but pulled the latest release

### What operating system and processor architecture are you using?
Ubuntu 18.04

### What did you do? If possible, provide a recipe for reproducing the error.
Tried to run the latest version of ioctl

### What did you expect to see?
to work as expected

### What did you see instead?
Error message:
ioctl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ioctl)

Seems that the latest version on Ubuntu 18.04 is GLIBC_2.27 and I'm not sure you can go to GLIBC_2.28. Upgrading libc.so.6 on Ubuntu only goes to GLIBC_2.27

**Comment by yutongp** [comment]
Hi @TezBaker , please use ubuntu 20.04 lts which has a higher version of glibc. if that is not a fessible option for you now, you can always build ioctl yourself (download the repo then run `make ioctl`, binary will be under `bin` folder)

**Comment by TezBaker** [comment]
Upgrading is not currently possible but we can rebuild ioctl as you suggest. It would also be a simple change to update the script so that it pulls down a different binary if running on 18.04.

**Comment by raullenchai** [comment]
Works on 20.04. Assume the issue addressed
