### ISSUE TITLE
Add GetLogsAPI for getting all events/logs 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2469]
https://github.com/iotexproject/iotex-core/blob/1f363de609cd8fff240ba3ef6141c72d500bead6/api/api.go#L658
Currently, in getLogs API, we support ByBlock and ByRange request. For ByRange request, the maximum count is 1000 which is not the number of return items but the number of blocks to look up from start height.
I think we need another option to get to all logs from start height as https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#events-allevents 
This is because current GetLogsByRange API can not be used to query all events of specific contract addr. (too inefficient as well)

**Comment by yutongp** [comment]
We intended to set a query limit to 1000 to avoid a big query. I think it is easy enough for client to loop over all data with a simple for loop.

**Comment by yutongp** [comment]
there shouldn't be real time usage for get all events. in real time, client should just sub to the events and get recent data which make
