### ISSUE TITLE
Modify not to get all block info to get header in HeaderByHeight  

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2471]
Previously in HeaderByHeight function (blockdao.go), we only deserialized block header. 
After filedao, we modified to read all block info(header, body, footer) from DB to get block header. 

It might affect performance when getting multiple headers to get logsBloom. (for the API node) 
It would be better if we can somehow change back to read block header only in HeaderByHeight (at least for API node or filedao_legacy)

**Comment by koseoyoung** [comment]
Have we compared the performance of using filedao_legacy and filedao_v2? 
What do you guys think of either making API node to just use filedao_legacy or finding another way to improve filedaoV2 headerByHeight as well? @CoderZhi @yutongp @dustinxie

**Comment by yutongp** [comment]
I think @dustinxie has some data on read performance comparison.
Let's just step back a little bit, do we have the data to support that if we reading the entire block to build the bloom filter, the API node performance(commit blocks, serve requests etc) will be impacted?

P.S. I agree worst case, we just use legacy file format in API nodes

**Comment by koseoyoung** [comment]
In terms of "getLogs" API, by using bloomfilter indexer, API performance does not rely on dao.HeaderByHeight anymore.
