### ISSUE TITLE
ioctl unappropriated amount

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#2473]
# What version of iotex-core are you using (`ioctl version`)?

1.1.1 ioctl within container

### What operating system and processor architecture are you using?

Linux Centos 8 in container

### What did you do? If possible, provide a recipe for reproducing the error.
Tried to pass a certain amount via IOCTL 

ioctl xrc20 transfer io1th3ud7h6lfz4a77777v9fr4fp766r09gukfq9d 2.368215624001163881 -c io1gafy2msqmmmqyhrhk4dg3ghc59cplyhekyyu26 -s signer -l 10000 

Seems like the amount failed , has happened on these
2.368215624001163881
1.131428772011580011

### What did you expect to see?

Successful transfer

### What did you see instead?

Error: failed to parse amount: unappropriated amount

**Comment by jerkyrs** [comment]
These amounts also fail
0.143213951330682559
1.046600432567924014
2.00625087043982928

**Comment by Frankonly** [comment]
@jerkyrs  Please try the latest ioctl.

**Comment by jerkyrs** [comment]
Guess since move to alpine docker the ioctl update no longer works, normally i just use version in current tagged container
```
 # ioctl update
Downloading the latest stable version ...

Error: failed to update ioctl: exec: "bash": executable file not found in $PATH
```

**Comment by raullenchai** [comment]
@Madongming pls help to release ioctl

**Comment by jerkyrs** [comment]
Just built it locally in container, works now as expected.

**Comment by Madongming** [comment]
There were some problems with ioctl files before, we have fixed them. But now that you have installed the problematic version, you can no longer use ‘ioctl update’ to upgrade, you can use the command 'curl -sS -L https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli .sh | bash -' to reinstall the latest stable version
