### ISSUE TITLE
Add release for ioctl arm64

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2501]
**What would you like to be added**:
Considering that now iotex-core for arm64 has been added to docker hub, can also ioctl release for arm64 architecture be added as well?
 
**Why is this needed**:
To "complete" the installation on Raspberry Pi and other arm boards

**Comment by Madongming** [comment]
done

**Comment by Madongming** [comment]
https://github.com/iotexproject/iotex-core/releases/download/v1.1.0/ioctl-linux-arm64
https://github.com/iotexproject/iotex-core/releases/download/v1.1.1/ioctl-linux-arm64
https://github.com/iotexproject/iotex-core/releases/download/v1.1.2/ioctl-linux-arm64
