### ISSUE TITLE
Add an optional "amount" for deployment

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2516]
**What would you like to be added**:
add an optional input argument

**Why is this needed**:
https://github.com/iotexproject/iotex-core/blob/6fc60f994391e63ca6f8fff74eacddb6ca568fd8/ioctl/cmd/contract/contractdeploysol.go#L113
amount shouldn't be hard coded to 0

**Comment by CoderZhi** [comment]
same here: https://github.com/iotexproject/iotex-core/blob/6fc60f994391e63ca6f8fff74eacddb6ca568fd8/ioctl/cmd/contract/contractdeploybytecode.go#L64

**Comment by Frankonly** [comment]
The `contract` commands adapt different number of arguments. If adding an option argument to those commands may cause confusion when ioctl identifies arguments. Therefore, I add a flag for initial amount of new deployed contract.
