### ISSUE TITLE
Provide "require()" error message when execution is reverted

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2530]
**What would you like to be added**:
When `revert()`is used in a solidity contract, it allows to set an explanatory message: would be very useful to provide this message somewhere into the tx data/logs 

For example, you can see it in etherscan for [this transaction](https://rinkeby.etherscan.io/tx/0xc3e46d6c69191a1bf7d38ceb8545a698d3e045aa55b0624cf0586ba4244ba6da), where [this is the Solidity Source](https://rinkeby.etherscan.io/address/0x27e8d50700c8d7b7a96acdf1f15628d60db00755#code). 

![image](https://user-images.githubusercontent.com/11096047/101203235-aa81d200-366a-11eb-94fe-05559f1aad54.png)

![image](https://user-images.githubusercontent.com/11096047/101203252-b1a8e000-366a-11eb-89c5-a393189943f4.png)

**Why is this needed**:
This would be very helpful for debugging issues with arguments when a tx is reverted

**Comment by raullenchai** [comment]
` % ioctl action hash 22713cd579bc9c239ae9c4cae6b335578fc11f0073c5a92627adb6286a946fa5 --endpoint api.testnet.iotex.one:443

version: 1  nonce: 189  gasLimit: 10000000  gasPrice: 0.000001 IOTX
senderAddress: io13zt8sznez2pf0q0hqdz2hyl938wak2fsjgdeml
execution: <
  contract: io1dsu9qeydrkzg4xg7tl0ncz2uccp0h9fs7s7gpp
  amount: 1 IOTX
  data: 864c26d20000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000006771e76a832ccedf7edca40affd726be801b62b6fb46b5c27f81b4d02c81528fe3f4e700000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000041e131b8b039439c54b3be3175a109ea8de1bdf1c546b8477610ee17f822ac004447d2247808170f7e75fd168a7bfa0b66984f61f88ee979f15f76d3402c6108641b00000000000000000000000000000000000000000000000000000000000000
>
senderPubKey: 04b23675d4f86f9edd327165d9d4040c47f1333c5bb7212fb22f15ef292d5a4cf80046facad3123db2f38ff00d634a87c7cd0912f52bc99ecd607f3c15c3310f53
signature: e91815a14dcb3cadf5bdea8a1f9e5f2dd64a6b4ba8ed85bc5089cff3ca37fc4f2822058dc3d8a416f18bbed6d30cff0a7ac31c930b310cd3d6d3c7dcc7c2721701
timeStamp: 1607083890
blkHash: 35f23aa77c0ddd197c85b37d419c198d5a54917f41fe0353854217e183e8f6cf
actHash: 22713cd579bc9c239ae9c4cae6b335578fc11f0073c5a92627adb6286a946fa5

#This action has been written on blockchain

status: 100 (Failure : Unknown)
actHash: 22713cd579bc9c239ae9c4cae6b335578fc11f0073c5a92627adb6286a946fa5
blkHeight: 6779173
gasConsumed: 10000000
logs:<
>
`
Looks like the err msg is not on chain which should be
