### ISSUE TITLE
EVM does't support `blockhash` build-in function

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#2531]
```
pragma solidity ^0.4.24;

contract Test {
    function getBlockHash(uint blockNumber) public view returns (bytes32) {
        return blockhash(blockNumber);
    }
}
```

No matter what parameters are entered, the `blockhash` function always returns `0000000000000000000000000000000000000000000000000000000000000000`

**Comment by dustinxie** [comment]
there's a bug in evm.GetBlockHash, will have a PR to fix
