### ISSUE TITLE
api.mainnet.iotex.one getLogs API has time-out error unlike tested full-node 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2542]
With this rpc url ```api.mainnet.iotex.one ```, getLogs API returns grpc time-out error. 

cmd that I used was 
```time ./grpcurl -d '{"filter": {"address":"io18pxsmvtj86gccdlw4hx4xdt64p9jlxzj6s2eta"}, "byRange": {"fromBlock": "0"}}' api.mainnet.iotex.one:443 iotexapi.APIService.GetLogs ``` (should be modified for your system to test) 

![image](https://user-images.githubusercontent.com/31757627/102109322-42579b00-3e77-11eb-9e01-73950f6e0fd6.png)

Previously, when I ran my full-node with bloom filter indexer to test, the same cmd worked well with shorter latency. So could be related to the roll-out.

**Comment by raullenchai** [comment]
Tried two cases:
-  query `io18pxsmvtj86gccdlw4hx4xdt64p9jlxzj6s2eta` from height 7M and seems working
-  query a busier contract `io18pxsmvtj86gccdlw4hx4xdt64p9jlxzj6s2eta` from height 8.5M and seems working

**Comment by koseoyoung** [comment]
in case of my full-node ```time ./grpcurl -plaintext -d '{"filter": {"address":"io18pxsmvtj86gccdlw4hx4xdt64p9jlxzj6s2eta"}, "byRange": {"fromBlock": "0"}}' localhost:14014 iotexapi.APIService.GetLogs``` 

it returns within 8 sec with data 

![스크린샷 2020-12-15 오전 2 07 18](https://user-images.githubusercontent.com/31757627/102111867-4507bf80-3e7a-11eb-9c60-2c12152825c9.png)

**Comment by dustinxie** [comment]
fixed in latest master
rollout ETA end of March 2021
