### ISSUE TITLE
ioctl parser for next EVM upgrade

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2544]
**Background**:
Currently I am working on upgrading EVM to 1.9.5, so far the test goes well. But I noticed after 1.9.5, EVM removed `Type reflect.Type` in abi module, see this commit:

https://github.com/ethereum/go-ethereum/commit/933acf3389d420a655b35a8dbf40536ebe058113#diff-335c7980e6ec076c550fe490b19a6e13f55ae5f94f51341599f9f37108cbaf56L48

ioctl parser is using abi module, which means our code won't compile for EVM > 1.9.5 (I actually verified)

**What would you like to be added**:
figure out a solution to resolve this

**Why is this needed**:
so we can upgrade to EVM > 1.9.5 the next time

an easy fix is to make getType --> GetType()
https://github.com/ethereum/go-ethereum/commit/933acf3389d420a655b35a8dbf40536ebe058113#diff-335c7980e6ec076c550fe490b19a6e13f55ae5f94f51341599f9f37108cbaf56R214

see if you can have a better solution

**Comment by dustinxie** [comment]
an easy fix is to make getType --> GetType()
https://github.com/ethereum/go-ethereum/commit/933acf3389d420a655b35a8dbf40536ebe058113#diff-335c7980e6ec076c550fe490b19a6e13f55ae5f94f51341599f9f37108cbaf56R214

see if you can have a better solution

**Comment by millken** [comment]
https://github.com/iotexproject/go-ethereum/pull/6

**Comment by dustinxie** [comment]
GetType() was added back later in go-ethereum
