### ISSUE TITLE
update bloom filter index to latest block

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2547]
**What would you like to be added**:
When bloomfilter index Start(), should check its height vs. tip height in blockdao, and index if there are missing blocks. 

Please refer to `func (ib *IndexBuilder) init()`, bloomfilter index should do the same

**Why is this needed**:
When delegates upgrade to 1.2, if they restart their node with their own existing db file + downloaded bloomfilter snapshot, this is needed to index the missing blocks.

**Comment by koseoyoung** [comment]
I thought rebuilding the bf indexer will be done via this process, b/c bf indexer is included in the blockdao.indexers unlike indexbuilder https://github.com/iotexproject/iotex-core/blob/master/blockchain/blockdao/blockdao.go#L132
