### ISSUE TITLE
Allow ioctl to show the list of actions for an account

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2567]
**What would you like to be added**:
ioctl account actions ADDRESS|ALIAS [ SKIP [FIRST] ]

At least it returns (for each tx):
count + type + status + recipient + amount + hash
```
# lists all actions sorted from the most recent
$ ioctl account actions myAccount 

# lists all actions sorted from the most recent, skipping the latest 10
$ ioctl account actions myAccount 10 

# lists the most recent action
$ ioctl account actions myAccount 0 1 

# Example
12 transfer success io1jsljstd5xt62gzyde0usvqdjyf4vhh8peks9lf 12 IOTX ca01376611a11215589aaa664f71c8e466a5b5288438e50026f977e6928e2c48
```

**Why is this needed**:
When web explorers fail, we need a way to still be able to explore wallet transactions, then we use` ioctl account action hash `to get more details on each transaction

**Comment by millken** [comment]
#2568

**Comment by millken** [comment]
pr #2568 submitted

**Comment by simonerom** [comment]
I tested the command and it works fine, but it seems to not include all actions: specifically if we take  `https://iotexscan.io/address/<address>` explorer view as a reference, the ioctl command seems to only include actions that are listed in the "Total Actions" tab, but all actions in the "Contract Actions" tab seem not to be included. 

Assuming that the XRC20 and NFT actions are already included, can we also include the Contract Actions in the output?

**Comment by simonerom** [comment]
> I will check it later, can you give some example address?

Sure: let's take this address as an example: https://iotexscan.io/address/io1jzdxuv7etyfvs7th7jwyspswr6y660zjd7lykg

the command `ioctl account actions io1jzdxuv7etyfvs7th7jwyspswr6y660zjd7lykg --limit 138` returns all the 138 actions that you can see on the iotexscan account summary.
In fact, iotexscan shows 138 actions, and these 138 actions are listed in the **Total Actions** tab:

![image](https://user-images.githubusercontent.com/11096047/108717360-7c9b8380-751d-11eb-91b1-3615397d30ed.png)

But these 138 are not **all the actions**, they seem to be all transfers and executions **initiated by the user** plus all the IOTX received, but they **do not include** the actions listed in the **Contract Actions** tab (IOTX received by a contract, like HERMES or ByrnDrop for example): as you can see there are 360 actions listed in the **Contract Actions** tab, that are not included in the "**Total Actions**" tab in iotexscan, and they are not included in the `ioctl` output as well.

We should provide, at least in `ioctl`, a raw list of all actions related to an address for the user to do its own filtering and calculations.

**Comment by Liuhaai** [comment]
This issue will be fixed after the release of iotex-analytics v2
