### ISSUE TITLE
Block producer stuck after loss of connectivity, did not recover after network was resumed

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2569]
### What version of iotex-core are you using (`ioctl version`)?
packageVersion:"v1.1.3" packageCommitID:"66cb15ff51ae1a3d220d1f41bc67704b2bc58afa" gitStatus:"clean" goVersion:"go version go1.14.6 linux/amd64" buildTime:"2020-12-01-UTC/02:15:45"

localhost:14014:
packageVersion:"v1.1.1" packageCommitID:"d474676d98d6b299022d86e56a658b81a360b7cf" gitStatus:"dirty" goVersion:"go version go1.14.6 linux/amd64" buildTime:"2020-08-21-UTC/22:58:24"

### What operating system and processor architecture are you using?

Ubuntu 18.04 64bit

### What did you do? If possible, provide a recipe for reproducing the error.
The server got disconnected by the network due to router maintenance, after connectivity was restored the node did not recover the sync.

### What did you expect to see?
The node to start syncing again after network connectivity was restored

### What did you see instead?
The node was stuck at the last Height before it got disconnected, with no specific error message. After I killed and restarted the node it synced back to the current blockchain height, but I saw these errors during the sync process:

![image](https://user-images.githubusercontent.com/11096047/107263982-b0b57580-6a42-11eb-94f3-ea73ac53df81.png)

**Comment by dustinxie** [comment]
was able to repro the issue by disabling network connection for 10 second, then re-enabling

the root-cause is that the network disconnection (even short-time) caused p2p to drop and lose all its peers, after re-enabling network it shows the number of connected peers becomes 0

potential fix is to periodically check the P2P status, and re-dial in case of connection loss

**Comment by dustinxie** [comment]
2648 is better/correct implementation
