### ISSUE TITLE
ioctl unstable installation fails on macOS

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2575]
see https://github.com/iotexproject/homebrew-ioctl-unstable/issues/1

**Comment by raullenchai** [comment]
@simonerom pls try again

**Comment by simonerom** [comment]
Still getting error:

```bash
~ » brew install ioctl-unstable
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 4 casks.

Error: iotexproject/ioctl-unstable/ioctl-unstable is a head-only formula.
To install it, run:
  brew install --HEAD iotexproject/ioctl-unstable/ioctl-unstable
```

**Comment by simonerom** [comment]
But then this command (as suggested in the error message) did the job:

`brew install --HEAD iotexproject/ioctl-unstable/ioctl-unstable`

**Comment by raullenchai** [comment]
@xianhuawei pls help out here - this should also be part of the cut/release process.

**Comment by xianhuawei** [comment]
fix in https://github.com/iotexproject/homebrew-ioctl-unstable/pull/2
