### ISSUE TITLE
Claim reward failure

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#2582]
Hermes claim reward failure with unknown error. 
Here is reverted action: 
 https://iotexscan.io/action/c7dd07ac746a042db4b8d8bcef026e95fd66cc21eef795b026fd4c67c92d242d

**Comment by dustinxie** [comment]
chatted with Leo, it is working fine after restarting the hermes service. Let's keep watching if it comes up again

related hermes code: https://github.com/iotexproject/iotex-hermes/blob/188077f109987ffd428467541c20afff5dcc698b/cmd/claim/claim.go#L89

**Comment by raullenchai** [comment]
Close for now. pls reopen if it happens again @ququzone @dustinxie
