### ISSUE TITLE
better error handling with Hash() (hash.Hash256, error)

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2584]
**What would you like to be added**:
hash of envelope/sealed envelope only returns hash.Hash256, hiding any error that might occur during the process. as a result, panic is used (instead of an all-zero hash value) to indicate error

return (hash.Hash256, error) could mitigate this issue and remove unnecessary panic

**Why is this needed**:
better code

**Comment by ashishsnigam** [comment]
@dustinxie @raullenchai I picked this issue and changed function func (sealed *SealedEnvelope) Hash() (hash.Hash256, error) in file sealedenvelope.go. This function is called in 127 places in overall source code and may require another level of refactoring in places like local_transfer_test.go # 394. Please see attached code snippet from there.

var selp action.SealedEnvelope
			err := backoff.Retry(func() error {
				var err error
				selp, err = as.GetActionByActionHash(tsf.Hash())
				return err
			}, bo)

Just want to confirm if this is the expectation from this issue. 
Please see initial changes for review in PR  https://github.com/iotexproject/iotex-core/pull/2732

**Comment by ashishsnigam** [comment]
Hi All, This task is completed. Please see PR. https://github.com/iotexproject/iotex-core/pull/2732
