### ISSUE TITLE
[ioctl] refactor common APIServiceClient and JwtAuth code

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2607]
**What would you like to be added**:
in ioctl module https://github.com/iotexproject/iotex-core/tree/master/ioctl, there are many occurrences of below code snippet which creates a gRPC connection and adds a JWT auth to the context:
```
conn, err := util.ConnectToEndpoint(config.ReadConfig.SecureConnect && !config.Insecure)
	if err != nil {
		return nil, output.NewError(output.NetworkError, "failed to connect to endpoint", err)
	}
	defer conn.Close()
	cli := iotexapi.NewAPIServiceClient(conn)
	ctx := context.Background()

jwtMD, err := util.JwtAuth()
	if err == nil {
		ctx = metautils.NiceMD(jwtMD).ToOutgoing(ctx)
	}
```
Find a solution to reconcile this common code, so ioctl does not need to call it multiple times

**Why is this needed**:
remove duplicate code

**Comment by Liuhaai** [comment]
Hi @dustinxie, could I work on this issue?

**Comment by Liuhaai** [comment]
The new `client` interface has implemented this feature, which will be used in `newcmd`. The issue can be closed.
