### ISSUE TITLE
[ioctl] add 'ioctl account info' command

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2608]
**What would you like to be added**:
for example
`ioctl account info io1vqzcl56vlfspyaadyxhqy07jrmalx73vdaklzn` produces the following output:
```
io1vqzcl56vlfspyaadyxhqy07jrmalx73vdaklzn:
{
  "address": "io1vqzcl56vlfspyaadyxhqy07jrmalx73vdaklzn",
  "balance": "0",
  "nonce": 1,
  "pendingNonce": 2,
  "isContract": true,
  "contractByteCode": "YIBgQFI0gBVgD1dgAID9W1BgBDYQYChXYAA1YOAcgGPugqxeFGAtV1tgAID9W2BWYASANgNgIIEQFWBBV2AAgP1bgQGQgIA1kGAgAZCSkZBQUFBgbFZbYEBRgIKBUmAgAZFQUGBAUYCRA5DzW2AAgIJAkFCAfy2T93SYYtM5afsmF1dBC0gGWhvIalbaXEeCC9Bj4jOCYEBRYEBRgJEDkKKAkVBQkZBQVv6iZWJ6enIxWCAKJYzQjqme4RqmjHi20r9+qRJhWh5kqBuQoqvKLdWc+mRzb2xjQwAFDAAy"
}
```

**Why is this needed**:
to display an account's information

**More info**:
Here's the protobuf definition of the account/address: https://github.com/iotexproject/iotex-proto/blob/master/proto/types/blockchain.proto#L100-L109

**Comment by Liuhaai** [comment]
Hi @dustinxie, I have roughly programed the code of `account info` command under ioctl/cmd/account/accountinfo.go. But I don't know how to start the CLI `ioctl` program with new cmd added. Could you give me some help?

**Comment by dustinxie** [comment]
1. `make ioctl`
2. run `ioctl account info io1nrm8gz3wqhgf7zsz75ja7kycfg8zxq0mwv92d7 --endpoint=api.testnet.iotex.one:443` as a test of your code
3. could you push your code to a branch?

**Comment by Liuhaai** [comment]
> 1. `make ioctl`
> 2. run `./bin/ioctl account info io1w97pslyg7qdayp8mfnffxkjkpapaf83wmmll2l --endpoint=api.testnet.iotex.one:443` as a test of your code, and paste the output here
> 3. could you push your code to a branch?

Thanks. BTW, any suggestions for the decoder of `contractByteCode`? I failed to print the contractByteCode as the format of the example. The direct printout of bytecode is like below

> '\ufffd\`@R\`\u00046\u0010a\u0001\ufffdWc\ufffd\ufffd\ufffd ......

**Comment by dustinxie** [comment]
thx, looks not bad. 2 things to be fixed:
1. contractByteCode is []byte, we want to print out as hex-string, how to do that?
2. there is also a field `NumActions`, which is missing in your code

**Comment by dustinxie** [comment]
thx, comment in https://github.com/iotexproject/iotex-core/pull/2610
