### ISSUE TITLE
sync from a blank folder failed

### ISSUE THREAD

**Issue by lcgogo** [iotexproject/iotex-core#2612]
### What version of iotex-core are you using (`ioctl version`)?

1.1.3 and 1.1.4

### What did you see instead?

{"level":"info","ts":1619010439.1655602,"caller":"p2p/agent.go:253","msg":"Connected bootstrap node.","ioAddr":"io1njenq35us7fk7ntud6czpcwgpa3scs8frljm2a","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ"}
{"level":"fatal","ts":1619010439.1844163,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1njenq35us7fk7ntud6czpcwgpa3scs8frljm2a","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting blockchain: failed to start child services: key = 0000000000000000 doesn't exist: not exist in DB","errorVerbose":"not exist in DB\ngithub.com/iotexproject/iotex-core/db.init\n\t/go/apps/iotex-core/db/kvstore_impl.go:23\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5480\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5475\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5475\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5475\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5475\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nkey = 0000000000000000 doesn't exist\ngithub.com/iotexproject/iotex-core/db.(*BoltDB).Get.func1\n\t/go/apps/iotex-core/db/db_bolt.go:88\ngo.etcd.io/bbolt.(*DB).View\n\t/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:725\ngithub.com/iotexproject/iotex-core/db.(*BoltDB).Get\n\t/go/apps/iotex-core/db/db_bolt.go:81\ngithub.com/iotexproject/iotex-core/blockindex.(*bloomfilterIndexer).rangeBloomFilter\n\t/go/apps/iotex-core/blockindex/bloomfilterindexer.go:238\ngithub.com/iotexproject/iotex-core/blockindex.(*bloomfilterIndexer).initRangeBloomFilter\n\t/go/apps/iotex-core/blockindex/bloomfilterindexer.go:115\ngithub.com/iotexproject/iotex-core/blockindex.(*bloomfilterIndexer).Start\n\t/go/apps/iotex-core/blockindex/bloomfilterindexer.go:93\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nfailed to start child services\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:96\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:430\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}

**Comment by lcgogo** [comment]
start from a blank data folder with followed error

{"level":"info","ts":1619159498.2796876,"caller":"p2p/agent.go:253","msg":"Connected bootstrap node.","ioAddr":"io10p6jvej6ucfklkpwgpt9fklcg5s4y6hu7hy2m8","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ"}
{"level":"info","ts":1619159498.279966,"caller":"p2p/agent.go:253","msg":"Connected bootstrap node.","ioAddr":"io10p6jvej6ucfklkpwgpt9fklcg5s4y6hu7hy2m8","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-1.mainnet.iotex.one/tcp/4689/p2p/12D3KooWN4TQ1CWRA7yvJdQCdti1qARLXXu2UEHJfycn3XbnAnRh"}
{"level":"info","ts":1619159498.2858622,"caller":"p2p/agent.go:253","msg":"Connected bootstrap node.","ioAddr":"io10p6jvej6ucfklkpwgpt9fklcg5s4y6hu7hy2m8","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-0.mainnet.iotex.one/tcp/4689/p2p/12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5"}
{"level":"info","ts":1619159498.3135698,"caller":"p2p/agent.go:253","msg":"Connected bootstrap node.","ioAddr":"io10p6jvej6ucfklkpwgpt9fklcg5s4y6hu7hy2m8","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-3.mainnet.iotex.one/tcp/4689/p2p/12D3KooWEsmwaorbZX3HRCnhkMPjMAHzwu3om1pdGrtVm2QaM35n"}
{"level":"fatal","ts":1619159499.2568889,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io10p6jvej6ucfklkpwgpt9fklcg5s4y6hu7hy2m8","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting election committee: failed to get tip height: failed to get tip height: failed to execute callback with any client: 401 Unauthorized account disabled\n","errorVerbose":"401 Unauthorized account disabled\n\nfailed to execute callback with any client\ngithub.com/iotexproject/iotex-election/carrier.(*EthClientPool).Execute\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:111\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:188\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).Tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:184\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:215\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:414\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nfailed to get tip height\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:203\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).Tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:184\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:215\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:414\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nfailed to get tip height\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:217\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:414\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting election committee\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:415\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:101\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}

**Comment by dustinxie** [comment]
talked with user online, fixed now

**Comment by zacker0515** [comment]
> talked with user online, fixed now

how to solve the problem ,i have the same question

**Comment by lcgogo** [comment]
> 
> 
> > talked with user online, fixed now
> 
> how to solve the problem ,i have the same question

根据
https://github.com/iotexproject/iotex-bootstrap

从0开始同步，要做下面两步中的1种，因为从0开始，要从eth映射iotx主链的投票信息。而之前默认config里自带的infura的一个token失效了，所以用默认的config启动的iotx不能从eth上读到genesis的投票信息了。
我推荐方法2，从一个镜像里解压出来

    Option 1: If you plan to run your node as a gateway, please use the snapshot with index data: https://t.iotex.me/mainnet-data-with-idx-latest.

    Optional 2: If you only want to sync chain data from 0 height without relaying on legacy delegate election data from Ethereum, you can setup legacy delegate election data with following command:

curl -L https://storage.googleapis.com/blockchain-golden/poll.mainnet.tar.gz > $IOTEX_HOME/poll.tar.gz; tar
