### ISSUE TITLE
Better Management of Log Files

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2661]
**Why is this needed**:
The current log file is monolithic and keeps growing in size, and becomes too large to be managed.

**What would you like to be added**:
1. have a separate log file every day, e.g., 1011.log, 1012.log, 1013.log...
2. log rotation - only keep the recent 30days of logs
3. make both features configurable 

For all these features, you can refer to how Nginx manages logs.

**Compatibility**
don't break the current ELK pipeline
make sure the log ingestion in ELK still works (cc @xianhuawei )

**Comment by CoderZhi** [comment]
@millken you may refer to https://programmer.help/blogs/zap-log-classification-and-file-splitting-log-cutting-by-time-integration-demo.html using some existing tools

**Comment by millken** [comment]
> @millken you may refer to https://programmer.help/blogs/zap-log-classification-and-file-splitting-log-cutting-by-time-integration-demo.html using some existing tools

https://github.com/lestrrat-go/file-rotatelogs 

**WARNINGS
THIS PROJECT HAS BEEN ARCHIVED. IT WILL NOT RECEIVE UPDATES, THE AUTHOR DOES NOT WISH TO MAINTAIN OR SUPPORT IT. IN SHORT, DO NOT USE THIS PROJECT.**

**Comment by millken** [comment]
`lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.

**Comment by Liuhaai** [comment]
> `lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.

[`lumberjack` can automatically roll log files based either on date or on file size.](https://github.com/bdurand/lumberjack#automatic-log-rolling).

**Comment by millken** [comment]
Pls see code first
https://github.com/natefinch/lumberjack/blob/7d6a1875575e09256dc552b4c0e450dcd02bd10e/lumberjack.go#L152-L156

> > `lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.
> 
> [`lumberjack` can automatically roll log files based either on date or on file size.](https://github.com/bdurand/lumberjack#automatic-log-rolling).

**Comment by Liuhaai** [comment]
> Pls see code first https://github.com/natefinch/lumberjack/blob/7d6a1875575e09256dc552b4c0e450dcd02bd10e/lumberjack.go#L152-L156
> 
> > > `lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.
> > 
> > 
> > [`lumberjack` can automatically roll log files based either on date or on file size.](https://github.com/bdurand/lumberjack#automatic-log-rolling).

thx for the info. [Logrotate](https://linux.die.net/man/8/logrotate) might be a better alternative.

**Comment by raullenchai** [comment]
> > Pls see code first https://github.com/natefinch/lumberjack/blob/7d6a1875575e09256dc552b4c0e450dcd02bd10e/lumberjack.go#L152-L156
> > > > `lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.
> > > 
> > > 
> > > [`lumberjack` can automatically roll log files based either on date or on file size.](https://github.com/bdurand/lumberjack#automatic-log-rolling).
> 
> thx for the info. [Logrotate](https://linux.die.net/man/8/logrotate) might be a better alternative.

@xianhuawei - can this be realized at k8s level using  Logrotate ?

**Comment by Liuhaai** [comment]
> > > Pls see code first https://github.com/natefinch/lumberjack/blob/7d6a1875575e09256dc552b4c0e450dcd02bd10e/lumberjack.go#L152-L156
> > > > > `lumberjack` rolling files focusd on `maxSize`, not by `timeFormat`, `RotateFile` also refers to its code.
> > > > 
> > > > 
> > > > [`lumberjack` can automatically roll log files based either on date or on file size.](https://github.com/bdurand/lumberjack#automatic-log-rolling).
> > 
> > 
> > thx for the info. [Logrotate](https://linux.die.net/man/8/logrotate) might be a better alternative.
> 
> @xianhuawei - can this be realized at k8s level using Logrotate ?

Here is [an article](https://logz.io/blog/a-practical-guide-to-kubernetes-logging/) introduces log-roration tools on kubernetes. @xianhuawei Could you give a try?

**Comment by raullenchai** [comment]
This is what happened on a node
```
sgp1-01:~/iotex-var/log# ls
s.log  update.log
sgp1-01:~/iotex-var/log# du -sh .
8.9G	.
```

**Comment by raullenchai** [comment]
As of now, this problem still exists. Reopen the issue

```
###:~/iotex-var/log# du -sh .
8.6G	.
```

**Comment by raullenchai** [comment]
> As of now, this problem still exists. Reopen the issue
> 
> ```
> ###:~/iotex-var/log# du -sh .
> 8.6G	.
> ```

This is for a node that is NOT running k8s.
