### ISSUE TITLE
About latest release

### ISSUE THREAD

**Issue by chenrui333** [iotexproject/iotex-core#2672]
👋  it looks like the latest 1.2.0 did not get marked as `latest release`, so raise this issue to double confirm. Thanks!

relates to Homebrew/homebrew-core#77036

**Comment by dustinxie** [comment]
Thanks for the quick note!
We tagged the 1.2.0 binary and is WIP to verify upgrade instructions, official release v1.2.0 will come out soon in a day or 2. Stay tuned!

**Comment by chenrui333** [comment]
Thanks for confirming it. 💯

**Comment by dustinxie** [comment]
v1.2.0 is officially released now, you can go ahead on your PR
