### ISSUE TITLE
"ioctl node delegate -n" stopped working

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2675]
### What version of iotex-core are you using (`ioctl version`)?
```
Client:
packageVersion:"v1.1.3-31-g5c8f449f"  packageCommitID:"5c8f449f8a6c8ce746d1c82870d760856985b241"  gitStatus:"dirty"  goVersion:"go version go1.14.6 linux/amd64"  buildTime:"2021-03-01-UTC/22:11:15"

localhost:14014:
packageVersion:"v1.1.1"  packageCommitID:"d474676d98d6b299022d86e56a658b81a360b7cf"  gitStatus:"dirty"  goVersion:"go version go1.14.6 linux/amd64"  buildTime:"2020-08-21-UTC/22:58:24"
```

### What operating system and processor architecture are you using?
Ubuntu 18

### What did you do? If possible, provide a recipe for reproducing the error.
ìoctl node delegate -n`

### What did you expect to see?
The list of active delegates for the next epoch

### What did you see instead?
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/11096047/118012704-a19bd780-b351-11eb-80eb-d1d42804ace6.png">

**Comment by Liuhaai** [comment]
Currently, ioctl only support command line like "ioctl node delegate -e xxx". Flags "-n" "-a" has not been implemented.
```
func init() {
	nodeDelegateCmd.Flags().Uint64VarP(&epochNum, "epoch-num", "e", 0,
		config.TranslateInLang(flagEpochNumUsages, config.UILanguage))
	nodeStatus = map[bool]string{true: "active", false: ""}
	probatedStatus = map[bool]string{true: "probated", false: ""}
}
```

**Comment by simonerom** [comment]
Hi @Liuhaai 
I’m pretty sure it worked before 😊
When we bootstrap mainnet alpha back in 2019, several delegates asked for this feature  to ease the planning of updates by knowing in advance if the next epoch your delegate was “at rest” and so available for update.

I myself have used it many times. Not sure why/when it disappeared.

**Comment by Liuhaai** [comment]
thx for feedback. I will check again

**Comment by Liuhaai** [comment]
https://github.com/iotexproject/iotex-core/pull/2187/files#diff-f72617c5afa49c8e6ff62624c6f1e29e66338d8820b9cf6f7216e57a8485bf3f

**Comment by dustinxie** [comment]
@Liuhaai, let's do this: 
1. re-enable this `-n` flag
2. verify if it working correctly, i.e, run it to get next epoch's delegate list `A`
3. wait until next epoch, check if delegate list matches with `A`

**Comment by Liuhaai** [comment]
Hi @simonerom . The mechanism of epoch generation has changed. As mentioned in the code comment, the next delegate could not be determined until the end of the epoch. 
Here is the result of requesting next delegate with `ioctl node delegate -n`
```
delegates of upcoming epoch #XXX are not determined
```
I think we can close this issue

**Comment by simonerom** [comment]
Oh, I see. This is a bad news, that was a useful feature.

Thank you for looking into it 🙏🏻
