### ISSUE TITLE
cross compile of ioctl doesn't work

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2684]
`GOOS=linux GOARCH=arm64 make ioctl `
```
...
github.com/ethereum/go-ethereum/core
google.golang.org/grpc/internal/transport
google.golang.org/grpc
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/go-ethereum/internal/ethapi
github.com/grpc-ecosystem/go-grpc-middleware/retry
github.com/iotexproject/iotex-proto/golang/iotexapi
github.com/ethereum/go-ethereum/signer/core
github.com/ethereum/go-ethereum/accounts/external
github.com/ethereum/go-ethereum/accounts/abi/bind
github.com/iotexproject/iotex-election/contract
github.com/iotexproject/iotex-election/carrier
make: *** [ioctl] Error 1
```

**Comment by leyafo** [comment]
This is a CGO cross compile problem.
https://github.com/ethereum/go-ethereum/issues/17452
https://github.com/ethereum/go-ethereum/issues/15662

According with their comments, it has three ways to reslove this problem:
1. Upgrading `go-ethereum`, we are using v1.7.4.  They said that 1.8.23 doesn't have this problem. https://github.com/ethereum/go-ethereum/issues/15662#issuecomment-505064956

2. Use `x-go` https://github.com/ethereum/go-ethereum/issues/16818. The cross compiling is integrated the make file in new version of `go-ethereum`.
https://geth.ethereum.org/docs/install-and-build/cross-compile

3. Some built a tool which solve the problem for CGO. https://github.com/nomad-software/vend.  I've tried, but my network has broken when I pulling the packges.

This [issue](https://github.com/ethereum/go-ethereum/issues/16818) has reported the same problem, he use `xgo` to solve this problem. I tried in my Mac, `xgo --targets=linux/arm64 ./`, but my doker has the network proxy problem. I can't pulling the docker image in my computer.

**Comment by niklr** [comment]
I'm getting the following make error on Ubuntu 18 LTS, not sure if this is related.

```
ok  	github.com/iotexproject/iotex-core/tools/executiontester/blockchain	(cached)
?   	github.com/iotexproject/iotex-core/tools/ioctl	[no test files]
?   	github.com/iotexproject/iotex-core/tools/ioctl/readme	[no test files]
?   	github.com/iotexproject/iotex-core/tools/iomigrater	[no test files]
?   	github.com/iotexproject/iotex-core/tools/iomigrater/cmds	[no test files]
?   	github.com/iotexproject/iotex-core/tools/iomigrater/common	[no test files]
?   	github.com/iotexproject/iotex-core/tools/minicluster	[no test files]
?   	github.com/iotexproject/iotex-core/tools/multisend	[no test files]
?   	github.com/iotexproject/iotex-core/tools/staterecoverer	[no test files]
?   	github.com/iotexproject/iotex-core/tools/util	[no test files]
?   	github.com/iotexproject/iotex-core/tools/xctl	[no test files]
?   	github.com/iotexproject/iotex-core/tools/xctl/readme	[no test files]
FAIL
make: *** [Makefile:110: test] Error 1
```

**Comment by Liuhaai** [comment]
> This is a CGO cross compile problem.
> [ethereum/go-ethereum#17452](https://github.com/ethereum/go-ethereum/issues/17452)
> [ethereum/go-ethereum#15662](https://github.com/ethereum/go-ethereum/issues/15662)
> 
> According with their comments, it has three ways to reslove this problem:
> 
> 1. Upgrading `go-ethereum`, we are using v1.7.4.  They said that 1.8.23 doesn't have this problem. [ethereum/go-ethereum#15662 (comment)](https://github.com/ethereum/go-ethereum/issues/15662#issuecomment-505064956)
> 2. Use `x-go` [ethereum/go-ethereum#16818](https://github.com/ethereum/go-ethereum/issues/16818). The cross compiling is integrated the make file in new version of `go-ethereum`.
>    https://geth.ethereum.org/docs/install-and-build/cross-compile
> 3. Some built a tool which solve the problem for CGO. https://github.com/nomad-software/vend.  I've tried, but my network has broken when I pulling the packges.
> 
> This [issue](https://github.com/ethereum/go-ethereum/issues/16818) has reported the same problem, he use `xgo` to solve this problem. I tried in my Mac, `xgo --targets=linux/arm64 ./`, but my doker has the network proxy problem. I can't pulling the docker image in my computer.

Thx for feedback. I succeed in cross compiling ioctl using [xgo](https://github.com/techknowlogick/xgo). Makefile will be updated to make `make ioctl` work. But I can't give some help on network issue, you should build a proxy to pass the firewall .
