### ISSUE TITLE
Use -s account as caller

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2687]
https://github.com/iotexproject/iotex-core/blob/654ba150b7f2a58b9ef8cf315bd99a154c6a330f/ioctl/cmd/action/action.go#L417

It is ok to use zero address as default caller, but if user specified a caller, e.g., `ioctl contract test ... -s $account`, use $account instead.

**Comment by Liuhaai** [comment]
@CoderZhi Is this account the signing account in Line 67
https://github.com/iotexproject/iotex-core/blob/654ba150b7f2a58b9ef8cf315bd99a154c6a330f/ioctl/cmd/action/action.go#L67
