### ISSUE TITLE
Architecture arm64 is not supported by this installation script

### ISSUE THREAD

**Issue by yym-store** [iotexproject/iotex-core#2690]
<img width="732" alt="截屏2021-06-02 下午12 48 14" src="https://user-images.githubusercontent.com/30860965/120425469-db845a80-c3a0-11eb-8cae-c9f568b2fe24.png">

MacBook Pro (13-inch, M1, 2020) macOS Big Sur  m1

**Comment by Madongming** [comment]
fixed
![pic](https://user-images.githubusercontent.com/13083058/120442460-370e1280-c3b8-11eb-8b54-2b59792f9388.jpg)
