### ISSUE TITLE
Use mock in `api/grpcserver_test.go` and `api/web3server_test.go`

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2696]
**What would you like to be added**:
Use mock blockchain, mock factory, and other components in api_test.go

**Why is this needed**:
The unit tests should rely on mock implementation but not real implementation. If we do want to use real implementation, move into e2e test.

**Comment by Liuhaai** [comment]
Many unit tests in api_test.go need to check transactions in the blockchain (https://github.com/iotexproject/iotex-core/blob/master/api/api_test.go#L2333-L2479). The easy way to commit these txs onto the chain is to use a unmocked chain.

**Comment by Liuhaai** [comment]
The `coreservice.go` has been separated from `api.go`. Now mocked coreservice can be used in the tests of grpc and web3
