### ISSUE TITLE
block commit being delayed 5 seconds

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2704]
**Background**:
After v1.2 launch, some nodes will run into this phenomenon
1. block N is generated at timestamp `ts`
2. at time `ts + 5s`, log print out: 
`"msg":"failed to calculate round for generating consensus event","error":"failed to get block at height N+1: not exist in DB","height":N+1`
3. at time `ts + 5s + 50ms`, log print out
`"Successfully committed block","height":N`

In summary, block N should be committed within short period time (say `ts + 1s` considering the time it takes to receive the block from p2p + time to write to DB) after its generation, but we are seeing a delay of 5 seconds here, which is not normal

**Occurrence**
this is random/sporadic
1. couple of delegates (one of them PublicPayments) reported seeing this
2. also seen on iotex-prod-delegates

**Impact**:
this is NOT causing consensus to fail, but need to find out the root-cause why this happens

**Comment by dustinxie** [comment]
[logsPublicPayments21May2021.txt](https://github.com/iotexproject/iotex-core/files/6628516/logsPublicPayments21May2021.txt)

**Comment by raullenchai** [comment]
cc @xianhuawei
