### ISSUE TITLE
Reduce staking index DB storage

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2711]
**What would you like to be added**:
staking.index.db may store a lot of duplicates, for example:

height: 5 --> cand{1, 2, 3}
height: 6 --> cand{1, 2, 3} // same as height 5
height: 7 --> cand{1, 2, 3} // same as height 5
height: 8 --> cand{1, 2, 3, 4}

**Why is this needed**:
At height 11000000, size of staking.index.db has already reached 10.5GB, which equals to half of all chain.db combined (22~24GB)

**Comment by jrynkiew** [comment]
good idea!
