### ISSUE TITLE
more contract tests

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2715]
**What would you like to be added**:
1. Refer to https://github.com/iotexproject/iotex-core/commit/86d52baefec035f4133a8463b47c414490dbd76d
2. add more contract test, using solidity v0.8.4, and contracts from https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts

**Why is this needed**:
increase contract test coverage

**Comment by raullenchai** [comment]
https://consensys.net/blog/news/everything-you-need-to-know-about-the-istanbul-hard-fork/
EIP-152: Adds Blake2 compression function F precompile.
EIP-1108: Reduce alt_bn128 precompile gas costs
EIP-1344: chainid
EIP-1844: reprices certain opcodes
EIP-2028: 68 gas per byte to 16 gas per byte
EIP-2200: Provides a structured definition of net gas metering changes for SSTORE opcode
