### ISSUE TITLE
In addition to "unsable", would be nice to choose version too. eg "v1.2.0"

### ISSUE THREAD

**Issue by dzuqe** [iotexproject/iotex-core#2720]
**What would you like to be added**:
In addition to "unsable", would be nice to choose version too. eg "v1.2.0"
That is:
`curl "link/to/install-cli.sh" | sh -c "v1.2.0"`

**Why is this needed**:
I was trying to install latest release, but it doesn't have any binaries linked to it. I manually hacked the script to install an earlier version instead

**Comment by xianhuawei** [comment]
![image](https://user-images.githubusercontent.com/3870801/124222301-0f83a480-db34-11eb-8d78-9bfa48b01ae7.png)

it can use this (example install v.1.2.0):

export CLI_RELEASE_TAG='v1.2.0'

curl https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli.sh | sh
