### ISSUE TITLE
I want to contribute to the Iotex project

### ISSUE THREAD

**Issue by alchemlstcoin** [iotexproject/iotex-core#2723]
Good evening I am from Colombia, I am 19 years old and I am a student in systems engineering, I have good training and knowledge in the work of tokens, in the scanner and token finder, I have many ideas to improve both the improvement of IotexScan, and tokens, I have a good and responsible commitment.

este es mi correo personal.!
alchemis04@gmail.com

**Comment by Liuhaai** [comment]
Hi @alchemlstcoin, ideas are welcomed to our project! The frontend code of iotexscan is at [iotex-explorer](https://github.com/iotexproject/iotex-explorer), whose data comes from [iotex-analytics](https://github.com/iotexproject/iotex-analytics). If you have any idea, you can submit a issue at related repo. FYI, we are switching from https://iotexscan.io/ to https://iotexscout.io/.

**Comment by Liuhaai** [comment]
I think we can close this issue. @alchemlstcoin

**Comment by alchemlstcoin** [comment]
ok I will expose my ideas in the following repositories.
Thanks
