### ISSUE TITLE
Remove ctrl.Finish() in test files

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2725]
**What would you like to be added**:
Remove ctrl.Finish() in test files

**Why is this needed**:
https://pkg.go.dev/github.com/golang/mock/gomock#Controller.Finish
>New in go1.14+, if you are passing a *testing.T into NewController function you no longer need to call ctrl.Finish() in your test methods.

**Comment by krishnaindani** [comment]
hey, Can I try on this issue? Would like to contribute to it.

**Comment by raullenchai** [comment]
> hey, Can I try on this issue? Would like to contribute to it.

Go ahead to send out a PR to fix it!

**Comment by krishnaindani** [comment]
sure. Thank you.

**Comment by krishnaindani** [comment]
I see Dockerfile at go 1.14 https://github.com/iotexproject/iotex-core/blob/master/Dockerfile#L1 but the go.mod it is 1.13 https://github.com/iotexproject/iotex-core/blob/master/go.mod#L3. Do we need to upgrade it there?
