### ISSUE TITLE
[ioctl] new accounts being generated unintentionally

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2730]
### What version of iotex-core are you using (`ioctl version`)?
master

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
after using ioctl for a while, new accounts are being generated (w/o calling `ioctl account create` to add new account)

### What did you expect to see?
no new account should be generated w/o calling `ioctl account create`

### What did you see instead?
`ioctl account list`, can see anonymous new accounts are added

**Comment by dustinxie** [comment]
this is an example running `ioctl account list`, seeing these anonymous new accounts
<img width="310" alt="Screen Shot 2021-07-16 at 1 27 57 PM" src="https://user-images.githubusercontent.com/12551272/126005026-27eaae7c-7791-41ca-af60-bbf655f7aa0e.png">

**Comment by raullenchai** [comment]
I didn't see this but I am using an older version of ioctl
`gitStatus:"clean"  goVersion:"go version go1.15.5 darwin/amd64"  buildTime:"2020-12-01-GMT/17:33:58"`

**Comment by dustinxie** [comment]
i found out why: every time `make test`, there is 1 new account generated
