### ISSUE TITLE
[evm] Cover all EVM error code

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2734]
**Background**:
in our codebase, `func evmErrToErrStatusCode` only covers 7 errors (starting Bering height), while ethereum now returns more errors, see:
https://github.com/ethereum/go-ethereum/blob/master/core/vm/errors.go#L24-L38

**What would you like to be added**:
1. add a new hard-fork height
2. starting this height, cover all errors returned by ethereum
also need to add corresponding error code into proto definition

**Why is this needed**:
provide detailed/accurate error message, better error visibility

**Comment by raullenchai** [comment]
https://github.com/iotexproject/iotex-core/pull/2762

**Comment by raullenchai** [comment]
cc @ququzone @millken @uuz
