### ISSUE TITLE
I need prompt answers

### ISSUE THREAD

**Issue by alchemlstcoin** [iotexproject/iotex-core#2738]
I have published my extraction request, to add my Alchemist (MIST) token, it has been days since they have given me answers for the elaboration of my integration to ioTube, I have already done the steps to follow if you need tests of my ERC-20 token. I can give, but I need you to give me an answer since the process is very delayed.

Thank you and sorry for the inconvenience

**Comment by guo** [comment]
hello, commented on your PR here. https://github.com/iotexproject/ioTube/pull/27#issuecomment-881996232

Could you please contact me on telegram for a quick discussion?  @qevanguo.
