### ISSUE TITLE
bitcoin to iotex integration

### ISSUE THREAD

**Issue by gladiusfynance** [iotexproject/iotex-core#2740]
for the integration of bitcoin to iotex, why has not been added, or are there possibilities for the aggregation?

**Comment by raullenchai** [comment]
It is not clear why this is needed. If you want to have Bitcoin coming to iotex, pls use tube.iotex.io to bridge over wbtc

**Comment by gladiusfynance** [comment]
@raullenchai oh I understood you, I just had that doubt, thank you
