### ISSUE TITLE
use Address() API to simplify code

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2749]
**What would you like to be added**:
replace
```
pubKey := prvKey.PublicKey()
addr, _ := address.FromBytes(pubKey.Hash())
```
with
```
addr := pubKey.Address()
```
**Why is this needed**:
1. the latest `go-pkgs` added `Address()` API to directly output the Address object given the public key
2. more concise code

**Comment by ashishsnigam** [comment]
@dustinxie Please review it.
