### ISSUE TITLE
Investigate the base gas of IoTeX mainnet

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2753]
When invoking a simple contract on iotex mainnet, the gas cost can go below 21000, which is the base cost for ethereum (https://ethereum.stackexchange.com/questions/34674/where-does-the-number-21000-come-from-for-the-base-gas-consumption-in-ethereum). We need to understand why.

This matters b/c metamask (and other web3.js-compatible tools) consider a tx costs less than 21000 invalid, which causes confusion for users.

cc @guo @maswalker

**Comment by raullenchai** [comment]
https://github.com/iotexproject/iotex-core/blob/master/action/protocol/execution/evm/evm.go#L367 - hardcode to 10000

https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L121 hardcode to 21000

**Comment by raullenchai** [comment]
- this one has no impact on app.iott.io since each trustream tx costs > 21000
- this one has impact on accuracy 
-  we should fix this one after https://github.com/iotexproject/iotex-core/issues/1600

**Comment by Liuhaai** [comment]
The lowest estimated gas is hardcoded into 21000 in web3 server
```
	if estimatedGas < 21000 {
		estimatedGas = 21000
	}
```
