### ISSUE TITLE
Gas Estimation failed when calling selfdestruct() 

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2761]
### What did you do? If possible, provide a recipe for reproducing the error.

To resolve #2618, I deployed a simple contract on the chain for testing.

```solidity
pragma solidity >0.6.0;
contract Storage {
 address payable private owner;
 uint256 number;
 constructor() {
  owner = payable(msg.sender);
 }
 function store(uint256 num) public {
  number = num;
 }
 function retrieve() public view returns (uint256){
  return number;
 }
 
 function close() public { 
  selfdestruct(owner); 
 }
}

```

However, it failed to calling close() function which executes selfdestruct action of the contract.

### What did you expect to see?

smart contract executes selfdestruct() action, and it transfers its token to the address of the owner

### What did you see instead?

error message:

> Internal JSON-RPC error. { "code": 13, "message": "Out of gas" }

**Comment by Liuhaai** [comment]
Error was caused by a bug in Remix. Close this issue

**Comment by raullenchai** [comment]
@Liuhaai will do the validation

**Comment by Liuhaai** [comment]
This bug is caused by a wrong return state when gas is limited.
https://github.com/iotexproject/iotex-core/blob/master/action/protocol/execution/evm/evm.go#L294
