### ISSUE TITLE
[account] unify API to use address.Address

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2771]
**What would you like to be added**:
1. change
```
func LoadAccount(sr protocol.StateReader, addrHash hash.Hash160) (*state.Account, error)
``` 
to
```
func LoadAccount(sr protocol.StateReader, addr address.Address) (*state.Account, error)
```
2. rename the original `func LoadAccount()` to `func LoadAccountByHash160()` so `evmstatedbadaptor.go` can continue to use it

**Why is this needed**:
1. be consistent with `StoreAccount` to use `address.Address` as input
2. lots of code like
```
caller, err := accountutil.LoadAccount(sm, hash.BytesToHash160(caller.Bytes()))
```
can reduce to 
```
caller, err := accountutil.LoadAccount(sm, caller))
```

**Comment by ashishsnigam** [comment]
@dustinxie I will work on this issue.
