### ISSUE TITLE
build constraints exclude all Go files in [folder] when cross compiling for Linux in MacOs 

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#279]
I'm building the master branch on Mac OS 10.14 (go1.11.2).

I can build for Mac without any issue, but when I try to cross compile for my Linux server I get the following:

`$ GOOS=linux make build `
```
go build -o ./bin/server -v ./server
vendor/github.com/CoderZhi/go-ethereum/crypto/signature_cgo.go:27:2: build constraints exclude all Go files in /Users/simone/Source/Go/src/github.com/iotexproject/iotex-core/vendor/github.com/CoderZhi/go-ethereum/crypto/secp256k1
make: *** [build] Error 1
```

**Comment by FishMeat** [comment]
what's your go version? 
it requires go 1.10.

**Comment by simonerom** [comment]
> what's your go version?
> it requires go 1.10.

I know that, I was actually using go 1.10.3 but I got a different error that came out to be a bug in the go release (I'm sorry I didn't take note of the error), therefore I upgraded to the latest **go 1.11.2** which I'm now using for the build: as expected the previous error was gone, but now I'm getting this "build constraints [...]" error.

**Comment by simonerom** [comment]
Still can't solve this issue.
Please notice that this is only happening when cross compiling, i.e. setting GOOS env variable different from "darwin".

go version: _go1.11.2 darwin/amd64_
darwin version: 18.2.0_

**Comment by lizhefeng** [comment]
Could you please try go 1.10.4? If there still exists an error, please report to us.

**Comment by simonerom** [comment]
> Could you please try go 1.10.4? If there still exists an error, please report to us.

Yes I did already try - same error.

**Comment by raullenchai** [comment]
which distribution/version of linux is this @simonerom? There could be incompatibility issues that's why we recommend running the docker image.

**Comment by simonerom** [comment]
> which distribution/version of linux is this @simonerom? There could be incompatibility issues that's why we recommend running the docker image.

Hi Raullen,
Please notice that I was cross-compiling for linux on my Mac (darwin version: _18.2.0_) i.e. target=ARM and Darwin as the host OS.

Anyway that was a long time ago, I can't remember exactly why I was cross-compiling from source, maybe because I did try to build iotex-core for ARM first on a Mac, and I got that error, so I tried again but this time with linux as a target and got the same error again, that's why I reported it (so the error appeared when cross compiling with target =  anything and Darwin as host OS).

Eventually, I gave up with this task because, after moving to ubuntu (i.e. cross compiling with target=ARM an Ubuntu as a host) the error disappeared, but I discovered that I could not build ARM binaries yet (until you provide the crypto libs for ARM as well). 

Honestly, I've not tried with recent releases: I will do it and let you know if this is still happening.

**Comment by raullenchai** [comment]
@simonerom I am close this stale issue. Pls reopen it if it still exists and is important to you.
