### ISSUE TITLE
Integration Workflow Queued forever

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2795]
Look at here https://github.com/iotexproject/iotex-core/pull/2790

<img width="737" alt="Screen Shot 2021-09-15 at 2 55 49 PM" src="https://user-images.githubusercontent.com/989846/133515188-b5bba098-94e7-4aa5-b050-917e56533953.png">

**Comment by raullenchai** [comment]
what does it do and why it stuck?

**Comment by xianhuawei** [comment]
mybe github runner delete ，i'm can‘t access to https://github.com/iotexproject/iotex-core/settings/actions/runners

**Comment by xianhuawei** [comment]
![image](https://user-images.githubusercontent.com/3870801/134275275-2c918da8-ade1-4366-bf34-a86d862e2a12.png)
github runner is ok
