### ISSUE TITLE
error when sending unicast message: protocol not supported

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2797]
![Screen Shot 2021-09-16 at 10 24 16 AM](https://user-images.githubusercontent.com/989846/133657368-eefeee6d-4e53-4922-8632-27a4f484a8d5.png)

Many such err has been observed on testnet. Pls diagnoze.

**Comment by dayuanc** [comment]
We can't parse binary multitudes unless we know all the necessary protocols because they don't have protocol definitions.

We can, however, parse a prefix. As a result, I'd want to propose a unique "unknown" protocol that only accepts a single multi-base encoding argument.

@raullenchai @Liuhaai

**Comment by Liuhaai** [comment]
duplicated with the issue #2729
