### ISSUE TITLE
"not exist in trie"

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2798]
![Screen Shot 2021-09-16 at 10 29 19 AM](https://user-images.githubusercontent.com/989846/133657977-b43b883a-e4fe-4031-bf72-9709e2cd348c.png)

Saw this err happens often in prod. Pls diagnose.

**Comment by raullenchai** [comment]
Is this the same as loadroot err? @CoderZhi

**Comment by dustinxie** [comment]
i think this is due to the LoadRoot error, fixed in https://github.com/iotexproject/iotex-core/commit/c07559c142b33b75615dd1c3549d76bacc7322a9
