### ISSUE TITLE
rebuild index is 15% slower in docker vs. native go

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2799]
### What version of iotex-core are you using (`ioctl version`)?
iotex/iotex-core:v1.4.0-rc3

### What operating system and processor architecture are you using?
Linux/Debian

### What did you do? If possible, provide a recipe for reproducing the error.
running full-sync test (by deleting trie.db, and let node rebuild trie.db using existing chain.db, this is faster than download all block from scratch)
1. start the node as a native go process (download code, go build, `./bin/server xxx`)
2. start the node using docker (`docker run xxx`)

### What did you expect to see?
roughly the same performance

### What did you see instead?
it took about ~25s to rebuild 5000 blocks on native go
```
"ts":1631816118.393805,"caller":"blockdao/blockdao.go:190","msg":"indexer is catching up.","ioAddr":"io14xpglc8xewru5zz9wv2e4nqjztxy7r4h4dv2vr","indexer":0,"height":9650000}
"ts":1631816142.900227,"caller":"blockdao/blockdao.go:190","msg":"indexer is catching up.","ioAddr":"io14xpglc8xewru5zz9wv2e4nqjztxy7r4h4dv2vr","indexer":0,"height":9655000}
```
while it took about ~270s on docker
```
"ts":1631815076.9819398,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1ede56ew4xdnjrhqremw797x0yem5smtnhw0cqv","indexer":0,"height":2880000}
"ts":1631815351.0380917,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1ede56ew4xdnjrhqremw797x0yem5smtnhw0cqv","indexer":0,"height":2885000}
```

### Correction
in original testing, DB write load on 2 heights `2880000 vs 9650000` are different (at 2880000 there are lots of `Store native buckets to election db` writes), so it is NOT a fair comparison.
so re-run the test at same height `2050000~2080000` shows that:
1. `docker` is 15% slower than `native go`
2.  with `cached` option, the running time is almost the same (`265 vs 273 seconds`) for this rebuilding index case

`native go`: 238 seconds to build 5000 blocks
{"level":"info","ts":1632264670.9210913,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io174jjgxfxlg872jm5xafjgjg48leahg7xnxts80","indexer":0,"height":2050000}
{"level":"info","ts":1632266102.7022457,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io174jjgxfxlg872jm5xafjgjg48leahg7xnxts80","indexer":0,"height":2080000}

`docker`: 273 seconds to build 5000 blocks
{"level":"info","ts":1632266433.5214458,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1ekws899t9cz2xgk69lx8e9s3eh0pg2yf6pa0hf","indexer":0,"height":2050000}
{"level":"info","ts":1632268075.369739,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1ekws899t9cz2xgk69lx8e9s3eh0pg2yf6pa0hf","indexer":0,"height":2080000}

`docker` with `cached` option: 265 seconds to build 5000 blocks
{"level":"info","ts":1632268730.3511808,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1kk589ra6upmrw2p5h8vcrerfsnnpn6ntzwal07","indexer":0,"height":2050000}
{"level":"info","ts":1632270325.424212,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1kk589ra6upmrw2p5h8vcrerfsnnpn6ntzwal07","indexer":0,"height":2080000}

**Comment by dustinxie** [comment]
rebuild index is basically the following:
```
for i++ {
    blk := dao.GetBlockByHeight(i)
    blk.Receipts = dao.GetReceipts(i)
    indexer.PutBlock(blk)
    if i%5000 == 0 { 
        log("indexer is catching up.", zap.Uint64("height", i))
    }
}
```

**Comment by dustinxie** [comment]
how to run docker: https://github.com/iotexproject/iotex-bootstrap

**Comment by dayuanc** [comment]
I think there are two ways we can do to improve the rebuild index: 
       1. reface the logic to get block by height to reduce the nest loops around indexer catching up.
       2. use cached parameter to pre-load the host file into docker container. 
              Example:
```
       docker run -d --restart on-failure --name iotex \
        -p 4689:4689 \
        -p 8080:8080 \
        -v=$IOTEX_HOME/data:/var/data:cached \
        -v=$IOTEX_HOME/log:/var/log:cached \
        -v=$IOTEX_HOME/etc/config.yaml:/etc/iotex/config_override.yaml:cached \
        -v=$IOTEX_HOME/etc/genesis.yaml:/etc/iotex/genesis.yaml:cached \
        iotex/iotex-core:v1.3.0 \
        iotex-server \
        -config-path=/etc/iotex/config_override.yaml \
        -genesis-path=/etc/iotex/genesis.yaml
```

**Comment by dustinxie** [comment]
did more testing
1. starting a node with empty state db (`height = 0`), the rebuilding is pretty fast at beginning, at about 22s for every 5000 blocks
```
{"level":"info","ts":1632244574.741659,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":45000}
{"level":"info","ts":1632245493.045841,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":245000}
{"level":"info","ts":1632245933.0378928,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":345000}
{"level":"info","ts":1632246387.710967,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":445000}
{"level":"info","ts":1632246843.1426394,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":545000}
{"level":"info","ts":1632247344.2740138,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":645000}
{"level":"info","ts":1632247854.4165614,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1w2lqewhekswps0ds2ljs6kh6uxjwzt65u3yjls","indexer":0,"height":745000}
```
2. when height reaches about 2M, it slows down to ~250 seconds for every 5000 blocks
```
{"level":"info","ts":1632257859.7121584,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io16plyg3jhf29erfqwalkmdhrzcnw3wcjqgfed0w","indexer":0,"height":1975000}
{"level":"info","ts":1632258081.0959778,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io16plyg3jhf29erfqwalkmdhrzcnw3wcjqgfed0w","indexer":0,"height":1980000}
{"level":"info","ts":1632258351.2618527,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io16plyg3jhf29erfqwalkmdhrzcnw3wcjqgfed0w","indexer":0,"height":1985000}
```
3. stop and restart the node, this time with new command with `cached` option. The rebuild time does not seem to improve, it still takes about ~270 seconds for every 5000 blocks
```
{"level":"info","ts":1632258621.6215086,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1nvnmdydcezl9w9nfe06dd22xq8nhaw3zsmx2rz","indexer":0,"height":1990000}
{"level":"info","ts":1632258856.109528,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1nvnmdydcezl9w9nfe06dd22xq8nhaw3zsmx2rz","indexer":0,"height":1995000}
{"level":"info","ts":1632259123.9622376,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1nvnmdydcezl9w9nfe06dd22xq8nhaw3zsmx2rz","indexer":0,"height":2000000}
{"level":"info","ts":1632259397.7329662,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1nvnmdydcezl9w9nfe06dd22xq8nhaw3zsmx2rz","indexer":0,"height":2005000}
{"level":"info","ts":1632259666.8781445,"caller":"blockdao/blockdao.go:180","msg":"indexer is catching up.","ioAddr":"io1nvnmdydcezl9w9nfe06dd22xq8nhaw3zsmx2rz","indexer":0,"height":2010000}
```

**Comment by dayuanc** [comment]
Is that running on GCP instances? I tried on my laptop and almost the same.

**Comment by CoderZhi** [comment]
"cached" may only work on Mac

**Comment by dustinxie** [comment]
yes, running on GCP instance, see "Correction" in original post

**Comment by dayuanc** [comment]
what kind of instance are you using? Could you share the config? I am wondering if we use more powerful instance it will definitionally improve the performance, and another way to think about is breakdown the current `path` file like: https://raw.githubusercontent.com/iotexproject/iotex-bootstrap/v1.3.0/genesis_mainnet.yaml. But it looks like very expensive to implement.

**Comment by dustinxie** [comment]
Machine type
e2-medium (2 vCPUs, 4 GB memory)

CPU platform
Intel Broadwell

100GB | SSD persistent disk | Google managed

**Comment by dayuanc** [comment]
after sync up with @dustinxie  since based on the latest test docker is only 15% slower than native go, it doesn't sound critical now. So we will close this task.  CC: @raullenchai @CoderZhi
