### ISSUE TITLE
fix Failed to get committed state error.

### ISSUE THREAD

**Issue by dayuanc** [iotexproject/iotex-core#2811]
### What version of iotex-core are you using (`ioctl version`)?

v1.3.0

### What operating system and processor architecture are you using?

Kibana

### What did you do? If possible, provide a recipe for reproducing the error.

Go kibana and select discover desk-board. field logs by error level, there are a lot of `Failed to get committed state.` error.

### What did you expect to see?
So 90% of latest 500 logs are `Failed to get committed state.` we should figure out how to reduce these kind of errors.

**Comment by dustinxie** [comment]
this has already been fixed by https://github.com/iotexproject/iotex-core/commit/5a68f1c5edcfcd5e28252aea42e0f154a088094d
