### ISSUE TITLE
Improve the test coverage of action/signedaction.go

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#2815]
**What would you like to be added**:
Add unit tests to cover the functions in https://codecov.io/gh/iotexproject/iotex-core/src/1bb35e310f4546147b26d7a28ef3927b9714b99b/action/signedaction.go

**Why is this needed**:
Improve coverage and enhance code security

**Comment by dayuanc** [comment]
https://github.com/iotexproject/iotex-core/pull/2824
