### ISSUE TITLE
Failed to request blocks

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#2817]
### What version of iotex-core are you using (`ioctl version`)?
1.4.0

### What operating system and processor architecture are you using?
Running version 1.4.0 Docker container on Centos 8

### What did you do? If possible, provide a recipe for reproducing the error.
Stopped 1.3.0, updated to 1.4.0 , started 1.4.0

### What did you expect to see?
No error 

### What did you see instead?
```
{"level":"error","ts":1632819836.161043,"caller":"chainservice/chainservice.go:402","msg":"failed to request blocks","ioAddr":"io10reczcaelglh5xmkay65h9vw3e5dp82e8vw0rz","error":"error when sending unicast message: protocol not supported","errorVerbose":"protocol not supported\nerror when sending unicast message\ngithub.com/iotexproject/iotex-core/p2p.(*Agent).UnicastOutbound\n\t/go/apps/iotex-core/p2p/agent.go:379\ngithub.com/iotexproject/iotex-core/chainservice.New.func7\n\t/go/apps/iotex-core/chainservice/chainservice.go:397\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).sync\n\t/go/apps/iotex-core/blocksync/blocksync.go:148\ngithub.com/iotexproject/iotex-core/pkg/routine.(*RecurringTask).Start.func1\n\t/go/apps/iotex-core/pkg/routine/recurringtask.go:60\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","peer":"12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5","start":13451098,"end":13451098}
```

After a couple failures similar to this one the node is syncing so it does not appear to be stopping it from maintaining block sync

**Comment by Liuhaai** [comment]
@jerkyrs Thx for feedback. This issue has been filed [here](https://github.com/iotexproject/iotex-core/issues/2797). Could you share your issue there, and this duplicated issue can be closed.
