### ISSUE TITLE
error:invalid opcode: opcode 0xfe not defined

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2835]
https://tracing.iotex.me/search?end=1634061236898000&limit=20&lookback=2d&maxDuration&minDuration=1s&service=mainnet-server-tracer&start=1633888436898000

**Comment by dustinxie** [comment]
{"level":"warn","ts":1636578568.400295,"caller":"evm/evm.go:343","msg":"evm internal error","ioAddr":"io10d4ndt0vzy642v0g2yyntzhtn9jxeq2mdmkglx","error":"invalid opcode: opcode 0xfe not defined","contract":"da257cbe968202dea212bbb65ab49f174da58b9d","calldata":"1e3dd18b00000000000000000000000000000000000000000000000000000000000000fa"}

contract = io1mgjhe05ksgpdagsjhwm94dylzax6tzuaugklfx (MimoFactory), calling function `allPairs(uint256)`

it is b/c the input `0xfa` is out of range (max is 246 = 0xf6), while the contract source code does not check out of range, so it continues execution and some unexpected data is interpreted as opcode 0xfe

running the tx on Ethereum returns the same error

**Comment by dustinxie** [comment]
this is error returned from Ethereum (according to Leo)
<img width="334" alt="0xfe" src="https://user-images.githubusercontent.com/12551272/142081695-299775ee-3708-4b00-8c48-b8ef8868c946.png">
