### ISSUE TITLE
[action] replace `require.True(strings.Contains(a, b))` pattern with `require.Contains(a, b)`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2881]
**What would you like to be added**:

**Why is this needed**:
The test checking code can be simplified

**Comment by himanshu007-creator** [comment]
Hey, i would like to work on this issue

**Comment by raullenchai** [comment]
> Hey, i would like to work on this issue

Feel free to make a pull request for it!
