### ISSUE TITLE
Question: What is the data flow architecture of IoT data?

### ISSUE THREAD

**Issue by sunphy** [iotexproject/iotex-core#2899]
I've been digging IoTex for a while and it's a great project btw. But I'm just wondering what is the data flow architecture of IoT data? Because IoT data is very large and time series related, and on the other hand the blockchain space is very limited due to decentralized mechanism.   
So What is the solution by IoTex, is the IoT metrics data (realtime GPS location, temperature, air quality, etc) stored on-chain or off-chain? If the answer is off-chain, then how to make sure the data is integrity?
Thank you IoTex team.

**Comment by Liuhaai** [comment]
@sunphy the `iotex-core` project focuses on the blockchain part of IoTeX. Pls follow our release of [IoTeX 2.0](https://machinefi.com/), the details will be revealed there.
This issue can be closed
