### ISSUE TITLE
[bug] the nonce of test account is unmatchable with its action number

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2904]
### What did you do? If possible, provide a recipe for reproducing the error.
Strange info of the test account `io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0` on testnet
 > ioctl account nonce io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0 --endpoint=api.testnet.iotex.one:443
io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0:
Nonce: 0, Pending Nonce: 1
 > ioctl account actions io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0 --endpoint=api.testnet.iotex.one:443
Total: 14
Error: start = 18446744073709551615 >= total = 14: invalid input

### What did you expect to see?

#Nonce should be reasonable

### What did you see instead?
nonce is 0

**Comment by dustinxie** [comment]
total action is different from nonce

nonce is the number of actions this address creates as sender

total action is number of action this address was involved (as sender or receiver), in this case, there are 14 actions where `io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0` is transfer recipient

https://testnet.iotexscout.io/address/io15u5256x6eap648p2cmwcc62v3elwl4fn6ymtm0
