### ISSUE TITLE
tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by lzwgiter** [iotexproject/iotex-core#2917]
### What version of iotex-core are you using (`ioctl version`)?
packageVersion:"v1.2.1-111-gdc9db3e7"

### What operating system and processor architecture are you using?
Ubuntu 20.04, x86

### What did you do? If possible, provide a recipe for reproducing the error.
I'm trying to build a local iotex testnet for studying&developing, so after git clone & make ioctl & make run, I start a stand-alone server(I change the address in ./config/standalone-genesis.yaml to the address which i generated by `ioctl account createadd xxx`) and try to connect to the server(port 14014), however i could not connect to the server.(error in `ioctl bc info`, `ioctl account balance xxx`).

### What did you expect to see?
the blockchain info of my local testnet.

### What did you see instead?
output: **Error: connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"**

**Comment by dustinxie** [comment]
for connecting to local server 14014 port, use non-TLS connection:
```
ioctl bc info --endpoint=12.34.56.78:14014 --insecure
```

also, it's recommended to start the server using latest released version v1.6.1

**Comment by lzwgiter** [comment]
> for connecting to local server 14014 port, use non-TLS connection:
> 
> ```
> ioctl bc info --endpoint=12.34.56.78:14014 --insecure
> ```
> 
> also, it's recommended to start the server using latest released version v1.6.1

Thanks a lot, problem solved.
