### ISSUE TITLE
[db] method should return error when db hasn't started

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2928]
### What did you do? If possible, provide a recipe for reproducing the error.
https://github.com/iotexproject/iotex-core/blob/master/db/db_bolt.go#L80
b.db is nil when db hasn't started

### What did you expect to see?
when b.db is nil, an error should be directly returned
```
if b.db == nil {
return nil, errors.New("db hasn't started")
}
b.db.xxx
```

### What did you see instead?
null pointer panic

**Comment by pocockn** [comment]
@Liuhaai  I've created a branch for this but I'm unable to push it due to

```
$ git push --set-upstream origin task/return-err-db

ERROR: Permission to iotexproject/iotex-core.git denied to pocockn.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
