### ISSUE TITLE
move `IoAddrToEvmAddr` from ioctl/util to pkg/util

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2934]
**What would you like to be added**:
The code in https://github.com/iotexproject/iotex-core/blob/master/ioctl/util/util.go#L109-L116 could be moved to ./pkg/util/addrutil/addrutil.go, 
And return proper error when conversion doesn't work

**Why is this needed**:

**Comment by pocockn** [comment]
@Liuhaai have you done this one already?

**Comment by Liuhaai** [comment]
> @Liuhaai have you done this one already?

No. Feel free to contribute if you want

**Comment by pocockn** [comment]
> > @Liuhaai have you done this one already?
> 
> No. Feel free to contribute if you want

Great, will look at this tonight.
