### ISSUE TITLE
[ioctl] build `account info` command line into new ioctl

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2936]
The new ioctl (./ioctl/newcmd) is a refactored version of the old ioctl(./ioctl/cmd). It includes two major changes:
- The [Client interface](https://github.com/iotexproject/iotex-core/blob/master/ioctl/client.go) is passed when constructing the Cobra command.
- Unit tests are added for each command.

The code is a draft. The code of old ioctl can be used for reference.

**What would you like to be added**:
add `accountinfo.go` and `accountinfo_test.go` in `./ioctl/newcmd/account`. 
**Code for reference**:
https://github.com/iotexproject/iotex-core/blob/master/ioctl/cmd/account/accountinfo.go

**Comment by LuckyPigeon** [comment]
@Liuhaai 
Can I have this issue assigned?

**Comment by Liuhaai** [comment]
> @Liuhaai
> Can I take this issue?

Sure

**Comment by LuckyPigeon** [comment]
Thanks!
