### ISSUE TITLE
[style] prefix unexported globals with '_'

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#2946]
https://github.com/uber-go/guide/blob/master/style.md#prefix-unexported-globals-with-_

### Prefix Unexported Globals with _

Prefix unexported top-level `var`s and `const`s with `_` to make it clear when
they are used that they are global symbols.

Exception: Unexported error values, which should be prefixed with `err`.

Rationale: Top-level variables and constants have a package scope. Using a
generic name makes it easy to accidentally use the wrong value in a different
file.

<table>
<thead><tr><th>Bad</th><th>Good</th></tr></thead>
<tbody>
<tr><td>

```go
// foo.go

const (
  defaultPort = 8080
  defaultUser = "user"
)

// bar.go

func Bar() {
  defaultPort := 9090
  ...
  fmt.Println("Default port", defaultPort)

  // We will not see a compile error if the first line of
  // Bar() is deleted.
}
```

</td><td>

```go
// foo.go

const (
  _defaultPort = 8080
  _defaultUser = "user"
)
```

</td></tr>
</tbody></table>

**Exception**: Unexported error values may use the prefix `err` without the underscore.

**Comment by LuckyPigeon** [comment]
I can take this.

**Comment by LuckyPigeon** [comment]
@Liuhaai 
Does `tools` folder also needs to add `_` prefix?

**Comment by Liuhaai** [comment]
> @Liuhaai Does `tools/` also needs to add `_` prefix?

you could skip this folder
