### ISSUE TITLE
fix make mockgen

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#2980]
**What would you like to be added**:
running `make mockgen` produces:
imported package collision: "backoff" imported twice
**Why is this needed**:
`make mockgen` can work correctly

**Comment by dustinxie** [comment]
it should be caused by the order of entries in /misc/scripts/mockgen.sh

**Comment by huof6829** [comment]
i run 'make mockgen'  in macos , and no errors.

**Comment by dustinxie** [comment]
yeah, it's due to mock version, after I upgrade to v1.6.0, it works fine
