### ISSUE TITLE
[ioctl] build `account verify` command line into new ioctl

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3003]
The new ioctl (./ioctl/newcmd) is a refactored version of the old ioctl(./ioctl/cmd). It includes two major changes:
- The [client interface](https://github.com/iotexproject/iotex-core/blob/master/ioctl/client.go) is passed when constructing the Cobra command.
- Unit tests are to be added for each command.

The newcmd code currently is a draft. The code of old ioctl can be used for reference.

### What would you like to be added
add `accountverify.go` and `accountverify_test.go` in `./ioctl/newcmd/account`. 
**Code for reference**:
https://github.com/iotexproject/iotex-core/blob/master/ioctl/cmd/account/accountverify.go

**Comment by LuckyPigeon** [comment]
I'm doing [accountinfo.go](https://github.com/iotexproject/iotex-core/issues/2936) currently, I can do this, too!
