### ISSUE TITLE
[api] Integrate `web3server_test.go` and `grpcserver_test.go` into `coreservice_test.go`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3018]
**What would you like to be added**:
 - Integrate `web3server_test.go` and `grpcserver_test.go` into `coreservice_test.go`
  - Create an interface in `coreservice.go`
 - Create new tests for grpc and web3 using mocked coreservice
 
**Why is this needed**:
 - `web3server_test.go` and `grpcserver_test.go` share many silimar tests in the code
 - https://github.com/iotexproject/iotex-core/issues/2696

**Comment by CoderZhi** [comment]
duplicate with #2696
