### ISSUE TITLE
[blocksync] use `struct{}` instead of `bool` in hashset

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3019]
**What would you like to be added**:
https://github.com/iotexproject/iotex-core/blob/master/blocksync/uniqueue.go
`map[hash.Hash256]bool{}` could be replaced by `map[hash.Hash256]struct{}`
**Why is this needed**:

**Comment by pramod74** [comment]
Hi @Liuhaai,

Can you please assign me this issue?

**Comment by Liuhaai** [comment]
submit a pr if u want

**Comment by pramod74** [comment]
Thanks. I have submitted a PR (# 3022). Kindly review.
