### ISSUE TITLE
[api] improve log query with goroutine

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3047]
**What would you like to be added**:
Doing logsInBlock() in each block could be done in parallel with goroutines.

**Why is this needed**:

Querying logs from mutiple blocks in `LogsInRange()` could be optimized with goroutine.
https://github.com/iotexproject/iotex-core/blob/da077c8a23a299cc4030368b8643f4382e92716f/api/coreservice.go#L1239

**Comment by LuckyPigeon** [comment]
So, these lines should by update by goroutines, right?

**Comment by Liuhaai** [comment]
> So, these lines should by update by goroutines, right?
> 
> https://github.com/iotexproject/iotex-core/blob/da077c8a23a299cc4030368b8643f4382e92716f/api/coreservice.go#L1258-L1270

yes
