### ISSUE TITLE
[api] add GetBlockHeightByBlockHash into `coreService.go`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3048]
**What would you like to be added**:
Add a `GetBlockHeightByBlockHash` public method in `coreService.go`
The block height could be accessed through blockDao 
```
height, err := core.dao.GetBlockHeight(hash)
```
**Why is this needed**:
replace `dao.GetBlockHeight()` in `grpcserver.go` with func in `coreService.go`
https://github.com/iotexproject/iotex-core/blob/da077c8a23a299cc4030368b8643f4382e92716f/api/grpcserver.go#L364

**Comment by LuckyPigeon** [comment]
This issue is solved right? Since it's already refactored by this line 
https://github.com/iotexproject/iotex-core/blob/faf3c97bee147662339a9fd3a3055a38052810bf/api/grpcserver.go#L402

**Comment by Liuhaai** [comment]
thx for the feedback
