### ISSUE TITLE
[test] Clean the temp file after testing

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3060]
**What would you like to be added**:
use `defer testutil.CleanupPathV2()` to clean the file

**Why is this needed**:
Some temp files aren't cleaned after it is created by `testutil.PathOfTempFile()` in the test

**Comment by DiptoChakrabarty** [comment]
I want to work on this can you please assign me.

Also should CleanPathV2 be used instead of CleanPath because this issue #3059 states to remove CleanPathV2 in the description

**Comment by DiptoChakrabarty** [comment]
@Liuhaai we can close this right
