### ISSUE TITLE
txIndex is 0 in the api test

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3068]
It might be related to hardfork height in the test

**Comment by dustinxie** [comment]
yes, it is a known issue. txIndex is going to have valid values from v1.7.0, see https://github.com/iotexproject/iotex-core/commit/892dee9bcf9c7e93efdca1b6c4ade0df21be0e4d

**Comment by dustinxie** [comment]
to verify the txIndex has been set, specify the hard-fork height, see https://github.com/iotexproject/iotex-core/commit/892dee9bcf9c7e93efdca1b6c4ade0df21be0e4d#diff-376031ecf84904d1ad817660ba4a12fcf9143faed75224a178fdad3ebcefd63eR1437 (here set to 5)

then for block with height >= 5, it can be verified that the txIndex/logIndex is correctly set, see https://github.com/iotexproject/iotex-core/commit/892dee9bcf9c7e93efdca1b6c4ade0df21be0e4d#diff-376031ecf84904d1ad817660ba4a12fcf9143faed75224a178fdad3ebcefd63eR1356-R1359
