### ISSUE TITLE
[test] move `ClassifyActions()` to test

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3069]
**What would you like to be added**:

**Why is this needed**:
`func ClassifyActions()` is only used in the test, so it can be moved out from `action.go`

**Comment by RishiKumarRay** [comment]
to which file do we need to move?

**Comment by Liuhaai** [comment]
> ClassifyActions()

IMO, moving the func to both `indexer_test.go` and `integrity_test.go` is ok. And `TestActionClassifyActions()` can be removed
