### ISSUE TITLE
[api] better cache invalidation

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3082]
**What would you like to be added**:
currently, upon receiving a new block, the cache used in `core.ReadContract()` is simply invalidated. However, this is not necessary. A better strategy is to only invalidate cache of those contracts that are called in the new block.

**Why is this needed**:
1. increase the cache performance
2. avoid unnecessary data invalidation

**Comment by Liuhaai** [comment]
states might implicitly change in each block
