### ISSUE TITLE
[bloomFilter] remove func `delete()` in `bloomfilterindexer.go`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3122]
**What would you like to be added**:

**Why is this needed**:
[func `delete()`](https://github.com/iotexproject/iotex-core/blob/master/blockindex/bloomfilterindexer.go#L243) could be integrated into [func DeleteTipBlock()](https://github.com/iotexproject/iotex-core/blob/master/blockindex/bloomfilterindexer.go#L168)

**Comment by DiptoChakrabarty** [comment]
Hi @Liuhaai can you assign me this
