### ISSUE TITLE
Figure out a hard code parameter

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#3137]
Figure out why `iotex-core` is hard coded in https://github.com/iotexproject/iotex-core/blame/aec2fa165f5e8f996cf0b96e9f383e8dcebb6937/pkg/util/fileutil/fileutil.go#L33

**Comment by LuckyPigeon** [comment]
Maybe search where the most recent iotex-core-ish parent folder is
A parent folder pattern like `iotex-core-[a-zA-Z0-0]+`
This kind of parent folder could exists if you pull a specific commit.

**Comment by Liuhaai** [comment]
@CoderZhi 
> returns the absolute path of a file in blockchain directory

The purpose of this func is strange. B/c it isn't called in the codebase. IMO, this func can be removed.
