### ISSUE TITLE
make test error in ioctl/newcmd/account

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3144]
### What version of iotex-core are you using (`ioctl version`)?
master

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
`make test`

### What did you expect to see?
test pass

### What did you see instead?
```
--- FAIL: TestSign (146.53s)
    account_test.go:77: 
        	Error Trace:	account_test.go:77
        	Error:      	Received unexpected error:
        	            	open /var/folders/_y/1yg9dv650f38jfl5z12kbz_40000gn/T/ksTest/UTC--2022-03-04T01-16-27.244304000Z--371c731612f748245f24d0832d7e14dcf2b06844: no such file or directory
        	Test:       	TestSign
    panic.go:661: missing call(s) to *mock_ioctlclient.MockClient.NewKeyStore() /Users/dustin/iotexproject/iotex-core/ioctl/newcmd/account/account_test.go:63
    panic.go:661: missing call(s) to *mock_ioctlclient.MockClient.IsCryptoSm2() /Users/dustin/iotexproject/iotex-core/ioctl/newcmd/account/account_test.go:64
    panic.go:661: aborting test due to missing call(s)
FAIL
FAIL	github.com/iotexproject/iotex-core/ioctl/newcmd/account	528.418s
```
however, if I go into the folder to run tests it can pass, like below
1. `cd ioctl/newcmd/account`
2. `go test ./...`
i got test pass

**Comment by huof6829** [comment]
caused by using global var . fix in https://github.com/iotexproject/iotex-core/pull/3133
