### ISSUE TITLE
Memory usage monitor/control for mptrie

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#3204]
**What would you like to be added**:
Replace the branch nodes or extension nodes, which have not been visited for a long time, with .

**Why is this needed**:
The size of mp trie will keep increasing with the new implementation, with current implementation, the memory size will be as large as 32G. To limit the memory usage, we need a way to replace some nodes with their corresponding hash nodes periodically.

**Comment by raullenchai** [comment]
Add flag to enable this one on a running node, default to be false.
