### ISSUE TITLE
[api] Remove `ReceiptByAction()` in `coreservice.go`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3208]
**What would you like to be added**:

**Why is this needed**:
`ReceiptByAction()` is only used in `GetReceiptByAction()` in `grpcserver.go`

**Comment by LuckyPigeon** [comment]
`ReceiptByAction` contains some private variables, which can't be removed in `coreservice.go`, since the private variables has been used by other functions.

see
https://github.com/iotexproject/iotex-core/blob/5a1fe5d978d45b07446e3750a177f5fba6876e96/api/coreservice.go#L716

**Comment by Liuhaai** [comment]
> `ReceiptByAction` contains some private variables (`hasActionIndex` & `indexer`), which can't be removed in `coreservice.go`, since the private variables has been used by other functions.
> 
> see
> 
> https://github.com/iotexproject/iotex-core/blob/5a1fe5d978d45b07446e3750a177f5fba6876e96/api/coreservice.go#L716

ReceiptByActionHash() has done similar check

**Comment by LuckyPigeon** [comment]
But `getBlockHashByActionHash` is a private function used in `ReciptByAction`, which hasn't defined in `CoreService` interface.
https://github.com/iotexproject/iotex-core/blob/5a1fe5d978d45b07446e3750a177f5fba6876e96/api/coreservice.go#L445

**Comment by Liuhaai** [comment]
> But `getBlockHashByActionHash` is a private function used in `ReciptByAction`, which hasn't defined in `CoreService` interface.
> 
> https://github.com/iotexproject/iotex-core/blob/5a1fe5d978d45b07446e3750a177f5fba6876e96/api/coreservice.go#L445
> 
> This makes `ReceiptByAction` unable to remove.

An new public method could be created in coreservice
