### ISSUE TITLE
eth_synching not implemented

### ISSUE THREAD

**Issue by jrynkiew** [iotexproject/iotex-core#3215]
Please add eth_syncing endpoint support to native web3 API server.

Currently this endpoint always returns "false" `{"jsonrpc":"2.0","id":1,"result":false}` since in the code the endpoint is hardcoded to do so `func (svr *Web3Server) isSyncing() (interface{}, error) {
	return false, nil
}
`

Can you please implement this endpoint soon? Node operators rely heavily on this endpoint to check if the node is running correctly when syncing from height 0

**Comment by Liuhaai** [comment]
thx for feedfack. We will solve this issue next week
