### ISSUE TITLE
Investigate the performance of `accountutil.AccountState()`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3341]
**What would you like to be added**:

**Why is this needed**:

**Comment by millken** [comment]
I added some tracer events to the code, and found a problem,spent a lot of time on the lock `sdb.mutex`
<img width="1838" alt="微信图片_20220428144202" src="https://user-images.githubusercontent.com/176581/165692852-96985a51-dcb1-4718-810e-59763d4997f9.png">
https://github.com/iotexproject/iotex-core/blob/5eb9a8339895094a5eafed0e02316fa35b2fbde1/state/factory/statedb.go#L451-L463
