### ISSUE TITLE
test in ioctl/newcmd/account takes 9 minutes

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3382]
**What would you like to be added**:
as title, find the root-cause why this happens.

**Why is this needed**:
speed up `make test`

**Comment by dustinxie** [comment]
<img width="520" alt="Screen Shot 2022-05-10 at 3 14 01 PM" src="https://user-images.githubusercontent.com/12551272/167738924-b9b7d880-5048-4bda-a909-21f7ca8ad6db.png">

**Comment by huof6829** [comment]
The main cost time is used in  `keystore.NewKeyStore()` ,  cost about 30s per time . I find about 15 times called in ioctl/newcmd/account/*_test.go. I will combine them to one time.
