### ISSUE TITLE
error handling in pkg/util/httputil/httputil.go

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#3430]
The errors of `SetKeepAlive` and `SetKeepAlivePeriod` are not handled.

### How important you think this is for IoTeX
- [] must have
- [] should have
- [] nice to have

### Additional information
Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)

**Comment by Adminsupportt** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
