### ISSUE TITLE
[action] use SenderAddress() to replace SrcPubkey().Address()

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3440]
### Description of the code refactor
commit https://github.com/iotexproject/iotex-core/commit/a22243101524bcf848312a573ed7380b4610ffae added `SenderAddress()` API, use it to replace `SrcPubkey().Address()` in the codebase

### Why is this needed
- [] better/less memory usage
- [x] reduce running time
- [x] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (like reduce complexity)
- [] reduce/decouple dependencies between code modules
- [] increase test coverage
- [] better code readability

**Comment by Adminsupportt** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
