### ISSUE TITLE
Start blockchain and related services before accepting external requests

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#3459]
### Description
External requests, e.g., block sync, action broadcast, and etc, should not be turned on before the core blockchain services are started.

### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [] Phase 1 description (PR number)
- [] Phase 2 description (PR number)
- [] Phase 3 description (PR number)

### Affected modules
- [] action
- [] actpool
- [] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [] ioctl
- [] p2p
- [] server
- [] state
- [] tools

**Comment by millken** [comment]
**iotex server `Start` data flow** 

![HDeF6hO1ER](https://user-images.githubusercontent.com/176581/190942550-2ccd2c42-05f6-444e-8102-11f70cce6e61.png)

**Comment by millken** [comment]
After call with @CoderZhi,  the issue has been fixed
https://github.com/iotexproject/iotex-core/blob/c53ad418024ec136de14fb96f8ae5798f321afb3/chainservice/chainservice.go#L91-L94
