### ISSUE TITLE
A better log format

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#3476]
Consider lighthouse's log format

![Lvd7NvwkbX](https://user-images.githubusercontent.com/989846/175994886-6d31aa8d-e854-4e2e-839a-80897ddd284c.png)

**Comment by guo** [comment]
just one line change like this:
https://github.com/rs/zerolog#pretty-logging

Example:
![image](https://user-images.githubusercontent.com/448293/176002708-f25781fa-c62a-438f-8f1a-c7482441b542.png)
