### ISSUE TITLE
[api]  move chainID metrics to chainservice

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3489]
### What would you like to be added
chainID metrics is added to grafana, however the IP address shows 127.0.0.1, try to get accurate/external IP from the source

### How important you think this is for IoTeX
- [] must have
- [x] should have
- [] nice to have

### Additional information
chainID metrics is added in https://github.com/iotexproject/iotex-core/commit/a221d57727d01cef829cbde4af25adc4adea5789, and updated in https://github.com/iotexproject/iotex-core/commit/00026974ea9aade22859d07485422a1298ba8d0f

**Comment by dustinxie** [comment]
<img width="565" alt="Screen Shot 2022-06-29 at 5 49 27 PM" src="https://user-images.githubusercontent.com/12551272/176569554-4844cef4-ec67-4542-aed4-f5015beb99a9.png">

**Comment by millken** [comment]
proxy or load balance in front of the gRPC server?
