### ISSUE TITLE
Support for eth_sendTransaction in RPC calls

### ISSUE THREAD

**Issue by senerakdemir** [iotexproject/iotex-core#3501]
I'm developing a p2e game and I need the **eth_sendTransaction** method. 
Your Babel API is _eth_sendTransaction_ method is not supported. When I call the existing **eth_sendRawTransaction** method I get the following error :
_{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"encoding/hex: invalid byte: U+007B'"}_
In summary, can you add the **eth_sendTransaction** method to the api?
You can view the document here.
[https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction)

**Comment by Liuhaai** [comment]
Could you provide the request json data for us to debug?
