### ISSUE TITLE
move config.Consensus to consensus package

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3504]
### Description of the code refactor
it contains `RollDPoS` struct, so need to handle that as well

### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (like reduce complexity)
- [x] reduce/decouple dependencies between code modules
- [] increase test coverage
- [x] better code readability

**Comment by millken** [comment]
closed via #3735
