### ISSUE TITLE
move config.DardanellesUpgrade to consensus package

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3506]
### Description of the code refactor
as title

### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (like reduce complexity)
- [x] reduce/decouple dependencies between code modules
- [] increase test coverage
- [x] better code readability

**Comment by millken** [comment]
Updated in pr #3504

**Comment by millken** [comment]
Closed via #3735
