### ISSUE TITLE
"Segmentation fault" when running the node on single cpu server

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#351]
I'm experiencing a segmentation fault error on my VPS (Virtual Private Server rented on OVH provider). 

That's a very basic configuration with 1vCPU and 2GB of ram, the server is located in France (Strasburg).

Here is what happens: if I run the node (according to docs.iotex.io) after a few minutes (or even seconds) I get the server freezed: watching the cpu/memory load while the node is running I see it freezes around 1.84GB used over 1.9GB available.

So I configured and run a second node on my Macbook (i7-4cores-8threads-16GBram, located in Italy) at home and it synced smootly and quickly, up to the latest block.

At that point I decided to run again the node on the VPS, and I noticed it started syncing smoothly as well, with only 40% cpu and 400MB ram usage, and I also noticed my node at home was receiving block syncing requests from my VPS node. I manually stopped both nodes around height 60,000 on the VPS node.

I could reproduce the problem: each time the VPS node (1 cpu 2GB ram in France) can sync with my home node (8 cpu, 16GB ram in Italy) it runs smoothly. If I shut down my node in Italy the VPS node saturates the memory in a few seconds, generates seg fault and freezes my server.

**Comment by zjshen14** [comment]
Do you still have the exception stack when you saw "segment fault"

**Comment by simonerom** [comment]
It’s actually not easy to even get the segfault message in the terminal as it’s almost frozen. Sometimes I could check Docker and notice that it lists no containers running, yet I see  iotex-server executable still among the processes list. Keep in mind that I’m not debugging the code, I’m just running it. If you pm me on gitter I can send you screen recording.

**Comment by simonerom** [comment]
Great work thank you! Everything is workin for me now, including the explorer!

Keep up the great work, looking forward for next features!
