### ISSUE TITLE
[db] Provide in-memory db for api layer

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3512]
### What would you like to be added
Read cache in API `./api/read_cache.go` should be integrated into db layer

### How important you think this is for IoTeX
- [] must have
- [] should have
- [x] nice to have

### Additional information
Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)

**Comment by raullenchai** [comment]
We have no intention to implement
