### ISSUE TITLE
[api] implicit memory aliasing in for loop

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3536]
### Description of the code refactor
check if this is an issue, if yes, fix [Implicit memory aliasing in for loop.](https://github.com/iotexproject/iotex-core/security/code-scanning/60)

### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (potential security issue)
- [] reduce/decouple dependencies between code modules
- [] increase test coverage
- [] better code readability

**Comment by Liuhaai** [comment]
This is not a problem. As the warning indicates, the address of value is unchanged in the loop. But its value is consumed in `handleWeb3Req`.
Below is an example for illustrating the idea.
```
func main() {
	arr := []int{1, 2, 3}
	total := 0
	for _, v := range arr {
		ptr_v := &v
		total += *ptr_v
		fmt.Printf("value %v address %p\n", v, &v)
	}
	fmt.Printf("total %v\n", total)
}
```
`v` in the loop share the same address. But `total` is 6
