### ISSUE TITLE
Use of weak random number generator (math/rand instead of crypto/rand)

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3537]
### Description of the code refactor
fix all [Use of weak random number generator (math/rand instead of crypto/rand)](https://github.com/iotexproject/iotex-core/security/code-scanning) in security scan result (page 2 & 3)

### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (potential security issue)
- [] reduce/decouple dependencies between code modules
- [] increase test coverage
- [] better code readability

**Comment by millken** [comment]
closed by https://github.com/iotexproject/iotex-core/pull/3543#issuecomment-1189732336

**Comment by dustinxie** [comment]
1. no need to touch all test files
2. use runtime/fastrand to replace math/rand
