### ISSUE TITLE
move config.BlockSync to blocksync package

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3541]
### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [x] better code design or structure (like reduce complexity)
- [x] reduce/decouple dependencies between code modules
- [] increase test coverage
- [x] better code readability

**Comment by millken** [comment]
fixed in #3736
