### ISSUE TITLE
[filedao] Investigate "Block already exists." error in testnet

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3560]
### What did you see instead?

> {"log.level":"info","@timestamp":"2022-07-18T00:05:35.413Z","log.origin":{"file.name":"chainservice/builder.go","file.line":419},"message":"Successfully committed block.","ioAddr":"io1etc9ffzsg7lvph3j4ncczg08llvame8k3asyzc","height":15373920}
{"log.level":"error","@timestamp":"2022-07-18T00:05:35.417Z","log.origin":{"file.name":"filedao/filedao.go","file.line":302},"message":"Block already exists.","ioAddr":"io1etc9ffzsg7lvph3j4ncczg08llvame8k3asyzc","height":15373920,"hash":"e3bb9d31ab262db7e91f059c7741284263b63ae6ce05ebe60e7bf9318e19d138"}

**Comment by raullenchai** [comment]
@Liuhaai pls be specific what happened and how to repo so others can take a look
