### ISSUE TITLE
add solc compiler support

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3594]
### What would you like to be added
as title

### Why is this needed
go-ethereum removed solc compiler support in https://github.com/ethereum/go-ethereum/pull/24936, which is needed by our `ioctl contract` command. As a result, if we advance to latest ethereum release, iotex-core won't compile

### How important you think this is for IoTeX
- [x] must have
- [] should have
- [] nice to have

### Additional information
an easy solution is to move the relevant code/API to iotex-core (implement them)

**Comment by raullenchai** [comment]
We can potentially upgrade to the latest version of EVM @dustinxie
