### ISSUE TITLE
Build error when following instructions in readme

### ISSUE THREAD

**Issue by chuang39** [iotexproject/iotex-core#36]
Run following commands and then see the error.

$ dep ensure; make fmt;
$ make build
...
`# iotex-core/vendor/github.com/iotexproject/iotex-core/crypto
vendor/github.com/iotexproject/iotex-core/crypto/sig.go:9:24: fatal error: lib/ecckey.h: No such file or directory
 //#include "lib/ecckey.h"`
...
`Makefile:49: recipe for target 'build' failed
make: *** [build] Error 2`

Any suggestion on the build? Thanks!

**Comment by zjshen14** [comment]
@chuang39 what the os and the golang version were when you built the project?

**Comment by chuang39** [comment]
khuang@khuang-ubuntu:~/myapp/Go/src/iotex-core$ go version
go version **go1.9.1** linux/amd64

khuang@khuang-ubuntu:~/myapp/Go/src/iotex-core$ uname -a
Linux 4.4.0-128-generic #154-**Ubuntu** SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'll try it on macos.

**Comment by zjshen14** [comment]
linux should also work. I wonder if the vendor dir is messed up. Could you delete the vendor dir and `dep ensure` again?

**Comment by raullenchai** [comment]
@chuang39 let us know if this is still the issue.

**Comment by raullenchai** [comment]
Close as there is no reply for a couple of months
