### ISSUE TITLE
Question - how large is iotex chain's data after uncompress?

### ISSUE THREAD

**Issue by kuchaguangjie** [iotexproject/iotex-core#3607]
`data.tar.gz` for mainnet is about 46Gb, how large is it after uncompression ?
I ask because not sure is the disk of my laptop big enough.

For testnet, it's about 26.5Gb, same question as above.

It would be nice to mention this in the https://github.com/iotexproject/iotex-bootstrap .

Thanks.

**Comment by kuchaguangjie** [comment]
Just finished compression, the mainnet data is about 72Gb, after uncompression. Not as large as I worries it would be.

**Comment by raullenchai** [comment]
> Just finished compression, the mainnet data is about 72Gb, after uncompression. Not as large as I worried it would be.

Thx for checking this one. We will have the size monitored on iotex scan soon
