### ISSUE TITLE
ioctl contract prepare got error

### ISSUE THREAD

**Issue by huangzhiran** [iotexproject/iotex-core#3625]
### What version of iotex-core image (or code branch) are you using?
iotex-core-1.8.2
iotex testnet

### What operating system and processor architecture are you using?
macos arm64

### What did you expect to see?
ioctl cmd success

### What did you see instead?

ioctl contract prepare
Preparing solidity compiler ...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x104f1790c]

goroutine 1 [running]:
github.com/iotexproject/iotex-core/ioctl/cmd/contract.checkCompilerVersion(...)
	/private/tmp/ioctl-20220808-39121-1ny9gzg/iotex-core-1.8.2/ioctl/cmd/contract/contract.go:98
github.com/iotexproject/iotex-core/ioctl/cmd/contract.prepare()
	/private/tmp/ioctl-20220808-39121-1ny9gzg/iotex-core-1.8.2/ioctl/cmd/contract/contractprepare.go:58 +0xac
github.com/iotexproject/iotex-core/ioctl/cmd/contract.glob..func7(0x105841ac0?, {0x10588c018?, 0x0?, 0x0?})
	/private/tmp/ioctl-20220808-39121-1ny9gzg/iotex-core-1.8.2/ioctl/cmd/contract/contractprepare.go:39 +0x24
github.com/spf13/cobra.(*Command).execute(0x105841ac0, {0x10588c018, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x1400037e580)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/private/tmp/ioctl-20220808-39121-1ny9gzg/iotex-core-1.8.2/tools/ioctl/ioctl.go:17 +0x20

**Comment by huof6829** [comment]
`solc` installed failed in local, and should return error, not panic.  I test it: 
![solc](https://user-images.githubusercontent.com/9823472/188356556-7dfab82d-c661-4369-b9d6-5024bf1d5b9d.jpeg)

**Comment by huof6829** [comment]
Execute  `install-cli.sh`  can occur.  The executable file `ioctl` is download from remote repo.

**Comment by huof6829** [comment]
The panic is made by executing `install-cli.sh` which uses stable release version 1.8.2 where the panic is not fixed yet.   The panic is fixed by pr#3595, merged in `2022-08-20`. Next stable release it will be fine. Now you can use latest unstable release.  see https://github.com/iotexproject/iotex-docs-gitbook/blob/master/get-started/command-line-client/install-ioctl-cli.md
