### ISSUE TITLE
testnet failed to validate block

### ISSUE THREAD

**Issue by Hanmask21** [iotexproject/iotex-core#3712]
Block: 17667040
`blocksync/blocksync.go:191	block sync intervals.	{"ioAddr": "io1k2mnvvg9tn2ttyawnke2vmtcu2606m3k827l8a", "intervals": [{"Start":17666641,"End":17666641}], "targetHeight": 17667040}`
Validate error:
`{"level":"error","ts":1670928314.667299,"caller":"blocksync/blocksync.go:167","msg":"failed to commit block","ioAddr":"io12u70dl3uygwnhzw3clgrmwxlztde46949rem0a","error":"failed to validate block with workingset in statedb: delta state digest doesn't match","errorVerbose":"delta state digest doesn't match\ngithub.com/iotexproject/iotex-core/blockchain/block.init\n\t/go/apps/iotex-core/blockchain/block/header.go:43\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6222\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:233\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nfailed to validate block with workingset in statedb\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Validate\n\t/go/apps/iotex-core/state/factory/statedb.go:216\ngithub.com/iotexproject/iotex-core/blockchain/block.(*validator).Validate\n\t/go/apps/iotex-core/blockchain/block/validator.go:45\ngithub.com/iotexproject/iotex-core/blockchain.(*blockchain).ValidateBlock\n\t/go/apps/iotex-core/blockchain/blockchain.go:322\ngithub.com/iotexproject/iotex-core/chainservice.(*Builder).buildBlockSyncer.func1\n\t/go/apps/iotex-core/chainservice/builder.go:408\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).commitBlocks\n\t/go/apps/iotex-core/blocksync/blocksync.go:162\ngithub.com/iotexproject/iotex-core/blocksync.(*blockSyncer).ProcessBlock\n\t/go/apps/iotex-core/blocksync/blocksync.go:280\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).HandleBlock\n\t/go/apps/iotex-core/chainservice/chainservice.go:146\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).handleBlockMsg\n\t/go/apps/iotex-core/dispatcher/dispatcher.go:288\ngithub.com/iotexproject/iotex-core/dispatcher.(*IotxDispatcher).blockHandler\n\t/go/apps/iotex-core/dispatcher/dispatcher.go:229\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","height":17666641,"peer":"12D3KooWGYwuDHa5a4Z62oC2i3mjMb9jTTqpS2CFsFhhZBnpKfbw"}`

**Comment by dustinxie** [comment]
you will need to use `v1.9.0-rc1` image and set the correct hard-fork height for testnet, see: https://github.com/iotexproject/iotex-bootstrap/commit/8e4a01e0455de58117d96f32010eae1b8613dffd
