### ISSUE TITLE
ioctl won't work without specifying endpoint

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#3716]
if endpoint is not set via `ioctl config set endpoint`, any commands using endpoint, e.g., `ioctl node delegate --endpoint ....` will fail

**Comment by huof6829** [comment]
<img width="1069" alt="截屏2022-12-20 23 07 39" src="https://user-images.githubusercontent.com/9823472/208699118-97f87ff8-898d-4803-99a1-993f8ca43fee.png">
<img width="789" alt="截屏2022-12-20 23 07 22" src="https://user-images.githubusercontent.com/9823472/208699151-793c7534-2d06-481b-8bc1-40f487a9b334.png">
I test and  `ioctl xxx --endpoint` succeed.
more detailed descriptions can be given?

**Comment by huof6829** [comment]
Default secure connect is `true` after run cmd normally,  but default value is  `false`  if `secureConnect` in config file  is false or removed by mistaken. this is wrong. Default value should be from `--insecure` if cmdline has, otherwise from `secureConnect`
