### ISSUE TITLE
Add e2e test for web3 rewarding 

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3730]
### What would you like to be added
More tests should be added under the file `./action/rlp_tx_test.go`
### Why is this needed
pr3691 follow-up
### How important you think this is for IoTeX
- [] must have
- [] should have
- [] nice to have

### Additional information
Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)

**Comment by ququzone** [comment]
`./action/rlp_tx_test.go` already have rewarding related tests. @Liuhaai 

https://github.com/iotexproject/iotex-core/blob/master/action/rlp_tx_test.go#L263-L288
https://github.com/iotexproject/iotex-core/blob/master/action/rlp_tx_test.go#L375-L377

**Comment by Liuhaai** [comment]
> `./action/rlp_tx_test.go` already have rewarding related tests. @Liuhaai
> 
> https://github.com/iotexproject/iotex-core/blob/master/action/rlp_tx_test.go#L263-L288 https://github.com/iotexproject/iotex-core/blob/master/action/rlp_tx_test.go#L375-L377

thx for the correction
