### ISSUE TITLE
stake.iotex.io not showing "Delegate Version" after upgrading to v1.9.0

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3746]
### What version of iotex-core image (or code branch) are you using?
v1.9.0

### What did you expect to see?
stake.iotex.io should show "Delegate Version" = v1.9.0

### What did you see instead?
it is empty

**Comment by raullenchai** [comment]
"iotex_heartbeat_status{source="v1.8.0",status_type="packageVersion"} " is missing

**Comment by raullenchai** [comment]
could be related to https://github.com/golang/go/issues/50603

**Comment by dustinxie** [comment]
culprit is https://github.com/iotexproject/iotex-core/commit/c14dccac8626f070122032fcd1620d0d9177d6ba
