### ISSUE TITLE
ioctl broken for old glibc

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#3786]
### What version of iotex-core image (or code branch) are you using?
1.9.1

### What operating system and processor architecture are you using?
Centos 8 stream Glibc 2.28

### What did you do? If possible, provide a recipe for reproducing the error.
Install ioctl via instructions on Centos 8 stream

### What did you expect to see?
Working installation of ioctl

### What did you see instead?
```
ioctl: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ioctl)
ioctl: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ioctl)
```
Seems as though it is built against latest version of glibc in golang:1.18.5-alpine container making it incompatible with Linux variants using a slightly older version of GLIBC

**Comment by dustinxie** [comment]
the recommendation/solution is to upgrade to CentOS 9, which is released 2 years ago (Dec 2021)

CentOS 8 is expected to reach EOL at May 2024 (https://wiki.centos.org/About/Product), as there exist many other similar outdated OS. It's not feasible for us to keep compatibility with all those outdated OS.
