### ISSUE TITLE
exceeds block gas limit

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#3801]
### What version of iotex-core image (or code branch) are you using?
1.9.1

### What operating system and processor architecture are you using?
Docker container or local machine

### What did you do? If possible, provide a recipe for reproducing the error.
Attemped to transfer XRC20 token

```
ioctl  transfer io1ahjs68fh4skwatg7fl9pzh7vpp9crr0us79u8p 0.088 -c io1gafy2msqmmmqyhrhk4dg3ghc59cplyhekyyu26 -s sender 
```

### What did you expect to see?
Transfer of token without error

### What did you see instead?
Error

```
Error: exceeds block gas limit
```

**Comment by huof6829** [comment]
@jerkyrs  `0.088` means transfer amount is 88 or another integer value? 
the command should be `ioctl xrc20 transfer target_address amount -c contact_address`  and the amount is an integer.

**Comment by huof6829** [comment]
I run the same command in local machine, and run successfully with no error. Pls check and confirm it.  @jerkyrs  

<img width="1196" alt="截屏2023-02-08 18 56 14" src="https://user-images.githubusercontent.com/9823472/217510996-53a93576-8552-405d-bb64-fd5c02d7b071.png">

<img width="1076" alt="截屏2023-02-08 18 58 27" src="https://user-images.githubusercontent.com/9823472/217511039-b9fe54b5-6d4a-4fd6-ba40-705a84738be7.png">

**Comment by jerkyrs** [comment]
yes it works going via api.mainnet.iotex.one:443 , so why does it not work going locally . Is the api.mainnet.iotex.one using Ethereum API , the other thing is that it is secure vs locally which is insecure.

**Comment by dustinxie** [comment]
`api.mainnet.iotex.one:443` connects you to the real blockchain, which has the necessary state/data for the command to work.

Local is your test environment, you can run a local blockchain, but it does not have the necessary state/data for that specific `ioctl` command you are executing
