### ISSUE TITLE
limit auto-release to official numerical tag

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3819]
### What would you like to be added
currently a release is automatically generated whenever a tag starting with `v` is pushed to origin. See https://github.com/iotexproject/iotex-core/blob/master/.github/workflows/release.yaml#L3-L6. This leads to unnecessary releases like `v1.9.2-rc0`

The auto-release should be limited only to official numerical tag, such as `v1.9.2`, tags of all other formats should not trigger an auto-release

### Why is this needed
reduce unnecessary releases

### How important you think this is for IoTeX
- [x] must have
- [] should have
- [] nice to have

### Additional information
Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)

**Comment by xianhuawei** [comment]
fix 

https://github.com/iotexproject/iotex-core/commit/fba0ef9fa12bda62abc3095527462f10dabe2ed1
