### ISSUE TITLE
[ioctl] probation status not shown in `ioctl node delegate` command

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3839]
### What version of iotex-core image (or code branch) are you using?
master

### What operating system and processor architecture are you using?
mac

### What did you do? If possible, provide a recipe for reproducing the error.
`ioctl node probationlist` shows that delegate `royalland` is in probation:

<img width="534" alt="Screen Shot 2023-04-01 at 1 19 48 PM" src="https://user-images.githubusercontent.com/12551272/229312320-255687c9-69a9-4784-be9e-38a0cc7a6d65.png">

### What did you expect to see?
`ioctl node delegate` command should show this delegate as in probation

### What did you see instead?
However, the `ioctl node delegate` command does not show it as in probation

<img width="961" alt="Screen Shot 2023-04-01 at 1 22 01 PM" src="https://user-images.githubusercontent.com/12551272/229312390-0739b5cc-3f26-4d61-8788-acf7115d1758.png">

**Comment by millken** [comment]
Is caused by using old ioctl
