### ISSUE TITLE
straighten up mock packages

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3871]
### Description of the code refactor
the last 4 lines of mockgen.sh
```
mkdir -p ./action/protocol/staking
mockgen -destination=./action/protocol/staking/contractstake_indexer_mock.go  \
        -source=./action/protocol/staking/contractstake_indexer.go \
        -package=staking \
        ContractStakingIndexer

mkdir -p ./blockchain/blockdao/mock
mockgen -destination=./blockchain/blockdao/mock/blockindexer_mock.go  \
        -package=mock \
        github.com/iotexproject/iotex-core/blockchain/blockdao \
        BlockIndexer
mockgen -destination=./blockchain/blockdao/mock/blockindexer_withstart_mock.go  \
        -package=mock \
        github.com/iotexproject/iotex-core/blockchain/blockdao \
        BlockIndexerWithStart
mockgen -destination=./blockchain/blockdao/mock/blockdao_mock.go  \
        -package=mock \
        github.com/iotexproject/iotex-core/blockchain/blockdao \
        BlockDAO
```
there are 2 problems:
1. change destination to `./test/mock/xxx`, just like earlier mock files
2. there's already an existing line/file for `BlockDAO` interface, please remove the recent added one

### Why is this needed
- [] better/less memory usage
- [] reduce running time
- [] clean (easy-to-understand) data structure or algorithm
- [] remove dead code
- [] better code design or structure (like reduce complexity)
- [x] reduce/decouple dependencies between code modules
- [] increase test coverage
- [] better code readability
- [x] remove duplicate code

**Comment by envestcc** [comment]
If the `ContractStakingIndexer` mock is moved outside of the package, referencing it within this package will cause a circular dependency. Therefore, it needs to remain inside the package.

The other three can be moved outside.
