### ISSUE TITLE
[ Web3 API ] Custom Errors are not correctly returned  

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#3919]
### What version of iotex-core image (or code branch) are you using?
N/A

### What operating system and processor architecture are you using?
Mac M1

### What did you do? If possible, provide a recipe for reproducing the error.
Unzip [hardhat-starter.zip](https://github.com/iotexproject/iotex-core/files/12306661/hardhat-starter.zip)

```
cd hardhat-starter
echo PRIVATE_KEY=[YOUR IOTEX DEV ACCOUNT] > .env
npm install
npx hardhat run scripts/deploy_and_reproduce.ts --network iotex_testnet
```

### What did you expect to see?
[Custom Errors](https://soliditylang.org/blog/2021/04/21/custom-errors/) have been introduced in Solidity 0.8.4. The script execution deploys a contract that reverts with a custom error and it should catch and log the custom error with its data.

### What did you see instead?
The script is failing with a Provider Error: _"ProviderError: execution simulation failed: status = 106"_

Run `npx hardhat run scripts/deploy_and_reproduce.ts` to see the correct behavior in the local Hardhat VM

**Comment by ququzone** [comment]
This bug cause by `eth_estimategas` api doesn't return correct error data.

**Comment by millken** [comment]
> This bug cause by `eth_estimategas` api doesn't return correct error data.

There are two bugs here, in addition to this, there is one eth_call will be returned as a normal call, not return custom error with its data, fix it later

**Comment by millken** [comment]
> This bug cause by `eth_estimategas` api doesn't return correct error data.

@ququzone I tested 'eth_estimategas' with ganache and it also return 'revert' message, Can you confirm it's a bug and need to fix?
