### ISSUE TITLE
transaction hash is not eth-compatible

### ISSUE THREAD

**Issue by envestcc** [iotexproject/iotex-core#3944]
### What version of iotex-core image (or code branch) are you using?
v1.11.2

### What operating system and processor architecture are you using?
macOS 14, Apple M1 Pro

### What did you do? If possible, provide a recipe for reproducing the error.
querying transaction by hash using ethclient and checking whether hash is consistent
```
import (
	"context"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/stretchr/testify/require"
)

func TestIoTexRead(t *testing.T) {
	r := require.New(t)
	cli, err := ethclient.Dial("https://babel-api.testnet.iotex.io")
	r.NoError(err)
	hash := "0xfcaf377ff3cc785d60c58de7e121d6a2e79e1c58c189ea8641f3ea61f7605285"
	tx, isPending, err := cli.TransactionByHash(context.Background(), common.HexToHash(hash))
	r.NoError(err)
	r.Equal(hash, tx.Hash().String())
}
```

### What did you expect to see?
test should pass

### What did you see instead?
```
expected: "0xfcaf377ff3cc785d60c58de7e121d6a2e79e1c58c189ea8641f3ea61f7605285"
actual  : "0x441ab0b3af3b4de256fe95efcdbf73b7652cf260b89cf8746e0aea486c0467bd"
```

**Comment by dustinxie** [comment]
it was root-caused to the fact that our returning `tx`'s signauture value does not include the chainID, will file a PR soon to fix
