### ISSUE TITLE
eth_estimateGas return revert error

### ISSUE THREAD

**Issue by envestcc** [iotexproject/iotex-core#3969]
### What version of iotex-core image (or code branch) are you using?
v1.12

### What operating system and processor architecture are you using?
macOS M1

### What did you do? If possible, provide a recipe for reproducing the error.

Using version v1.13.0 of ethclient to call eth_estimateGas, to estimate the gas for a contract call.

```go
func TestIoTexWrite(t *testing.T) {
	r := require.New(t)

	cli, err := ethclient.Dial("https://babel-api.testnet.iotex.io")
	r.NoError(err)

	to := common.HexToAddress(`0xbc3C770272a8D274Ba75CE2A104dF397F7CA793e`)
	data, err := hex.DecodeString(`bfc3254b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000`)
	r.NoError(err)
	gas, err := cli.EstimateGas(context.Background(), ethereum.CallMsg{
		To: &to,
		Data: data,
	})
	r.NoError(err)
	t.Logf("gas: %+v", gas)
}

```

The abi of contract is as follows:
```json
[	{		"constant": true,		"inputs": [],		"name": "getProof",		"outputs": [			{				"internalType": "bytes",				"name": "",				"type": "bytes"			}		],		"payable": false,		"stateMutability": "view",		"type": "function"	},	{		"constant": false,		"inputs": [			{				"internalType": "bytes",				"name": "_proof",				"type": "bytes"			}		],		"name": "setProof",		"outputs": [],		"payable": false,		"stateMutability": "nonpayable",		"type": "function"	}]
```

### What did you expect to see?

show gas estimated

### What did you see instead?

execution simulation failed: status = 106

**Comment by envestcc** [comment]
This issue started to occur from version v1.13.0 of go-ethereum.

**Comment by envestcc** [comment]
The reason for the failure is that in version 1.13, it modified the request parameter structure in ethclient, changing the original `data` field to `input` field. The corresponding PR for this modification is: https://github.com/ethereum/go-ethereum/pull/28078/files

The field name defined in the JSON-RPC Spec is `input`, and the use of `data` is a historical legacy issue. In Ethereum API implementations, both parameters are supported (https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L93)

**Comment by CoderZhi** [comment]
let's support both `input` and `data` in api node
