### ISSUE TITLE
Support reward claim via web3

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#4068]
Enable reward claiming from reward pool via web3

### Is this a hard-fork (and height to be activated)
- [] Yes
- Name of activation height:

### Implementation plan
- [] Phase 1 description (PR number)
- [] Phase 2 description (PR number)
- [] Phase 3 description (PR number)

### Affected modules
- [] action
- [] actpool
- [] api
- [] blockchain
- [] blockindex
- [] blocksync
- [] chainservice
- [] config
- [] consensus
- [] db
- [] dispatcher
- [] ioctl
- [] p2p
- [] server
- [] state
- [] tools

**Comment by envestcc** [comment]
already supported
