### ISSUE TITLE
Wrong block hash while syncing node on Testnet

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#409]
I'm currently getting the following errors while syncing my node with the open testnet:

```
{"level":"error","recvHeight":6096,"confirmedHeight":6095,"source":"blockBuffer","error":"Failed to validate block on height 6096: failed to verify block's height and hash: wrong prev hash 69913b6f31b1b9f83e805bed10eb8acc38a779c72f6e0c9fd7f9ddedbd487b58, expecting f2f2b1e117fd7a8f27f0e1d95c39daa6249373af998681c927a95d3ae2799d24: failed to validate the block","syncHeight":6097,"time":"2019-01-02T11:36:09Z","message":"Failed to commit the block."}
```

I'm attaching db files and log for you to reproduce.

[log_wrong_block_hash.tar.gz](https://github.com/iotexproject/iotex-core/files/2720663/log_wrong_block_hash.tar.gz)

[chain.db.tar.gz](https://github.com/iotexproject/iotex-core/files/2720666/chain.db.tar.gz)
[trie.db.tar.gz](https://github.com/iotexproject/iotex-core/files/2720668/trie.db.tar.gz)

**Comment by raullenchai** [comment]
assign to @zjshen14

**Comment by jerkyrs** [comment]
i think i have same issue on #506
