### ISSUE TITLE
Some wallets have inccorect nonce from rpc. 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-core#4156]
There are a couple examples where the nonce returned by rpc not correct. 

This prevent users from sending new txns.  They txns could get pending and dropped after timing out.

**Comment by anwar139** [comment]
Hey Qevan, as per conversation, I've collected some of the addresses which reported this issue  - Can't tansfer out IOTX from their wallets. They can receive.

1) io1mq7a7xey4gjefpxcnk50ttkqxnft0meg3yu2dq
2) io1ducahpprkmxzdmy3zs3jt9su8semwcev9s2mku
3) io1zl4sx7lt8vmpxzcv4v34tckjruvjz08hfln8k8

I'll update when I find more

**Comment by satyashr** [comment]
This is my IOPAY wallet :
io1zl4sx7lt8vmpxzcv4v34tckjruvjz08hfln8k8

I've Quite a few IOTEX stuck in TrustWallet, can you please help resolve this Issue ASAP? I need to transfer my fund to exchanges?

**Comment by Liuhaai** [comment]
@anwar139 @satyashr  I just checked that the state of these accounts is unchanged in the blockchain, where there is no outbounding transactions from these accounts. We're fixing the transaction pending issue. Your tokens can be safely transfered out once it's fixed.

**Comment by gopinath87607** [comment]
@Liuhaai any estimation time?

**Comment by satyashr** [comment]
Any ETA for when the bug will be fixed?

**Comment by anwar139** [comment]
Another address added No.5 - was attempting to transfer from a ledger. Similar symptom(s), managed to get hash, but later on, transaction dropped and the hash is no longer traceable on iotexscan

**Comment by satyashr** [comment]
This could be a widespread issue, people haven't tried to move IOTEX from Self Custody wallet to exchanges! Please give us the ETA on when it will be fixed.

**Comment by anwar139** [comment]
Can you try again?

**Comment by anwar139** [comment]
> This could be a widespread issue, people haven't tried to move IOTEX from Self Custody wallet to exchanges! Please give us the ETA on when it will be fixed.

Quoting Jeremi from 1 of the tickets on Discord. I removed unnecessary messages. 

"Hey, the issue has been fixed in the code, for what it seems, but the iotex-core node software still needs to be updated across the entire network before the fix is available to use."

**Comment by guo** [comment]
let's keep it open until the fix is released.

**Comment by Reallyfresh** [comment]
I'm experiencing this problem as well. I haven't accessed my wallet in 3 years and when I tried a few days ago to make a transfer everything is still pending and nothing is showing up on iotexscan.

io127fxrul5ykcwec6pjy4rrlrpng0xwuppd2fzac

**Comment by anwar139** [comment]
added 1 more address 6). I wanted to add this address earlier, but seeing the thread was closed I thought it was unnecessary because I assumed fix will be released soon.

**Comment by Charliecharlie-git** [comment]
The address of the Chinese community with the same problem：
io1g0djt0dld0u6cj58fgkkf0e8mfjvdvm2tk0cn0

**Comment by Liuhaai** [comment]
@anwar139  @satyashr  @gopinath87607  @Reallyfresh  @Charliecharlie-git   Thanks for your patience. The fix has been deployed to our nodes. You can use our RPC (https://babel-api.mainnet.iotex.io/) to connect to the network. The transaction might take longer than usual to be minted since some of the delegates haven't upgraded to v1.13.1. However, we are notifying our delegates to upgrade their nodes. The status of the transaction can be checked at (https://iotexscan.io/?format=0x). Let me know if your transfer still fails.

**Comment by gopinath87607** [comment]
@Liuhaai thanks for the update

**Comment by anwar139** [comment]
Thanks for the work fam!
 And sorry if this late ping annoys you :p
