### ISSUE TITLE
SIGINT won't stop the program when syncing blocks

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#4158]
### What version of iotex-core image (or code branch) are you using?
v1.13
### What did you do? If possible, provide a recipe for reproducing the error.
ctrl+c to stop the process
### What did you expect to see?
The program was still running 
### What did you see instead?
The program will exit in a few seconds

**Comment by envestcc** [comment]
I was unable to reproduce this issue on my local Mac environment. @Liuhaai Please provide more information about your environment and when you are executing `ctrl+c`.
