### ISSUE TITLE
verify mainnet's genesis hash

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#4189]
### What version of iotex-core image (or code branch) are you using?
master

### What operating system and processor architecture are you using?
linux/macOS

### What did you do? If possible, provide a recipe for reproducing the error.
When starting a mainnet fullnode, it prints:
```
"Genesis hash: b337983730981c2d50f114eed5da9dd20b83c8c5e130beefdb3001dc858cfe8b"
```
while in our test code
```
func TestHash(t *testing.T) {
	require := require.New(t)
	cfg, err := New("")
	require.NoError(err)
	hash := cfg.Hash()
	require.Equal("3dfcdee76186b59a9f9abd0ded8e6c093c35bddea23834044550fb68626adb62", hex.EncodeToString(hash[:]))
}
```

### What did you expect to see?
We should be able to generate the same hash value in our test code as in mainnet. It would be good to understand why, and adjust the test to track the same genesis hash value, which is important for mainnet safety/correctness

**Comment by millken** [comment]
The hash in `TestHash` reads the hardcode default configuration, and the mainnet reads the `genesis.yaml` file. Their configurations are different, resulting in inconsistent final genesis hashes. I will sync the `genesis.yaml` of mainnet to hardcode defaults
