### ISSUE TITLE
debug_traceTransaction reverted

### ISSUE THREAD

**Issue by jacob-chia** [iotexproject/iotex-core#4208]
### What version of iotex-core image (or code branch) are you using?

[v1.13.1](https://github.com/iotexproject/iotex-core/releases/tag/v1.13.1)

### What operating system and processor architecture are you using?

Ubuntu 20.04.1,  x86_64

### What did you do? If possible, provide a recipe for reproducing the error.

An action is success on scan: https://iotexscan.io/tx/e969d762f8216b32a04f4b827854f1bbcd5e833c073191067e45d8cf2d75884d
But it reverted in `debug_traceTransaction`, here is my rpc request:

```sh
curl http://127.0.0.1:15014/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"debug_traceTransaction","params":["0xe969d762f8216b32a04f4b827854f1bbcd5e833c073191067e45d8cf2d75884d"],"id":1,"jsonrpc":"2.0"}' | jq
```

### What did you expect to see?

A success response

### What did you see instead?

[debug_tracetx_resp.json](https://github.com/iotexproject/iotex-core/files/14766400/debug_tracetx.json)
![image](https://github.com/iotexproject/iotex-core/assets/61052369/3fc2eb7d-6c54-44c2-9586-49f297874deb)

**Comment by millken** [comment]
![img_v3_029e_a135abc1-9738-497c-a86f-2b8d207bfcfh](https://github.com/iotexproject/iotex-core/assets/176581/daf70bae-9adc-4984-8637-069e67c1e16c)
`debug_traceTransaction` simulates the execution of this tx in the EVM using zero address, the values of `msg.sender` different from in the real world (0x090dba43bdb643fdf5edfc94ec92203b5881ff69). 

The hash computed during the `debug_traceTransaction` operation does not meet the condition stipulated by require, resulting in revert being returned.

**Comment by jacob-chia** [comment]
In the simulation execution, `debug_traceTransaction` should use `tx.from` as `msg.sender`, instead of the 0 address.

**Comment by raullenchai** [comment]
Closing as fixed: `debug_traceTransaction` no longer simulates with a zero-address sender. The current implementation (api/coreservice.go TraceTransaction) replays the block's preceding actions and then re-executes the original sealed action in place, so `msg.sender` is the transaction's true sender. Verified on current master (v2.4.x line). Please reopen with a repro if you still see success-on-chain/revert-in-trace divergence on ≥v2.4.3.
