### ISSUE TITLE
start err: field sgdIndexDBPath not found in type blockchain.Config

### ISSUE THREAD

**Issue by yun81911** [iotexproject/iotex-core#4397]
deploy master on ubuntu ,configfile=https://raw.githubusercontent.com/iotexproject/iotex-bootstrap/v2.0.4/config_mainnet.yaml

when start system error message :
 ./bin/server  -config-path=$IOTEX_HOME/etc/config.yaml   -genesis-path=$IOTEX_HOME/etc/genesis.yaml

2024/09/19 11:55:43 Failed to new config. {error 26 0  failed to unmarshal YAML config to struct: yaml: unmarshal errors:
  line 94: field sgdIndexDBPath not found in type blockchain.Config}

**Comment by dustinxie** [comment]
`sgdIndexDBPath` is a deprecated field that will be removed in the next release
please deploy the latest release v2.0.4 code/image, do not use master branch
