### ISSUE TITLE
`eth_getTransactionReceipt` RPC response missing field

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-core#4478]
The `eth_getTransactionReceipt` RP response missing `effectiveGasPrice` field.

The `effectiveGasPrice` field define is below:
<img width="1101" alt="截屏2024-11-07 22 40 54" src="https://github.com/user-attachments/assets/a777dc04-24a3-4858-94ad-ac773662d7a3">

**Comment by envestcc** [comment]
@ququzone Already supported after 2.1 HF
