### ISSUE TITLE
Please report testnet wallet technical issue in this thread

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#46]
Please comment on this thread by answering the following questions. Thanks!

**Comment by kingsop** [comment]
What did you do?
I am build a new testnet with iotexproject/iotex-core

What did you expect to see?
Run Unit Tests
What did you see instead?
when ienter  "dep ensure" ,there has been a mistake,what should i do.

  ✗ unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/grpc?go-get=1": Get http://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:80: i/o timeout

**Comment by zjshen14** [comment]
@kingsop are you using go 1.11? Saw the same problem reported here: https://github.com/cloudflare/bn256/issues/2

**Comment by kingsop** [comment]
yeah，good job！i try cloudflare / bn256＃2，it fix Go 1.11 compatibility.

**Comment by kingsop** [comment]
When I try the next step，there was another error there.it said：
There was another mistake there.
localhost:iotex-core kingsop123$ make test
go fmt ./...
go test -short ./...
ok  	github.com/iotexproject/iotex-core/accounts/keystore	0.103s
# github.com/iotexproject/iotex-core/blockchain
blockchain/blockchain.go:223: Event.Msgf format %s has arg opt of wrong type blockchain.Option
blockchain/blockvalidator.go:79: Wrapf call needs 1 arg but has 2 args
ok  	github.com/iotexproject/iotex-core/actpool	0.905s
ok  	github.com/iotexproject/iotex-core/beacon	0.036s
FAIL	github.com/iotexproject/iotex-core/blockchain [build failed]
ok  	github.com/iotexproject/iotex-core/blockchain/action	0.047s
ok  	github.com/iotexproject/iotex-core/blocksync	0.594s
?   	github.com/iotexproject/iotex-core/cli/iotc	[no test files]
ok  	github.com/iotexproject/iotex-core/cli/iotc/cmd	0.109s
ok  	github.com/iotexproject/iotex-core/config	0.073s
?   	github.com/iotexproject/iotex-core/consensus	[no test files]
?   	github.com/iotexproject/iotex-core/consensus/scheme	[no test files]
# github.com/iotexproject/iotex-core/explorer
explorer/server.go:116: Event.Msgf call has arguments but no formatting directives
explorer/server.go:122: Event.Msgf call has arguments but no formatting directives
ok  	github.com/iotexproject/iotex-core/consensus/scheme/rolldpos	10.635s
?   	github.com/iotexproject/iotex-core/consensus/sim	[no test files]
?   	github.com/iotexproject/iotex-core/consensus/sim/proto	[no test files]
ok  	github.com/iotexproject/iotex-core/crypto	5.907s
ok  	github.com/iotexproject/iotex-core/db	0.038s
ok  	github.com/iotexproject/iotex-core/dispatch	0.276s
?   	github.com/iotexproject/iotex-core/dispatch/dispatcher	[no test files]
# github.com/iotexproject/iotex-core/state
state/factory.go:161: Event.Msgf format %s has arg opt of wrong type state.FactoryOption
ok  	github.com/iotexproject/iotex-core/e2etest	11.289s
FAIL	github.com/iotexproject/iotex-core/explorer [build failed]
?   	github.com/iotexproject/iotex-core/explorer/idl/explorer	[no test files]
ok  	github.com/iotexproject/iotex-core/iotxaddress	0.034s
ok  	github.com/iotexproject/iotex-core/iotxaddress/bech32	0.015s
ok  	github.com/iotexproject/iotex-core/logger	0.017s
ok  	github.com/iotexproject/iotex-core/network	2.595s
?   	github.com/iotexproject/iotex-core/network/node	[no test files]
?   	github.com/iotexproject/iotex-core/network/proto	[no test files]
ok  	github.com/iotexproject/iotex-core/pkg/counter	5.708s
?   	github.com/iotexproject/iotex-core/pkg/enc	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/errcode	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/hash	[no test files]
ok  	github.com/iotexproject/iotex-core/pkg/keypair	0.022s
ok  	github.com/iotexproject/iotex-core/pkg/lifecycle	0.027s
ok  	github.com/iotexproject/iotex-core/pkg/routine	0.632s
?   	github.com/iotexproject/iotex-core/pkg/util/byteutil	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/util/fileutil	[no test files]
?   	github.com/iotexproject/iotex-core/pkg/version	[no test files]
?   	github.com/iotexproject/iotex-core/proto	[no test files]
?   	github.com/iotexproject/iotex-core/server	[no test files]
?   	github.com/iotexproject/iotex-core/server/itx	[no test files]
FAIL	github.com/iotexproject/iotex-core/state [build failed]
?   	github.com/iotexproject/iotex-core/test/mock/mock_actpool	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_blockchain	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_blocksync	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_consensus	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_dispatcher	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_lifecycle	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_network	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_state	[no test files]
?   	github.com/iotexproject/iotex-core/test/mock/mock_trie	[no test files]
?   	github.com/iotexproject/iotex-core/test/testaddress	[no test files]
ok  	github.com/iotexproject/iotex-core/testutil	0.044s
ok  	github.com/iotexproject/iotex-core/tools/actioninjector	5.379s
?   	github.com/iotexproject/iotex-core/tools/addrgen	[no test files]
?   	github.com/iotexproject/iotex-core/tools/addrgen/internal/cmd	[no test files]
ok  	github.com/iotexproject/iotex-core/trie	4.270s
ok  	github.com/iotexproject/iotex-core/txvm	0.040s
make: *** [test] Error 2

**Comment by zjshen14** [comment]
Problem fixed
