### ISSUE TITLE
Add a JSON-RPC API to get the node status

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#47]
Now we print the node status in the log as a heartbeat every 10 secs: https://github.com/iotexproject/iotex-core/blob/master/server/itx/heartbeat.go

It's better to add a JSON-RPC API to let ops to query the node status. You're supposed to define an API here: https://github.com/iotexproject/iotex-core/blob/master/explorer/idl/explorer.idl, and implement it. You could refer to `heartbeat.go` for what metrics we want to expose.

**Comment by raullenchai** [comment]
I believe we should use grpc for the same purpose.

@zjshen14 does this overlap with https://github.com/iotexproject/iotex-core/issues/556?

**Comment by zjshen14** [comment]
We no longer need this issue
