### ISSUE TITLE
TestBroadcast successful?

### ISSUE THREAD

**Issue by nairan** [iotexproject/iotex-core#535]
Hi, can I humbly check the test case "TestBroadcast" (agent_test.go) can work without any change? Thank you.

**Comment by zjshen14** [comment]
Hi @nairan, did you run into any failure with the test case `TestBroadcast`?

**Comment by nairan** [comment]
I am not sure - the test can pass but I am seeing ERROR: 

`ERROR	go-p2p/p2p.go:324	Error when subscribing a broadcast message.	{"error": "subscription cancelled by calling sub.Cancel()"}`

Pls. do not look at line number (324) since I have debug code inside.

**Comment by Frankonly** [comment]
Hello @nairan, can you describe the situation when this error happened?

**Comment by nairan** [comment]
> Hello @nairan, can you describe the situation when this error happened?

Sure. Simply run "go test -v -run TestBroadcast". This was confirmed by @zjshen14 that it is not an issue (no?).

**Comment by Frankonly** [comment]
@zjshen14

**Comment by zjshen14** [comment]
> am not sure - the test can pass but I am seeing ERROR:
The error you see doesn't matter, and the should happen. Network messages are canceled after the p2p agent are stopped.

Close the this. Feel free to reopen it, if you find something else.
