### ISSUE TITLE
Implement a monitoring cron job

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#556]
We need to create a simple tool executable, which takes a list of endpoints of servers, and a target blockchain height as params. The executable poke every endpoints' getBlockMeta API to get the block height info. If any server respond a block height lower than the expectation, return failure. Otherwise, return success.

We could then deploy this executable a cron job to scan through the servers we want to monitor, and alert us if any server is abnormal. Feel free to ping me if you have any question.

**Comment by raullenchai** [comment]
@ashishsnigam feel free to ping @zjshen14 in https://gitter.im/iotex-dev-community/Lobby

**Comment by zjshen14** [comment]
Per discussion offline, we no longer need this cron job as we figure out an alternative monitoring plan, but thank you all the same @ashishsnigam!
