### ISSUE TITLE
panic error in running server executable

### ISSUE THREAD

**Issue by ashishsnigam** [iotexproject/iotex-core#578]
Setup - Observed with repo iotex-core from github.com/iotexproject master branch and also with forked repo from master branch
Code status - code checked in as of 22 Feb 2019
Environment - Go version 1.11.5 on mac OS Mojave 10.14.3  , docker installed

Steps - 
1) git clone repo
2) cd $GOPATH/src/github.com/iotexproject/iotex-core
3) make build (fine no error)
4) run command ./bin/server e2etest/config_local_delegate.yaml to start server in standalone mode
5) This command terminated with panic error. See attached file logs.txt from my laptop.
6) ./bin/minicluster command worked fine.
 
[logs.txt](https://github.com/iotexproject/iotex-core/files/2890724/logs.txt)

**Comment by raullenchai** [comment]
“{"level":"panic","ts":1550775945.0134761,"caller":"block/block.go:78","msg":"Failed to unmarshal public key.","addr":"io1v557hycpucapc80sa7c4px7ys0gahme7wsuk5q","networkAddress":"0.0.0.0:4689","nodeType":"full_node","error":"invalid secp256k1 public key"

Looks like the configured key/addr in yaml file is not up-to-date.

**Comment by ashishsnigam** [comment]
Issue occurred because I provided incorrect cli option. command I used was 
. ./bin/server e2etest/config_local_delegate.yaml 

Did not add switch -config-path before file name.

**Comment by raullenchai** [comment]
@ashishsnigam pls help to make the panic more informative, e.g., "no config file specified", rather than  "Failed to unmarshal public key" which is confusing.

**Comment by ashishsnigam** [comment]
@raullenchai sure. Will take it with other cli based work #132

**Comment by raullenchai** [comment]
```➜  iotex-core git:(master) ./bin/server e2etest/config_local_delegate.yaml
2019/02/25 10:50:01 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
{"level":"info","ts":1551120601.097259,"caller":"server/main.go:67","msg":"Config in use: {NodeType:full_node Network:{Host:0.0.0.0 Port:4689 ExternalHost: ExternalPort:4689 BootstrapNodes:[] MasterKey:33085588cc6a6a8177c7633d4dfb18dcc17ae2e764ca79346639e56c5f039869} Chain:{ChainDBPath:/tmp/chain.db TrieDBPath:/tmp/trie.db ID:1 Address: ProducerPubKey:0469d8208832b366b2d80a863386d75b4f4332a23920060cb18cdbb1fea5c339807bf6693be8a1dfe3a0f05fe000152e55680a26fa330c3b8f3c28d06519d56111 ProducerPrivKey:33085588cc6a6a8177c7633d4dfb18dcc17ae2e764ca79346639e56c5f039869 GenesisActionsPath: EmptyGenesis:false NumCandidates:101 EnableFallBackToFreshDB:false EnableSubChainStartInGenesis:false EnableTrielessStateDB:true EnableIndex:false EnableAsyncIndexWrite:false AllowedBlockGasResidue:10000} ActPool:{MaxNumActsPerPool:32000 MaxNumActsPerAcct:2000 MaxNumActsToPick:0 ActionExpiry:10m0s} Consensus:{Scheme:NOOP RollDPoS:{FSM:{EventChanSize:10000 UnmatchedEventTTL:3s UnmatchedEventInterval:100ms AcceptBlockTTL:4s AcceptProposalEndorsementTTL:2s AcceptLockEndorsementTTL:2s} ToleratedOvertime:2s Delay:5s} BlockCreationInterval:10s} BlockSync:{Interval:10s BufferSize:16} Dispatcher:{EventChanSize:10000}
```

Without --config-path, the binary now uses the default config (e.g., NOOP consensus). Good to close.
