### ISSUE TITLE
P2P network setup takes a long time

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#594]
{"level":"info","ts":1550888478.937869,"caller":"blockchain/blockchain.go:791","msg":"Add a subscriber.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate"}
{"level":"info","ts":1550888478.9422655,"caller":"go-p2p/p2p.go:254","msg":"P2p host started.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","address":["/ip4/10.16.15.26/tcp/4689/ipfs/12D3KooWHAwucimNXbySnUBUEMjpdM38VBXdmeAfmUtYKP8wnDuL"],"secureIO":true,"gossip":true}
{"level":"error","ts":1550888483.9466057,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial attempt failed: <peer.ID 12*8wnDuL> --> <peer.ID 12*W5DAGQ> dial attempt failed: dial tcp4 0.0.0.0:4689->10.19.251.97:4689: i/o timeout"}
{"level":"error","ts":1550888485.9523368,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial backoff"}
{"level":"error","ts":1550888494.9575458,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial attempt failed: <peer.ID 12*8wnDuL> --> <peer.ID 12*W5DAGQ> dial attempt failed: dial tcp4 0.0.0.0:4689->10.19.251.97:4689: i/o timeout"}
{"level":"error","ts":1550888507.9641738,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial attempt failed: <peer.ID 12*8wnDuL> --> <peer.ID 12*W5DAGQ> dial attempt failed: dial tcp4 0.0.0.0:4689->10.19.251.97:4689: i/o timeout"}
{"level":"error","ts":1550888528.9749358,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial attempt failed: <peer.ID 12*8wnDuL> --> <peer.ID 12*W5DAGQ> dial attempt failed: dial tcp4 0.0.0.0:4689->10.19.251.97:4689: i/o timeout"}
{"level":"error","ts":1550888565.9822242,"caller":"p2p/agent.go:385","msg":"Error happens, will retry.","addr":"io1t8nl3ezyjw00cmhqnzv8wth5uqhkztnrhv933a","networkAddress":"10.16.15.26:4689","nodeType":"delegate","error":"dial attempt failed: <peer.ID 12*8wnDuL> --> <peer.ID 12*W5DAGQ> dial attempt failed: dial tcp4 0.0.0.0:4689->10.19.251.97:4689: i/o timeout"}

**Comment by raullenchai** [comment]
Testnet & mainnet should have bootnode always on. So this should not be a problem for them.
