### ISSUE TITLE
cannot find package "context"

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#6]
1) What i did

Tried to run 
```
make fmt; make build
```
2) What i saw
```
iotex-core/logger/logger.go:10:2: cannot find package "context" in any of:
```
3) What i expected to see
Build work properly.

It would appear as though context is imported but not available, it was not installed with other glide installation like in glide.yaml

```
- package: golang.org/x/net
```

**Comment by zjshen14** [comment]
Try`glide update` and then `glide install` again?

**Comment by SoyTheCat** [comment]
`golang.org/x/net/context` is moved to std `context` since Go 1.7. We can resolve this issue by rename all `golang.org/x/net/context` import use into using just `context`.

**Comment by jerkyrs** [comment]
i am running on go 1.6.1 , it wants the context import to be declared as ```golang.org/x/net/context```

I added the ```- package: goland.org/x/net``` manually to glide.yaml and got further but still got

```
go build -o ./bin/server -v ./server
logger/logger.go:10:2: cannot find package "context" in any of:
```

**Comment by SoyTheCat** [comment]
our environment use go 1.9. Please upgrade your go version to avoid unexpected error

**Comment by jerkyrs** [comment]
so i updated to go 1.9
```
[iotex@localhost iotex-core]$ go version
go version go1.9.4 linux/amd64
```

Works as expected, but as per #5 if this was all done within the Docker container my local environment would be irrelevant
