### ISSUE TITLE
Using TempDir/File to replace hard coded path in tests

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#615]
Now in lots of tests, we hard code a path for test file creation, and we defer the deletion upon finishing the tests. This manual handling could be replaced by using golang's  TempDir/File.

**Comment by ashishsnigam** [comment]
@zjshen14 I can take up this task. You can assign it to my name.

**Comment by raullenchai** [comment]
@ashishsnigam Thanks. Pls feel free to take it! You can start with one package.

**Comment by ashishsnigam** [comment]
@raullenchai Sure.

**Comment by ashishsnigam** [comment]
Please have a code review for https://github.com/iotexproject/iotex-core/pull/663/
Suggest if code changes matches the expectation and we can replicate this in all other tests.
@zjshen14 @raullenchai

**Comment by raullenchai** [comment]
@ashishsnigam if this is all done, pls close it
