### ISSUE TITLE
gRPC iotexapi.APIService.GetChainMeta method returns an empty epoch number

### ISSUE THREAD

**Issue by atorrente75** [iotexproject/iotex-core#622]
iotex@IoTeX-testnode1:~$ grpcurl -plaintext localhost:14014 iotexapi.APIService.GetChainMeta | jq .
{
  "chainMeta": {
    "height": 4853,
    "supply": "10000000000000000000000000000",
    "numActions": 481581,
    "tps": 481581,
    "epoch": {}
  }
}

**Comment by raullenchai** [comment]
Thanks for reporting! @CoderZhi is working on the fix.

**Comment by raullenchai** [comment]
Done.
