### ISSUE TITLE
Review all negative cases of big.Int

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#625]
As Zhenchuan found that a transfer with negative balance could be committed (but the corresponding account balance won't be impacted). Need a review of all big.Int usages.

**Comment by atorrente75** [comment]
I found another problem that could be related. Compiling from the sources, i get this error:

```
# github.com/iotexproject/iotex-core/action/protocol/vote
action/protocol/vote/protocol.go:83:15: Wrapf format %d has arg voteFrom.Balance of wrong type *math/big.Int
FAIL    github.com/iotexproject/iotex-core/action/protocol/vote [build failed]
```
