### ISSUE TITLE
CI for building on Ubuntu

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#716]
We already have circle ci build/test for macos and docker (debian). Need to build/test on ubuntu as well.

**Comment by feigu1984** [comment]
circlie ci  latest  ubuntu 14.04, default golang 1.9  ;  ./go.test.sh
```
# github.com/iotexproject/iotex-core/vendor/github.com/multiformats/go-multiaddr
vendor/github.com/multiformats/go-multiaddr/codec.go:140:10: undefined: strings.Builder
vendor/github.com/multiformats/go-multiaddr/component.go:118:8: undefined: strings.Builder
vendor/github.com/multiformats/go-multiaddr/component.go:125:32: undefined: strings.Builder
FAIL	github.com/iotexproject/iotex-core/api [build failed]
Exited with code 2
```
1,  I'm not sure if it's a code problem?
2,  I'll try to update  golang > 1.11.5

**Comment by feigu1984** [comment]
when golang update 1.11.6   ./go.test.sh  working
found out   last macos  
`go test github.com/iotexproject/iotex-core/action/protocol/vote/`

> protocol.go:81:15: Wrapf format %d has arg voteFrom.Balance of wrong type *math/big.Int

use go 1.12    change 1.11.5/6   ok

**Comment by raullenchai** [comment]
@feigu1984 right, golang ≥ 1.11.5 is required.

**Comment by raullenchai** [comment]
@lzxm160 pls dig out why unit test always fail under ubuntu -- low priority tho

**Comment by lzxm160** [comment]
> @lzxm160 pls dig out why unit test always fail under ubuntu -- low priority tho

sure

**Comment by lzxm160** [comment]
I tested with ubuntu 16.04 and golang 1.12.5,there's no error found.I also build a docker image ,and added it to config.yml.
https://github.com/iotexproject/iotex-core/pull/1170,this is the test demo.
I think my docker repo need auth,maybe someone can help me build it under docker account iotex

**Comment by lzxm160** [comment]
The ubuntu ci test used default resouce_class medium,need add "resource_class: large" to config.yaml
Too few resources caused test results error
