### ISSUE TITLE
Setup 2 Kovan Fullnodes for internal testings

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#734]

**Comment by feigu1984** [comment]
finished !!

about geth process lose,  syslog record
> Mar 14 16:41:13 us-west-1 kernel: [175314.570935] Out of memory: Kill process 6013 (geth) score 940 or sacrifice child

Consider increasing memory if it occurs frequently

**Comment by raullenchai** [comment]
Cool, thx
