### ISSUE TITLE
Test failed in action/protocol/execution/protocol_test.go

### ISSUE THREAD

**Issue by Frankonly** [iotexproject/iotex-core#774]
2019-03-19T04:47:58.583Z	ERROR	evm/evmstatedbadapter.go:528	Failed to get state.	{"error": "not exist in trie", "errorVerbose": "not exist in trie\ngithub.com/iotexproject/iotex-core/db/trie.init\n\t/go/src/github.com/iotexproject/iotex-core/db/trie/trie.go:37\ngithub.com/iotexproject/iotex-core/action/protocol/execution/evm.init\n\t<autogenerated>:1\ngithub.com/iotexproject/iotex-core/action/protocol/execution.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:189\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}
github.com/iotexproject/iotex-core/action/protocol/execution/evm.(*StateDBAdapter).GetState
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/evm/evmstatedbadapter.go:528
github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm.gasSStore
	/go/src/github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm/gas_table.go:121
github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run
	/go/src/github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm/interpreter.go:224
github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm.run
	/go/src/github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm/evm.go:64
github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm.(*EVM).Call
	/go/src/github.com/iotexproject/iotex-core/vendor/github.com/ethereum/go-ethereum/core/vm/evm.go:213
github.com/iotexproject/iotex-core/action/protocol/execution/evm.executeInEVM
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/evm/evm.go:222
github.com/iotexproject/iotex-core/action/protocol/execution/evm.ExecuteContract
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/evm/evm.go:147
github.com/iotexproject/iotex-core/action/protocol/execution.(*Protocol).Handle
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/protocol.go:42
github.com/iotexproject/iotex-core/state/factory.(*stateTX).RunAction
	/go/src/github.com/iotexproject/iotex-core/state/factory/statetx.go:105
github.com/iotexproject/iotex-core/blockchain.(*blockchain).pickAndRunActions
	/go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:911
github.com/iotexproject/iotex-core/blockchain.(*blockchain).MintNewBlock
	/go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:475
github.com/iotexproject/iotex-core/action/protocol/execution.TestProtocol_Handle.func1
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/protocol_test.go:331
github.com/iotexproject/iotex-core/action/protocol/execution.TestProtocol_Handle.func4
	/go/src/github.com/iotexproject/iotex-core/action/protocol/execution/protocol_test.go:781
testing.tRunner
	/usr/local/go/src/testing/testing.go:827

**Comment by Frankonly** [comment]
failed on circle-ci-docker

**Comment by zjshen14** [comment]
It doesn't say the test failed. It's common not to get the state from db

**Comment by zjshen14** [comment]
Can't reproduce
