### ISSUE TITLE
Write e2e test for ERC721 token smart contract

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-core#781]
Please refer to the Fp token smart contract test: 
https://github.com/iotexproject/iotex-core/blob/master/tools/executiontester/executiontester.go

1. start a single IoTeX server;
2. create two accounts;
3. create a token contract;
4. transfer the token between two accounts;
5. compare the actual sum of tokens with the amount of creation

**Comment by guo** [comment]
a reference implementation of ERC721 token is here:
https://github.com/0xcert/ethereum-erc721
