### ISSUE TITLE
ioctl supports Windows

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#801]
1. need a way to build ioctl on windows
2. need the curl install script to support windows

**Comment by raullenchai** [comment]
let's set up a windows machine with go environment, pull iotex-core every 24 hours, build a binary, upload to s3://ioctl.

**Comment by feigu1984** [comment]
There are many problems
1, exec gcc executable file not found in path windows
2, C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
3,  buildcli.sh   dos  fileformat -->   unix
