### ISSUE TITLE
Curl cli install script fails if not root

### ISSUE THREAD

**Issue by jason-james** [iotexproject/iotex-core#803]
If the bin directory is evaluated as /usr/local/bin, the install will fail unless in root with error message 

```mv: cannot move '/tmp/tmp.IfCIWZ5xFf' to '/usr/go/bin/ioctl': No such file or directory```

May be friendlier to add sudo to the final step to avoid this for users without root access

Issue pertains to https://raw.githubusercontent.com/iotexproject/iotex-core/master/install-cli.sh

**Comment by Frankonly** [comment]
Thanks for reporting this issue. @jason-james
