### ISSUE TITLE
Operator should not be able to claim reward

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#818]
### What version of iotex-core are you using (`ioctl version`)?
Not relevant

### What operating system and processor architecture are you using?
rc5-hotfix1

### What did you do? If possible, provide a recipe for reproducing the error.
Operator can claim a part of the reward

### What did you expect to see?
Operator cannot claim the reward

**Comment by zjshen14** [comment]
Fixed with https://github.com/iotexproject/iotex-core/pull/821
