### ISSUE TITLE
Should be clearer for candidates to see when they are expected to delegate

### ISSUE THREAD

**Issue by jason-james** [iotexproject/iotex-core#824]
Sometimes while our nodes are running we come back and check their status and suddenly they are no longer a delegate and not producing blocks. When this happens its not clear if something went wrong with our note setup or if its expected behaviour. There should be some changes made to make it clearer when we next expect to be a delegate.

Perhaps the clearest thing for us would be to tell us how many epochs the current delegates list will last for, and also allow individual delegates to query how many epochs until they next will be a delegate

**Comment by zjshen14** [comment]
@jason-james, thanks for the suggestion! Several points to share with you:

1. Rotation among the delegate pool is designed to involve a bigger community as well as prevent some colluding party hold the network forever.
2. To achieve this, we intentionally make the future delegates could not be predicted way before the epoch start. Currently, you could know this one epoch upfront.
3. As long as your node is still in the delegate pool (36 for our initial launch), your node is qualified for being the delegate. The only reason that your node isn't in the current epoch's delegate list is that it's not chosen for this epoch. And the chance is fair to all delegates in the pool.

**Comment by jason-james** [comment]
Thanks @zjshen14 for responding. I got it and agree with you that its good to not allow too much future insight into when exactly which nodes will be a delegate, but I still think there needs to be something to know that our node is operating OK. For example even though we are top 36 on the website, we might have doubts that the website is accuractly reflecting that at times when we are not delegates.

Simple change could be adding one more section on ```ioctl node delegate``` response which says "Eligible candidates not selected this epoch: [list all addressses in top 36 that are not selected to be part of the 24 this epoch]". Then in this way we know 100% there is not an issue with our node and we know its just Roll DPoS doing its work

**Comment by zjshen14** [comment]
> "Eligible candidates not selected this epoch: [list all addressses in top 36 that are not selected to be part of the 24 this epoch]".

This is a good idea

**Comment by zjshen14** [comment]
@lizhefeng can you see if you could help this? thanks!

**Comment by raullenchai** [comment]
<img width="874" alt="Screen Shot 2019-03-29 at 4 00 21 PM" src="https://user-images.githubusercontent.com/989846/55266754-c6996300-523b-11e9-98c1-d8eecea2c95c.png">
Should be good for you @jason-james

**Comment by jason-james** [comment]
It is! Thanks
