### ISSUE TITLE
show a summary of current node status via cli

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#862]
**What would you like to be added**:
E.g. current height, whether-up-to-date, and etc.

**Why is this needed**:

**Comment by raullenchai** [comment]
Blocked by #900

**Comment by zjshen14** [comment]
`ioctl bc info` can do this already

`whether-up-to-date` a way bigger chain intelligence question

**Comment by Frankonly** [comment]
@zjshen14 How can I get the hip height of the blockchain.

**Comment by raullenchai** [comment]
What else is needed?
