### ISSUE TITLE
Deploy contract cannot pass in amount and transfer the amount to contract created

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-core#865]
### What version of iotex-core are you using (`ioctl version`)?
v0.5.0 rc6

### What did you do? If possible, provide a recipe for reproducing the error.
Deploy a contract with specific amount > 0

### What did you expect to see?
Amount is not transferred to the contract created

### What did you see instead?
amount is transferred to the contract created

**Comment by raullenchai** [comment]
Is this still an issue?
