### ISSUE TITLE
ioctl action hash fails to get an existing action

### ISSUE THREAD

**Issue by atorrente75** [iotexproject/iotex-core#872]
### What version of iotex-core are you using (`ioctl version`)?

Client:
packageVersion:"v0.5.0-rc6" packageCommitID:"36143b89d7d82280322e1e768ed387c92acb49a5" gitStatus:"dirty" goVersion:"go version go1.12 linux/amd64" buidTime:"2019-03-27-CET/17:17:24"

Server: localhost:14014
packageVersion:"v0.5.0-rc6" packageCommitID:"36143b89d7d82280322e1e768ed387c92acb49a5" gitStatus:"dirty" goVersion:"go version go1.12 linux/amd64" buidTime:"2019-03-27-CET/17:17:30"

### What operating system and processor architecture are you using?

Linux IoTeX-testnode1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you do? If possible, provide a recipe for reproducing the error.

ioctl action hash 1ce025b850acfb20f2b813874e7c5caa3a5ed0d4c90da642732c9824f087cfa6

### What did you expect to see?

```
{
  "actionInfo": [
    {
      "action": {
        "core": {
          "version": 1,
          "gasPrice": "0",
          "grantReward": {
            "type": "EpochReward"
          }
        },
        "senderPubKey": "BPnume2UmdZyRsW/6uQ/IVy/N5+PKJWqpzywr0iv8PPm2qMt4dUd7rvS5YDEh5LFnlppLnfW+gweRMral0kESbk=",
        "signature": "G694faHDI5A90OIxabxcjzSv3QAJ6FIEYPpjQ2fzokhHe7ifyLjgoqZKiRfajRgGsVUo3qpTAIDPB7BvGsEz5AE="
      },
      "actHash": "1ce025b850acfb20f2b813874e7c5caa3a5ed0d4c90da642732c9824f087cfa6",
      "blkHash": "3afcdb6795cfebfbe7bcf05023ef217830f55b417d12fef9a8c5f61a5b618500"
    }
  ]
}
```

### What did you see instead?

action can not match

### More info
 
Instead i can get the action info using this command :

`grpcurl -plaintext -d '{"byHash": {"actionHash": "1ce025b850acfb20f2b813874e7c5caa3a5ed0d4c90da642732c9824f087cfa6"}}' localhost:14014 iotexapi.APIService.GetActions`

**Comment by zjshen14** [comment]
@Frankonly pls take a look

**Comment by Frankonly** [comment]
hash cmd support only a few actions now, it will support all kinds of actions soon.
