### ISSUE TITLE
cannot find package "github.com/golang/glog"

### ISSUE THREAD

**Issue by FishMeat** [iotexproject/iotex-core#9]
When I run make test, there is an error:

`
make test
go fmt ./...
go test -short ./...
blockdb/blockdb.go:13:2: cannot find package "github.com/golang/glog" in any of:
	/Users/sggb/go/src/github.com/iotexproject/iotex-core/vendor/github.com/golang/glog (vendor tree)
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/golang/glog (from $GOROOT)
	/Users/sggb/go/src/github.com/golang/glog (from $GOPATH)
make: *** [test] Error 1
`

**Comment by lizhefeng** [comment]
Fixed by removing blockdb package in commit ea831161926f60aaf077ffa63dbddd430ba930a0.
