### ISSUE TITLE
windows buildcli faild

### ISSUE THREAD

**Issue by feigu1984** [iotexproject/iotex-core#928]
Maybe after March 29th, Windows buildcli.sh failed!

![windows_failed](https://user-images.githubusercontent.com/4827661/55380673-7da32080-5553-11e9-887e-1eaeee7a453f.png)

[windows_buildcli_failed.txt](https://github.com/iotexproject/iotex-core/files/3036691/windows_buildcli_failed.txt)

**Comment by raullenchai** [comment]
@Frankonly something is going rouge with cgo. pls take a look
