### ISSUE TITLE
Better ioctl installation handling in linux env

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#941]
**What would you like to be added**:

I hotfix an installation issue on linux, but it only works for the latest release. We need to fix it for unstable. 

In addition, see how to make this backward compatible because our previous release candidate doesn't have libsect283k1_ubuntu.so.

If I missed other points of installing the shared library, feel free to raise them. Thanks

**Why is this needed**:

**Comment by wqwqwq219** [comment]
mv ibsect283k1_ubuntu.so  to /usr/lib64 on linux will resolve it

**Comment by zjshen14** [comment]
@feigu1984 can you fix @wqwqwq219 's issue too?

**Comment by zjshen14** [comment]
We still need it until we push next release candidate
