### ISSUE TITLE
Generate a build/install link for action injector

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-core#942]
**What would you like to be added**:
A Curl link for action injector build and install.
**Why is this needed**:
For the convenience of building and installing action injector

**Comment by feigu1984** [comment]
Not very clear, any context, easy to understand

**Comment by raullenchai** [comment]
@feigu1984 
injector is another cli-alike tool we have for operating with iotex-core blockchain. @lizhefeng wants something similar as ioctl:
- a curl script for install
- nightly build
- and so on

**Comment by FeirenK** [comment]
fix https://github.com/iotexproject/iotex-core/pull/1009/
