### ISSUE TITLE
buildcli.sh will make git status dirty

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#944]
Using it build ioctl binary will make version like this:

```
packageVersion:"v0.5.0-rc8" packageCommitID:"ed955b701cd1c1695cc41fb7a39335e7a691d91b" gitStatus:"dirty" goVersion:"go version go1.11.5 linux/amd64" buildTime:"2019-04-04-UTC/04:20:40"
```

**Comment by raullenchai** [comment]
`packageVersion:"snapshot-v0.6.0-156-ga5f7a59b" packageCommitID:"a5f7a59b4c940ba012c0cba190347af91a508f6b" gitStatus:"clean" goVersion:"go version go1.11.6 darwin/amd64" buildTime:"2019-04-08-PDT/00:00:29"`

Verified
