### ISSUE TITLE
TPS doesn't match the number of actions in a block

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#951]
### What version of iotex-core are you using (`ioctl version`)?

```
zjshen@testnet-zjshen:~$ ioctl version
Client:
packageVersion:"v0.5.0-rc8" packageCommitID:"ed955b701cd1c1695cc41fb7a39335e7a691d91b" gitStatus:"dirty" goVersion:"go version go1.11.5 linux/amd64" buildTime:"2019-04-04-UTC/04:20:40"

Server: api.iotex.one:80
packageVersion:"v0.5.0-rc8" packageCommitID:"ed955b701cd1c1695cc41fb7a39335e7a691d91b" gitStatus:"clean" goVersion:"go version go1.11.5 linux/amd64" buildTime:"2019-04-03-UTC/19:08:13"
```

### What operating system and processor architecture are you using?

in browser

and in ubuntu amd

### What did you do? If possible, provide a recipe for reproducing the error.

See my comments below

### What did you expect to see?

number of actions in a block / 10 sec should match tps

### What did you see instead?
All blocks contain no more than 2000 tx.
<img width="1680" alt="Screen Shot 2019-04-04 at 11 09 15 AM" src="https://user-images.githubusercontent.com/35021395/55578272-5ae74800-56ca-11e9-8a19-5917393808a7.png">

However tps is said to be 217.
<img width="1680" alt="Screen Shot 2019-04-04 at 11 09 21 AM" src="https://user-images.githubusercontent.com/35021395/55578278-5f136580-56ca-11e9-843f-0c351cebe437.png">

**Comment by lizhefeng** [comment]
This issue cannot be reproduced and doesn't happen again. Closed for now.
