### ISSUE TITLE
gRPC iotexapi.APIService.GetActions "byAddr" returns an empty grantReward type

### ISSUE THREAD

**Issue by atorrente75** [iotexproject/iotex-core#954]
### What version of iotex-core are you using (`ioctl version`)?
Client:
packageVersion:"v0.5.0-rc8" packageCommitID:"ed955b701cd1c1695cc41fb7a39335e7a691d91b" gitStatus:"dirty" goVersion:"go version go1.12 linux/amd64" buildTime:"2019-04-04-CEST/13:10:32"

Server: localhost:14014
packageVersion:"v0.5.0-rc8" packageCommitID:"ed955b701cd1c1695cc41fb7a39335e7a691d91b" gitStatus:"dirty" goVersion:"go version go1.12 linux/amd64" buildTime:"2019-04-04-CEST/13:10:39"

### What operating system and processor architecture are you using?

4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you do? If possible, provide a recipe for reproducing the error.

`grpcurl -plaintext -d '{"byAddr": {"address": "io1fra0fx6akacny9asewt7vyvggqq4rtq3eznccr", "count": "5"}}' localhost:14014 iotexapi.APIService.GetActions
`
### What did you expect to see?

grantReward type for every action 

### What did you see instead?

grantReward type is always empty:

```
{
  "actionInfo": [
    {
      "action": {
        "core": {
          "version": 1,
          "gasPrice": "0",
          "grantReward": {

          }
        },
        "senderPubKey": "BPnume2UmdZyRsW/6uQ/IVy/N5+PKJWqpzywr0iv8PPm2qMt4dUd7rvS5YDEh5LFnlppLnfW+gweRMral0kESbk=",
        "signature": "7+yzVj6hZR2Ch0RpuFnYfu2pqj0sSvCXOM8FhX9tjyBDoFIuRdH+cLZYZQDofVl8zvYGxGssaFkfpw8Kn5WkowE="
      },
      "actHash": "7a4963206ec68e9aa1603cc6217c2fd7acb18b586beccc17f2bde976296e42b5",
      "blkHash": "d5cf22422255bf2c1c32dfb761135548a063a61969e9f692f968d28f6868c362"
    }
  ]
}
```
....

**Comment by zjshen14** [comment]
@atorrente75 I think this is the problem of grpcurl. The enum type wasn't able to visualize properly. I can actually assert the type is epoch reward for 1ce025b850acfb20f2b813874e7c5caa3a5ed0d4c90da642732c9824f087cfa6 and is block reward for 7a4963206ec68e9aa1603cc6217c2fd7acb18b586beccc17f2bde976296e42b5

**Comment by zjshen14** [comment]
Close it. If you don't think so, please feel free to restart it
