### ISSUE TITLE
ioctl client output not sent to stdout anymore, but stderr instead

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#970]
After the latest update it seems like the ioctl command output is now redirected to stderr instead of stdout.

All scripts based on piping do not work, unless using |&.

this doesn't work anymore (last line should not be in the output of egrep):
```
 » ioctl bc info | egrep height 
height:25297  numActions:5080711  tps:22
epochNum:71  epochStartHeight:25201  gravityChainStartHeight:7516600
```
this works:

```
 » ioctl bc info |& egrep height                                                                                                         
height:25302  numActions:5081717  tps:22
```

**Comment by raullenchai** [comment]
@simonerom if can use `|&`, this seems not an issue?

**Comment by Frankonly** [comment]
@CoderZhi

**Comment by simonerom** [comment]
@raullenchai yeah, not necessarily an issue, but I thought it’s worth reporting: it sounds like a mistake, unless it’s been done on purpose for some reason.

**Comment by jerkyrs** [comment]
does seem incorrect to me you just expect | to work

**Comment by zjshen14** [comment]
https://github.com/iotexproject/iotex-core/pull/972

Will rollout with rc9
