### ISSUE TITLE
Name registration (change reward address) does not work with ledger nano s. Delegate page doesn't work on Brave Browser

### ISSUE THREAD

**Issue by jason-james** [iotexproject/iotex-core#979]
My reward and operator address has been set to be equal a couple of weeks ago, this is not ideal for security reasons. Trying to change the reward address on member-rehearsal.iotex.io or member.iotex.io results in one of two errors:

`ALERT: TransportError: Failed to sign with Ledger device: U2F TIMEOUT`
or
`ALERT: Ledger: The transaction signature is not valid`

With the first error, it asks me to confirm once, then the metamask window has a loading spinner and ends up with the timeout message. With the second error, I have to confirm 3 transactions on my ledger, then the metamask window gives that error.

In both cases I have a 1m gas limit and 4 gas price

I have tried once every day for the past week and its the same result. I don't know if this happens without a ledger device, I can't test that. I also can't test name registration on testnet with ledger, because my testnet admin address is not from a ledger. It's probably not an issue with my ledger because it's able to make regular transactions and smart contract interactions just fine.

**Comment by jason-james** [comment]
Ok, so it seems like this is a Ledger/Chrome issue, however, Opera browser doesn't support Ledger addresses for Metamask, and member.iotex.io has a bug with the Delegate page for Ledger on Brave browser.

I am logged into Metamask, I can see my correct details in 'My Votes', but when I click 'Delegate' it has a screen of 'Please Connect Metamask', and there's no way to get around it

**Comment by jason-james** [comment]
Last update about this from me, to workaround you can install metamask direct from source on Opera. The version in the extensions store does not support metamask. Install the CHROME version on Opera, and it will work.

**Comment by raullenchai** [comment]
This has been fixed a while ago
