### ISSUE TITLE
P2P Optimization for active delegates

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#995]
**What would you like to be added**:
In a given round where there are 24 delegates the proposer should utilize there available outbound connections as per #994 to send to other active delegates first so the consensus delegates in that round can get the block as fast as possible. 

**Why is this needed**:
This would ensure proposer distributes the block to the 23 other consensus delegates in the given round so they can validate it as fast as possible

**Comment by raullenchai** [comment]
Close as it is stale.
